u(2,'transport',['Từ IP đến giao tiếp giữa ứng dụng','From IP to application communication'],[0,2,3],
['IP biết host đích nhưng một host chạy nhiều process. Transport bổ sung phân phối tới đúng process và các dịch vụ mà ứng dụng cần trên nền IP best-effort.','IP identifies a destination host, but that host runs many processes. Transport adds process delivery and application-facing services over best-effort IP.'],[
['Logical end-to-end service','Logical end-to-end service','Sender nhận message từ app, tạo segment, giao cho IP. Receiver transport chuyển data tới app. “Connection” là state logic ở endpoints; không phải một circuit riêng được đặt trước qua mọi router. UDP có logical communication dù không setup connection.','The sender forms segments from application messages and hands them to IP. Receiver transport dispatches data to applications. A connection is endpoint state, not a reserved circuit through every router. UDP supports logical communication without connection establishment.'],
['Multiplex và demultiplex','Multiplex and demultiplex','Multiplexing gom data từ nhiều sockets, gắn header rồi gửi xuống IP. Demultiplexing đọc header của incoming segment và chọn đúng socket. Port là identifier phục vụ việc này; địa chỉ IP đơn lẻ không phân biệt browser, music app và các connection đang chạy.','Multiplexing gathers data from sockets, adds headers and passes segments to IP. Demultiplexing examines incoming headers and selects a socket. Ports enable this distinction; an IP alone cannot separate a browser, music app and their connections.'],
['Ví dụ web của module','The module’s web example','Trong ví dụ HTTP-over-TCP: browser tìm địa chỉ server qua DNS, lập TCP connection, gửi GET, nhận HTTP response chứa HTML rồi render. DNS, TCP và HTTP giải quyết ba trách nhiệm khác nhau. Ví dụ dùng TCP không hàm ý mọi phiên bản HTTP đều dùng TCP.','In the module’s HTTP-over-TCP example, the browser resolves the server with DNS, establishes TCP, sends GET, receives an HTTP response containing HTML and renders it. DNS, TCP and HTTP have different roles. This example does not imply every HTTP version uses TCP.']],
['Hai app cùng dùng 192.0.2.10. Một packet chỉ mang IP đó chưa nói nó thuộc cuộc gọi hay file download; transport header cung cấp thông tin socket cần thiết.','Two apps share 192.0.2.10. That IP alone does not say whether incoming data belongs to a call or download; transport headers supply the socket information.'],
['Transport không thể biến network ngừng hoạt động vĩnh viễn thành dịch vụ thành công. TCP cố phục hồi và có thể báo lỗi kết nối.','Transport cannot make a permanently failed network succeed. TCP attempts recovery and can report connection failure.'],
['Phân biệt multiplexing và demultiplexing bằng hướng dữ liệu?','How do multiplexing and demultiplexing differ by direction?'],['Gửi: nhiều sockets → segments → IP. Nhận: segments từ IP → đúng socket.','Sending: sockets → segments → IP. Receiving: IP segments → the correct socket.']);

u(2,'sockets',['UDP 2-tuple, TCP 4-tuple','UDP two-tuples, TCP four-tuples'],[4],
['Server dùng chung một listening port vẫn có thể giữ nhiều TCP connections vì từng connection có identifier đầy đủ hơn destination port.','A server can accept many TCP connections on one listening port because each connection has an identifier richer than the destination port.'],[
['UDP trong mô hình lớp','UDP in the course model','Socket UDP connectionless được xác định bởi (destination IP, destination port). A:5000 và C:6000 gửi tới B:12000 có thể vào cùng UDP socket. Receiver vẫn thấy source tuple để reply. Connected UDP và các tùy chọn OS có thể khác, nhưng bài tập module dùng mô hình 2-tuple này.','An unconnected UDP socket is identified by destination IP and port in the course model. A:5000 and C:6000 sending to B:12000 can reach the same socket. The source tuple remains available for replies. Connected UDP and OS options add nuances beyond this model.'],
['TCP connection sockets','TCP connection sockets','TCP dùng (source IP, source port, destination IP, destination port). Listening socket nhận yêu cầu; accepted sockets phân biệt từng connection. Cùng destination :80 và cùng client port vẫn khác connection nếu source IP khác.','TCP uses source IP, source port, destination IP and destination port. The listening socket accepts requests; connected sockets identify individual connections. A shared destination :80 and client port still identify different connections when source IP differs.'],
['HTTP persistent','Persistent HTTP','Persistent connection tái sử dụng TCP connection cho nhiều HTTP exchanges; non-persistent tạo/đóng connection cho mỗi exchange trong mô hình bài học. Tạo nhiều connection làm tăng handshake, state và tải xử lý.','A persistent connection reuses TCP for multiple HTTP exchanges; the course’s non-persistent model opens/closes a connection per exchange. Repeated creation adds handshakes, state and processing load.']],
['A:26145→B:80 và C:26145→B:80 là hai TCP connections khác. C:7532→B:80 là connection thứ ba. Server không cần đổi listening port cho mỗi client.','A:26145→B:80 and C:26145→B:80 are distinct TCP connections. C:7532→B:80 is a third. The server need not change its listening port for each client.'],
['Port không đồng nghĩa duy nhất với process trên toàn hệ thống: listening và accepted sockets có thể cùng local port. Luôn dùng identifier đúng ngữ cảnh.','A port is not a globally unique process identity: listening and accepted sockets may share a local port. Use the context’s complete identifier.'],
['Đổi source port có tạo identifier TCP khác không?','Does changing the source port change the TCP identifier?'],['Có; bất kỳ trường nào trong 4-tuple thay đổi đều làm tuple khác.','Yes. Changing any field changes the four-tuple.'],'sockets');

u(2,'udp',['UDP: tối giản có chủ đích','UDP: minimal by design'],[5],
['UDP không tự retransmit, giữ thứ tự, setup connection hay điều chỉnh congestion window. App chọn nó khi cần tự kiểm soát trade-off, nhưng trách nhiệm còn lại không biến mất.','UDP does not provide retransmission, ordering, connection setup or a congestion window. Applications choose it to control trade-offs themselves; missing responsibilities do not disappear.'],[
['Vì sao dùng?','Why use it?','Không chờ handshake, ít connection state, ít transport overhead. App có thể bỏ data quá trễ thay vì đợi retransmission. DNS thường dùng UDP; voice/game thời gian thực có thể ưu tiên latency. Điều này không bảo đảm packet UDP luôn tới nhanh hơn packet TCP trên mọi network.','No handshake wait, little connection state and low transport overhead can suit delay-sensitive use. An app can discard stale data instead of waiting for retransmission. DNS commonly uses UDP; real-time voice/games may prioritize latency. This does not guarantee UDP always arrives faster on every network.'],
['Header 8 byte','The eight-byte header','Bốn trường 16-bit: source port, destination port, length và checksum. Length gồm header+payload. Payload 24 bytes → UDP length 32 bytes. Header của IP/link nằm ngoài con số này.','Four 16-bit fields contain source port, destination port, length and checksum. Length includes the UDP header and payload. A 24-byte payload gives UDP length 32 bytes; IP/link headers are outside this length.'],
['Checksum','Checksum','One’s-complement sum có end-around carry trên các word 16-bit rồi đảo bit; receiver kiểm tra tổng có checksum. Checksum bao gồm pseudo-header, UDP header và application data, không chỉ ba trường đầu. Nó phát hiện nhiều lỗi nhưng không sửa lỗi, không xác thực người gửi và không bảo đảm phát hiện mọi corruption.','A one’s-complement sum uses end-around carry over 16-bit words, then complements the result; the receiver checks the sum including the checksum. Coverage includes the pseudo-header, UDP header and application data, not just the first three fields. It detects many errors but does not repair them, authenticate the sender or detect every corruption.']],
['Minh họa checksum rút gọn hai words: 0x0001 + 0x0002 = 0x0003; checksum = 0xFFFC. Cộng ba word được 0xFFFF. Đây là minh họa arithmetic, chưa phải checksum đầy đủ của một UDP packet.','For two illustrative words, 0x0001 + 0x0002 = 0x0003 and checksum = 0xFFFC. Adding all three gives 0xFFFF. This demonstrates arithmetic, not a complete UDP packet checksum.'],
['Không có congestion control trong UDP không có nghĩa app nên gửi vô hạn; app/protocol trên UDP cần hành vi phù hợp với network.','UDP lacking congestion control does not justify unlimited sending; applications/protocols above it need network-appropriate behavior.'],
['Checksum đúng có chứng minh đủ mọi packet đã tới không?','Does a correct checksum prove every packet arrived?'],['Không. Nó kiểm tra data của datagram nhận được, không phát hiện toàn bộ các datagram bị mất.','No. It checks a received datagram, not the completeness of a multi-datagram transfer.']);

u(2,'handshake',['TCP handshake và teardown','TCP handshake and teardown'],[6],
['TCP phải thống nhất sequence spaces và trạng thái hai phía trước khi trao đổi dữ liệu trong mô hình handshake cơ bản. Đóng connection cũng cần giải quyết từng chiều riêng.','TCP establishes sequence spaces and endpoint state before data in the basic handshake model. Closing also handles the two directions separately.'],[
['Ba thông điệp','Three messages','Client SYN: seq=x, SYN=1. Server SYN-ACK: seq=y, ack=x+1, SYN=1, ACK=1. Client ACK: seq=x+1, ack=y+1, SYN=0, ACK=1. SYN chiếm một sequence number nên ACK tăng 1 dù SYN không có application data.','Client SYN: seq=x, SYN=1. Server SYN-ACK: seq=y, ack=x+1, SYN=1, ACK=1. Client ACK: seq=x+1, ack=y+1, SYN=0, ACK=1. SYN consumes one sequence number, explaining the increment without application data.'],
['Hai sequence spaces','Two sequence spaces','Client và server chọn initial sequence number riêng: ACK của A xác nhận byte stream từ B, không phải bộ đếm gửi của A. Handshake thiết lập buffer/control state và giúp xử lý các segment cũ bị trì hoãn.','Client and server choose separate initial sequence numbers. An ACK from A acknowledges B’s byte stream, not A’s sending counter. The handshake establishes buffering/control state and helps disambiguate delayed old segments.'],
['FIN và TIME_WAIT','FIN and TIME_WAIT','Normal teardown minh họa: A FIN → B ACK → B FIN → A ACK. FIN nói phía đó hết dữ liệu gửi; chiều kia có thể tiếp tục tạm thời. ACK và FIN có thể được gộp nên không phải lúc nào cũng bốn packet riêng. TIME_WAIT ở active closer giúp xử lý retransmitted FIN và segment cũ.','Illustrative normal teardown: A FIN → B ACK → B FIN → A ACK. FIN ends one sending direction; the other may continue temporarily. ACK and FIN can combine, so four separate packets are not mandatory. TIME_WAIT at the active closer handles retransmitted FINs and old segments.']],
['x=100, y=900: SYN seq100; SYN-ACK seq900 ack101; ACK seq101 ack901. First client data bắt đầu seq101. Nếu gửi 50 bytes, byte kế tiếp của client là151.','With x=100, y=900: SYN seq100; SYN-ACK seq900 ack101; ACK seq101 ack901. Client data starts at101. After 50 bytes, the next client byte is151.'],
['Erratum Canvas: ACK thứ ba có SYN=0. “Connection established” không cấp bandwidth riêng và không có nghĩa HTTP request đã xử lý.','Canvas erratum: the third ACK has SYN=0. Establishment neither reserves bandwidth nor proves an HTTP request was processed.'],
['SYN seq=700 không data được ACK bằng số nào?','What ACK acknowledges a data-free SYN with seq=700?'],['701: SYN tiêu thụ một sequence number.','701: SYN consumes one sequence number.'],'handshake');

u(2,'arq',['Reliability: ACK, timeout và cửa sổ','Reliability: ACKs, timers and windows'],[7],
['Reliability cần nhận biết data thiếu và phục hồi mà không giao trùng/sai thứ tự cho app. ARQ kết hợp feedback và retransmission.','Reliability requires detecting missing data and recovering without duplicate or out-of-order application delivery. ARQ combines feedback with retransmission.'],[
['Stop-and-wait','Stop-and-wait','Gửi một packet, giữ bản sao và chờ ACK. Hết timeout thì gửi lại. Timeout quá ngắn tạo spurious retransmissions; quá dài phục hồi chậm. Ước lượng RTT giúp đặt timer, nhưng ACK bị mất và data bị mất đều có thể gây timeout.','Send one packet, keep a copy and wait for an ACK. Retransmit on timeout. Too short a timer causes spurious retransmissions; too long delays recovery. RTT estimates help, but either lost data or a lost ACK can cause timeout.'],
['Pipelining / sliding window','Pipelining / sliding window','Cho tối đa N packets hoặc W bytes unacknowledged để tận dụng lúc chờ RTT. ACK tới làm cửa sổ trượt và mở thêm chỗ gửi. Sender giữ data chưa ACK; receiver có thể giữ data out-of-order và data app chưa đọc.','Allow up to N packets or W bytes unacknowledged to use the path during RTT waits. ACKs slide the window and permit more sending. The sender stores unacknowledged data; the receiver may store out-of-order and unread data.'],
['Go-back-N và selective recovery','Go-back-N and selective recovery','GBN rút gọn: receiver bỏ out-of-order; mất packet7 kéo theo gửi lại7,8,9… Selective recovery giữ data đã nhận và chỉ retransmit phần thiếu. TCP dùng cumulative ACK; SACK là tùy chọn thương lượng để báo thêm các block nhận ngoài thứ tự. Không phải mọi TCP session đều có SACK.','Simplified Go-back-N discards out-of-order packets; losing7 causes7,8,9… to be resent. Selective recovery buffers received data and retransmits missing portions. TCP uses cumulative ACKs; negotiated SACK additionally reports out-of-order blocks. SACK is not universal to every TCP connection.']],
['Link100Mbps, RTT100ms, packet1000bytes: stop-and-wait xấp xỉ1000/0.1=10,000bytes/s, chỉ80kbps nếu bỏ qua transmission time. Window nhiều packet khai thác bandwidth tốt hơn.','At100Mbps, RTT100ms and1000-byte packets, stop-and-wait gives about1000/0.1=10,000bytes/s or80kbps when transmission time is neglected. A larger in-flight window uses the path better.'],
['TCP là byte stream: ranh giới app write không được bảo tồn như ranh giới message. App cần framing nếu muốn messages riêng.','TCP is a byte stream; application write boundaries are not preserved as message boundaries. Apps needing messages must frame them.'],
['ACK bị mất có nhất thiết làm mất data ở app không?','Does losing an ACK necessarily lose application data?'],['Không: retransmission/cumulative ACK có thể phục hồi thông tin; sequence numbers giúp loại duplicate data.','No. Retransmissions or later cumulative ACKs can recover feedback, while sequence numbers identify duplicate data.']);

u(2,'ack',['Byte numbering và fast retransmit','Byte numbering and fast retransmit'],[7],
['Trong TCP, ACK=k nghĩa là receiver đã có liên tục mọi byte trước k và đang mong k. Đây là điểm mấu chốt để đọc timeline loss.','TCP ACK=k means the receiver has all preceding bytes contiguously and expects k next. This is the key to reading loss timelines.'],[
['Sequence numbers đếm byte','Sequence numbers count bytes','Segment seq1000, length500 mang bytes1000–1499. Nhận đủ liên tục thì ACK1500. ACK1500 không có nghĩa “đã nhận byte1500”. SYN và FIN cũng dùng một sequence number; ACK thuần không dùng thêm sequence number.','A segment seq1000 with length500 contains bytes1000–1499. Contiguous receipt yields ACK1500, not confirmation that byte1500 arrived. SYN and FIN each consume one sequence number; a pure ACK does not.'],
['Hole giữ cumulative ACK đứng yên','A hole holds the cumulative ACK back','Mất1500–1999, nhưng2000–2499 tới: receiver vẫn ACK1500. Out-of-order blocks có thể buffer; app chưa được giao phần sau hole trong ordered stream. Nhận lại missing500bytes có thể làm ACK nhảy tới cuối toàn vùng liên tục đã buffer.','If1500–1999 is missing but2000–2499 arrives, the cumulative ACK remains1500. Out-of-order blocks may be buffered, but the application cannot receive beyond the hole in the ordered stream. Filling it can advance the ACK across already-buffered data.'],
['Ba duplicate ACK','Three duplicate ACKs','Classic fast retransmit dùng ba ACK lặp sau ACK gốc như bằng chứng mất segment và retransmit trước timeout. Data sau hole tới chứng tỏ network vẫn giao được một phần dữ liệu. Reordering cũng có thể tạo duplicate ACK nên đây là suy luận, không bằng chứng tuyệt đối.','Classic fast retransmit uses three duplicates after the original ACK as evidence of loss and retransmits before timeout. Later data arriving shows the path still delivers some data. Reordering can also generate duplicates, so this is an inference rather than proof.']],
['Receiver đã ACK1500. Segments2000,2500,3000 (mỗi500bytes) lần lượt tới trong khi1500 mất → ba duplicate ACK1500. Sender retransmit1500. Nếu receiver buffer cả ba, ACK mới có thể là3500.','The receiver already sent ACK1500. Segments2000,2500,3000 of500bytes arrive while1500 is missing, producing three duplicate ACK1500s. The sender retransmits1500; if all later data was buffered, the ACK can advance to3500.'],
['Slide dùng “packet7 / ACK7” là đánh số minh họa. Khi đề dùng TCP byte numbers, phải cộng payload lengths.','Slide “packet7 / ACK7” labels illustrate packet order. Actual TCP byte-number exercises require payload lengths.'],
['seq4000 dài1000 và seq5000 dài500 đến liên tục, ACK là bao nhiêu?','Contiguous seq4000 length1000 and seq5000 length500 arrive. What is the ACK?'],['5500, nếu mọi byte trước4000 cũng đã có.','5500, assuming all preceding bytes are already present.'],'ack');

u(2,'flow',['Flow control: bảo vệ receiver','Flow control: protect the receiver'],[8,9],
['Receiver có thể nhận từ network nhanh hơn ứng dụng đọc. Receive window quảng bá chỗ trống để sender không làm đầy buffer.','Network arrivals can outpace the receiving application. The receive window advertises free space so the sender avoids overflowing the buffer.'],[
['Buffer accounting','Buffer accounting','Trong mô hình liên tục của bài: occupied=LastByteRcvd−LastByteRead; rwnd=RcvBuffer−occupied. Nhận thêm data làm rwnd giảm; app đọc data làm rwnd tăng. ACK và việc app đọc không phải cùng một sự kiện.','In the course’s contiguous-data model, occupied=LastByteRcvd−LastByteRead and rwnd=RcvBuffer−occupied. Arrivals reduce rwnd; application reads increase it. Acknowledgment and application consumption are different events.'],
['Phía sender','At the sender','Outstanding=LastByteSent−LastByteAcked. Giới hạn flow control: outstanding≤rwnd. Nếu đang outstanding3000 và advertised window5000 thì chưa xét congestion, có thể gửi thêm tối đa2000 bytes, không phải5000.','Outstanding=LastByteSent−LastByteAcked. Flow control limits outstanding≤rwnd. With3000 outstanding and advertised window5000, up to2000 additional bytes fit before considering congestion—not5000.'],
['Zero-window deadlock','The zero-window problem','rwnd=0 làm normal sending dừng. Nếu update mở lại window mất, hai phía có thể chờ nhau. Persist/zero-window probes định kỳ (ví dụ một byte trong mô hình lớp) kích ACK chứa rwnd mới. Không phải liên tục đẩy data vào buffer đã đầy.','A zero window stops ordinary sending. A lost window-reopening update can leave both ends waiting. Periodic persist/zero-window probes, illustrated as one byte in the course, elicit current-window ACKs. They are not continuous sending into a full buffer.']],
['RcvBuffer=8000, LastByteRcvd=12000, LastByteRead=7000: occupied5000, rwnd3000. App đọc thêm2000, chưa nhận thêm: occupied3000 và rwnd5000.','With buffer8000, LastByteRcvd12000 and LastByteRead7000, occupied=5000 and rwnd=3000. If the app reads2000 more without arrivals, occupied=3000 and rwnd=5000.'],
['rwnd phản ánh receiver, không đo bottleneck link. Network rảnh vẫn có thể rwnd=0.','rwnd reflects the receiver, not the bottleneck link. An uncongested network can coexist with rwnd=0.'],
['ACK tăng nhưng app chưa đọc, buffer có nhất thiết trống hơn không?','Does an advancing ACK necessarily free the receiver buffer if the app has not read?'],['Không: receiver có thể ACK data vừa buffer mà application chưa consume.','No. The receiver may acknowledge buffered data before the application consumes it.'],'window');

u(2,'congestion',['Congestion: mục tiêu và tín hiệu','Congestion: goals and signals'],[10,11,12,13],
['Nhiều senders chia sẻ bottleneck capacity. Tổng arrival rate quá cao tạo queue, delay và loss; sender cần thay đổi khi flows đến/đi.','Senders share bottleneck capacity. Excess aggregate arrivals create queues, delay and loss, so sending must adapt as flows arrive and depart.'],[
['Bốn mục tiêu','Four goals','Efficiency: sử dụng capacity tốt. Fairness: trong mô hình, chia đều theo flow. Low delay: tránh queue dài dù throughput cao. Fast convergence: nhanh đạt fair allocation, đặc biệt vì nhiều flows ngắn kết thúc trước khi thuật toán hội tụ chậm.','Efficiency uses capacity well. Fairness shares bandwidth per flow in the model. Low delay avoids long queues even at high throughput. Fast convergence reaches allocation quickly, particularly because many short flows finish before slow convergence can help.'],
['End-to-end và network-assisted','End-to-end and network assistance','Loss/delay-based sender suy luận từ ACK/RTT mà không cần router báo rõ. Network-assisted dùng explicit feedback như ECN. ICMP Source Quench là ví dụ lịch sử trong học liệu, đã bị deprecated; không nên triển khai nó như cách hiện đại.','A loss/delay-based sender infers conditions from ACKs/RTT without explicit router reports. Network assistance provides signals such as ECN. The course’s ICMP Source Quench example is historical and deprecated, not a modern deployment mechanism.'],
['Tín hiệu không phải kết luận chắc chắn','Signals are not certainty','Queue buildup làm RTT tăng, nhưng path/processing cũng gây biến thiên. Packet loss có thể vì congestion, lỗi link, route hay TTL. TCP classic dùng loss vì reliability đã có cơ chế phát hiện nó. Triple duplicate ACK và timeout đều là loss indications; timeout thường khiến phản ứng mạnh hơn.','Queue buildup increases RTT, but path and processing changes also vary delay. Loss can arise from congestion, links, routing or TTL expiry. Classic TCP reused loss detection already needed for reliability. Both duplicate ACKs and timeout indicate loss; timeout generally causes a stronger reaction.']],
['Một link100Mbps nhận tổng120Mbps. Với buffer đủ lớn, queue vẫn tăng20Mb mỗi giây cho tới khi senders giảm tốc hoặc buffer tràn. Tăng buffer chỉ trì hoãn drop và có thể tăng delay.','A100Mbps link receives120Mbps. Its queue grows by20Mb each second until sending decreases or the buffer overflows. More buffering delays drops and can increase delay.'],
['Đừng gọi triple duplicate ACK là phép đo delay. Nó chủ yếu báo hole trong byte stream; RTT samples mới dùng cho delay inference.','Triple duplicate ACKs are not delay measurements. They primarily signal a byte-stream hole; RTT samples support delay inference.'],
['Thuật toán throughput cao nhưng queue rất dài có đạt đủ mục tiêu không?','Does high throughput with a very long queue meet all goals?'],['Không, nó vi phạm low delay và có thể gây hại cho interactive traffic.','No. It fails the low-delay goal and may harm interactive traffic.']);

u(2,'cwnd',['Cửa sổ nào đang giới hạn tốc độ?','Which window limits the sender?'],[14],
['cwnd là budget in-flight do sender giữ để bảo vệ network; rwnd là thông tin receiver quảng bá để bảo vệ buffer. Cả hai cùng giới hạn một connection.','cwnd is the sender’s in-flight budget for network protection; rwnd is the receiver-advertised buffer allowance. Both constrain a connection.'],[
['Công thức kết hợp','Combined constraint','W=min(cwnd,rwnd). Outstanding=LastByteSent−LastByteAcked≤W. Chỗ gửi mới=max(0,W−outstanding). Window là lượng byte, không phải byte/second. ACK quay về giải phóng budget, tạo ACK clock.','W=min(cwnd,rwnd). Outstanding=LastByteSent−LastByteAcked≤W. New sending allowance=max(0,W−outstanding). A window is bytes, not bytes/second. Returning ACKs release budget, creating an ACK clock.'],
['Từ window sang rate','From window to rate','Nếu luôn có data, RTT ổn định và không bị limit khác, throughput≈W/RTT. Đổi bytes sang bits bằng nhân8. Capacity vật lý, application-limited behavior, loss và overhead có thể làm rate thấp hơn.','With continuous data, stable RTT and no other limits, throughput≈W/RTT. Multiply by8 to convert bytes to bits. Physical capacity, application behavior, loss and overhead can reduce actual throughput.'],
['Probe-and-adapt','Probe and adapt','Sender không nhìn trực tiếp capacity của từng link. Nó tăng cwnd để thử mức cao hơn khi ACK thuận lợi, giảm khi có congestion signal. Đây là feedback loop động, không phải tốc độ cố định chọn một lần từ access link.','The sender cannot directly observe every link’s capacity. It increases cwnd when feedback is favorable and decreases it on congestion signals. This is a dynamic feedback loop, not a fixed rate chosen once from the access link.']],
['cwnd=12000bytes, rwnd=20000bytes, outstanding=9000bytes: gửi thêm3000bytes. Với RTT=0.1s, W/RTT≈120,000bytes/s=0.96Mbps trước overhead.','cwnd12000, rwnd20000 and outstanding9000bytes permit3000 more bytes. At RTT0.1s, W/RTT≈120,000bytes/s=0.96Mbps before overhead.'],
['Window nhỏ lại dưới outstanding không “rút” packet đã gửi; sender phải đợi ACK/giảm in-flight trước khi gửi thêm.','Shrinking a window below outstanding data does not recall packets; the sender waits for in-flight data to decrease.'],
['cwnd gấp đôi nhưng rwnd đang nhỏ hơn cả cwnd cũ, rate có gấp đôi không?','Does doubling cwnd double the rate if rwnd is below even the old cwnd?'],['Không theo window model, vì min(cwnd,rwnd) vẫn là rwnd.','Not in the window model: the minimum remains rwnd.']);

u(2,'reno',['Slow start, AIMD và TCP Reno','Slow start, AIMD and TCP Reno'],[15,16],
['Đọc graph bằng ba câu hỏi: đang slow start hay congestion avoidance; loss được phát hiện thế nào; ssthresh đổi ra sao?','Read the graph by asking which phase is active, how loss was detected and what happens to ssthresh.'],[
['Slow start','Slow start','Trong mô hình lớp, bắt đầu1MSS và tăng1MSS cho mỗi ACK mới: với mỗi segment được ACK, cwnd xấp xỉ double mỗi RTT:1,2,4,8… Đến ssthresh chuyển sang congestion avoidance. Tên “slow” so với việc gửi cả cửa sổ lớn ngay lập tức; tăng trưởng thực sự là exponential.','The course starts at1MSS and adds1MSS per new ACK, approximately doubling each RTT when every segment is acknowledged:1,2,4,8… At ssthresh it switches to congestion avoidance. “Slow” contrasts with immediately sending a large window; the growth itself is exponential.'],
['Additive increase','Additive increase','Congestion avoidance tăng xấp xỉ1MSS mỗi RTT, không phải mỗi ACK. Công thức theo ACK: increment=MSS²/cwnd (bytes). Ví dụ cwnd10000, MSS1000: mỗi ACK tăng khoảng100bytes; khoảng10 ACK tạo tổng gần1000bytes.','Congestion avoidance adds about1MSS per RTT, not per ACK. An ACK-based increment is MSS²/cwnd bytes. With cwnd10000 and MSS1000, each ACK adds about100bytes; roughly10 ACKs add about1000bytes.'],
['Hai loại loss event','Two loss events','Mô hình Reno sau triple duplicate ACK: đặt ssthresh≈flight/2 và sau fast recovery trở về khoảng nửa window, tiếp tục additive. Timeout: ssthresh giảm, cwnd về1MSS rồi slow start. Chi tiết fast recovery có inflation tạm thời nên graph bài học là giản lược, không trace đầy đủ implementation.','After triple duplicate ACKs, Reno sets ssthresh≈flight/2 and settles near half the window after fast recovery, resuming additive growth. Timeout lowers ssthresh and resets cwnd to1MSS for slow start. Temporary fast-recovery inflation makes the course graph a simplification of implementation details.']],
['ssthresh=8, initial1: RTT boundaries1,2,4,8,9,10… Loss triple-dup ở16 → về khoảng8; timeout ở16 →1 rồi2,4,8 và additive. Cùng lost packet nhưng recovery state khác.','With ssthresh8 and initial1, RTT boundaries are1,2,4,8,9,10… A triple-duplicate event at16 settles near8; a timeout at16 gives1,2,4,8 then additive growth. Similar loss can cause different recovery states.'],
['Không áp “mọi timeout giảm một nửa cwnd” cho Reno. Học liệu AIMD chung và Reno-specific response phải được tách rõ. Initial window1 là giả định bài tập.','Do not apply “every timeout halves cwnd” to Reno. Separate abstract AIMD from Reno-specific behavior. Initial window1 is an exercise assumption.'],
['Đường thẳng trên graph cwnd theo RTT biểu thị phase nào?','Which phase produces approximately linear cwnd growth by RTT?'],['Congestion avoidance/additive increase; slow start tạo tăng xấp xỉ exponential.','Congestion avoidance/additive increase. Slow start is approximately exponential.'],'reno');

u(2,'fairness',['Fairness: chia theo flow hay ứng dụng?','Fairness: per flow or per application?'],[17,18],
['Mô hình k TCP flows chia bottleneck R nhắm mỗi flow R/k. Điều này dựa trên giả định tương đồng và không bảo đảm mỗi người/app được phần bằng nhau.','The model targets R/k for k TCP flows sharing bottleneck R. This relies on similar conditions and does not guarantee equal shares per user/application.'],[
['Vì sao AIMD hướng tới cân bằng?','Why AIMD approaches fairness','Trong đồ thị rates(x,y), efficiency line x+y=R và fairness line x=y. Additive increase cộng cùng lượng vào hai flow; multiplicative decrease nhân cùng factor nên chênh lệch tuyệt đối co lại. Lặp đủ lâu với assumptions phù hợp đưa trạng thái gần giao hai đường.','On the rate plane, efficiency is x+y=R and fairness is x=y. Additive increase adds equally; multiplicative decrease scales both, shrinking the absolute difference. Repetition under suitable assumptions moves allocations toward the lines’ intersection.'],
['RTT bias','RTT bias','Reno tăng window theo ACK/RTT. Flow RTT nhỏ có nhiều vòng feedback trong một giây nên tăng nhanh hơn; kết luận equal share lý tưởng không giữ nguyên khi RTT khác. Capacity/traffic/dynamics cũng ảnh hưởng.','Reno’s growth follows ACKs/RTT. A shorter-RTT flow completes more feedback rounds per second and grows faster; the ideal equal-share conclusion does not hold unchanged for different RTTs. Capacity, traffic and dynamics also matter.'],
['Nhiều parallel connections','Multiple parallel connections','Nếu chín app mỗi app một flow và app mới mở11 flows, tổng20 flows. Với equal per-flow sharing, app mới có11R/20=55% capacity; mỗi app cũ5%. Fair theo connection vẫn có thể unfair theo user.','If nine apps have one flow each and a new app opens11, there are20 flows. Equal per-flow sharing gives the new app11R/20=55% and each old app5%. Per-connection fairness can still be per-user unfairness.']],
['R=100Mbps,5 flows giống nhau:20Mbps mỗi flow. Một app sở hữu3 trong5 flows có60Mbps. Không thể suy từ “fair TCP” rằng mỗi app có20Mbps.','At R100Mbps with five similar flows, each gets20Mbps. An app owning three gets60Mbps. “Fair TCP” does not imply20Mbps per app.'],
['UDP traffic không tự tuân theo TCP AIMD. Fairness còn phụ thuộc traffic mix và cách định nghĩa policy.','UDP traffic does not automatically follow TCP AIMD. Fairness depends on the traffic mix and policy definition.'],
['Tại sao fast convergence là một fairness goal?','Why is fast convergence a fairness goal?'],['Flow ngắn có thể kết thúc trước khi đạt fair rate nếu thuật toán điều chỉnh quá chậm.','Short flows may finish before reaching a fair rate if adaptation is slow.']);

u(2,'cubic',['CUBIC: tăng theo thời gian','CUBIC: time-based window growth'],[19],
['Trên high bandwidth-delay product path, tăng1MSS/RTT có thể phục hồi rất chậm. CUBIC dùng đường cong theo thời gian từ loss để khai thác capacity nhanh hơn.','On high-bandwidth-delay-product paths, gaining1MSS per RTT can recover very slowly. CUBIC uses elapsed time since loss to recover capacity faster.'],[
['Ba vùng tăng trưởng','Three growth regions','Sau loss, giảm window và nhớ Wmax. Tăng nhanh khi còn xa Wmax, chậm dần khi gần mức từng gây loss; nếu vượt Wmax mà không loss thì tăng nhanh dần để khám phá capacity mới. Đường cubic vừa có vùng concave vừa convex.','After loss, reduce the window and remember Wmax. Grow quickly while far below Wmax, cautiously near the previous loss point, then faster beyond it if no new loss appears. The cubic curve includes concave and convex regions.'],
['Công thức và biến','Formula and variables','W(t)=C(t−K)³+Wmax, t là thời gian từ congestion event, C là scale, K là thời điểm trở lại Wmax. Nếu β là fraction giữ lại, K=cuberoot(Wmax(1−β)/C). Tại t=K, W=Wmax và slope bằng0.','W(t)=C(t−K)³+Wmax, where t is elapsed time, C is a scale and K is the return time to Wmax. If β denotes the retained fraction, K=cuberoot(Wmax(1−β)/C). At t=K, W=Wmax and the slope is zero.'],
['Phân biệt mô hình bài và chuẩn','Course illustration versus standard','Canvas minh họa giảm nửa window để giải thích shape. RFC9438 dùng β=0.7 làm retained fraction và C=0.4. Ghi rõ convention: một paper có thể dùng β cho fraction bị giảm thay vì fraction giữ lại. Time-based growth giảm RTT bias, không biến fairness thành tuyệt đối.','Canvas illustrates a half-window reduction to explain the shape. RFC9438 uses retained fraction β=0.7 and C=0.4. State the convention: papers can use β for the removed rather than retained fraction. Time-based growth reduces RTT bias but does not guarantee perfect fairness.']],
['Ví dụ chuẩn hóa Wmax=100, β=0.7, C=0.4: K≈4.22s. W(0)=70; W(K)=100. Ngay gần K, tăng rất chậm; xa hơn K, tăng nhanh hơn.','For Wmax100, β0.7 and C0.4, K≈4.22s. W(0)=70 and W(K)=100. Growth is cautious near K and faster farther beyond K.'],
['Không thay công thức theo milliseconds nếu C đang được định nghĩa theo seconds; units và β convention phải nhất quán.','Do not substitute milliseconds when C assumes seconds; units and the β convention must be consistent.'],
['Vì sao CUBIC chậm lại gần Wmax?','Why does CUBIC slow near Wmax?'],['Đó là mức từng có loss, nên probe thận trọng trước khi giả định capacity đã tăng.','That was a previous loss level, so it probes cautiously before assuming more capacity exists.'],'cubic');

u(2,'throughput',['Tính TCP throughput và kiểm tra giả định','Compute TCP throughput and check assumptions'],[20],
['Mô hình sawtooth biến hình graph thành công thức. Điều quan trọng là biết W theo packets, MSS theo bytes và RTT theo seconds.','The sawtooth model turns a graph into a formula. Track W in packets, MSS in bytes and RTT in seconds.'],[
['Một chu kỳ sawtooth','One sawtooth cycle','Giả định congestion avoidance tăng1packet/RTT từW/2 đếnW rồi loss, giảm nửa; không timeout/slow-start trong chu kỳ. Average window=(W/2+W)/2=3W/4. Duration≈W/2 RTTs. Packets/cycle≈(3W/4)(W/2)=3W²/8.','Assume additive growth of1packet/RTT fromW/2 toW, followed by a halving loss, without timeout/slow start in the cycle. Average window is3W/4; duration≈W/2 RTTs; packets per cycle≈3W²/8.'],
['Liên hệ loss probability','Relating loss probability','Với một loss khoảng mỗi1/p packets:3W²/8≈1/p nên W≈sqrt(8/(3p)). Rate≈(3W/4)MSS/RTT≈sqrt(3/2)·MSS/(RTT·sqrt(p)). Hệ số phụ thuộc model, ACK behavior và giới hạn thực; scaling theo1/(RTT√p) là trọng tâm.','With roughly one loss per1/p packets,3W²/8≈1/p gives W≈sqrt(8/(3p)). Rate≈(3W/4)MSS/RTT≈sqrt(3/2)·MSS/(RTT·sqrt(p)). Constants depend on modeling, ACK behavior and real limits; the key scaling is1/(RTT√p).'],
['Khi không nên áp máy móc','When the model breaks down','Receiver window nhỏ, application thiếu data, link capacity thấp, nhiều timeouts hoặc TCP variant khác sẽ thay kết quả. p→0 không có nghĩa rate vô hạn: bottleneck/window/app vẫn giới hạn. Muốn fill path, lượng in-flight cần gần bandwidth×RTT.','Small receive windows, lack of application data, link capacity, frequent timeouts or different TCP variants change the result. p→0 does not imply infinite rate; bottlenecks, windows and apps still limit it. Filling the path requires roughly bandwidth×RTT in flight.']],
['Giữ MSS/RTT: p tăng từ0.001 lên0.004 (gấp4) → predicted rate giảm một nửa. RTT gấp đôi → rate lại giảm nửa. Kết hợp cả hai → còn một phần tư.','Holding MSS/RTT otherwise fixed, increasing p from0.001 to0.004 quadruples loss and halves predicted rate. Doubling RTT halves it again. Together they yield one quarter of the original rate.'],
['p là xác suất dạng thập phân:1%=0.01, không phải1. Throughput bytes/s phải nhân8 nếu đáp án bps.','p is a decimal probability:1%=0.01, not1. Multiply bytes/s by8 for bps.'],
['Muốn rate gấp đôi chỉ nhờ giảm loss, p cần thay ra sao?','To double predicted rate by reducing loss alone, how must p change?'],['Giảm p xuống một phần tư trong mô hình1/√p.','Reduce p to one quarter under the1/√p model.'],'throughput');

u(2,'datacenter',['Mở rộng: DCTCP và TIMELY','Extension: DCTCP and TIMELY'],[21],
['Datacenter có nhiều short flows nhạy delay và một operator kiểm soát endpoints/network. Điều này cho phép thiết kế congestion control phù hợp hơn môi trường Internet chung.','Datacenters combine delay-sensitive short flows with an operator controlling endpoints and network. This supports congestion-control designs tailored to that environment.'],[
['Workload và mục tiêu','Workload and objectives','Large transfers cần throughput, short RPCs cần latency thấp; queue dài hại tail latency. Chính sách chỉ tối đa bandwidth chưa đủ. Chủ sở hữu có thể phối hợp thay đổi hosts/switches dễ hơn nhiều AS độc lập.','Large transfers need throughput while short RPCs need low latency; long queues hurt tail latency. Maximizing bandwidth alone is insufficient. One owner can coordinate hosts/switches more readily than independent ASes can.'],
['DCTCP','DCTCP','Dùng ECN feedback từ network và phản ứng dựa mức độ congestion, thay vì chỉ một loss/no-loss event. Mục tiêu giữ queue nhỏ mà sử dụng capacity tốt. Explicit feedback không loại bỏ mọi cơ chế loss recovery.','DCTCP uses network ECN feedback to respond to the extent of congestion rather than only a binary loss event, aiming for shallow queues and good utilization. Explicit feedback does not remove the need for loss recovery.'],
['TIMELY','TIMELY','Dùng RTT measurements và gradient của RTT để điều chỉnh sending rate: RTT đang tăng nhanh gợi queue tích tụ. Đây là ý tưởng rate adjustment theo delay; không nên mô tả nó đơn giản là Reno với công thức cwnd khác.','TIMELY uses RTT measurements and their gradient to adjust sending rate: increasing RTT suggests queue buildup. It is a delay-based rate-adjustment design, not merely Reno with a different cwnd expression.']],
['Nếu hai scheme đều đạt95% link utilization nhưng scheme A tạo queue50ms còn B tạo1ms, B hợp short interactive requests hơn khi các yếu tố khác tương đương.','If both schemes achieve95% utilization but A adds50ms of queueing and B adds1ms, B better suits short interactive requests, other factors equal.'],
['Đây là phần optional. Phân biệt explicit ECN với inferred RTT, và hiểu vì sao môi trường DC tạo cơ hội triển khai.','This is optional material. Distinguish explicit ECN from inferred RTT and understand why datacenter ownership changes deployment feasibility.'],
['DCTCP và TIMELY lấy feedback đặc trưng nào?','What distinguishes their feedback?'],['DCTCP dùng ECN từ network; TIMELY dùng RTT và sự thay đổi RTT.','DCTCP uses network ECN; TIMELY uses RTT and changes in RTT.']);
