u(3,'routing',['Routing xây bảng; forwarding dùng bảng','Routing builds tables; forwarding uses them'],[0,2],
['Sau khi host gửi tới default router, mỗi router cần biết output link. Control plane phối hợp xây thông tin đó; data plane áp dụng cho từng packet.','After a host sends to its default router, each router needs an outgoing link. The control plane builds that information; the data plane applies it per packet.'],[
['Hai tác vụ, hai timescales','Two tasks and timescales','Forwarding nhận packet, tra destination trong FIB và chuyển input→output, nhanh và local. Routing trao đổi thông tin topology/reachability, tính good paths và cập nhật FIB khi network thay đổi. Router không chạy Dijkstra lại cho mỗi packet web.','Forwarding receives a packet, looks up its destination in the FIB and moves it from input to output quickly and locally. Routing exchanges topology/reachability information, computes paths and updates the FIB after changes. Dijkstra is not rerun for every web packet.'],
['Scope nội miền','Intradomain scope','Một administrative domain/AS có quyền chọn metric chung; IGP như OSPF/RIP tính đường trong đó. Interdomain liên quan nhiều AS độc lập và policy, học trong Lesson4. Cùng một end-to-end path dùng cả hai loại routing.','One administrative domain/AS can choose an internal metric; IGPs such as OSPF/RIP find paths within it. Interdomain routing involves independent AS policies, covered in Lesson4. An end-to-end path uses both kinds.'],
['Đồ thị chi phí','A cost graph','Nodes là routers, edges là links với cost do metric/admin quyết định. Cost path là tổng edge costs. “Shortest” là least-cost, không mặc định ít hop, ngắn địa lý hay ít delay. Link-state dùng topology map; DV dùng neighbor distance estimates.','Nodes represent routers and edges represent links with metric/admin-defined costs. Path cost is the sum of edge costs. Shortest means least-cost, not necessarily fewest hops, shortest geography or lowest delay. Link state uses a topology map; DV uses neighbors’ distance estimates.']],
['A→B cost1, B→C cost1, A→C cost10: least-cost A→C đi quaB với2 dù có nhiều hop hơn direct link. FIB củaA chỉ cần next hopB choC.','A–B costs1, B–C1 and A–C10. A’s least-cost path toC goes throughB for2 despite using more hops. A’s FIB needs next hopB forC.'],
['UDP không thiết lập TCP-style connection dù nguồn đôi khi dùng từ “connection” theo nghĩa liên lạc logic.','UDP does not establish a TCP-style connection even if course prose uses connection informally for communication.'],
['Thay đổi link cost ảnh hưởng control hay data plane trước?','Which plane first handles a changed link cost?'],['Control plane học thay đổi và tính/cài route; data plane dùng FIB mới sau đó.','The control plane learns/recomputes/installs; the data plane subsequently uses the new FIB.'],'planes');

u(3,'dijkstra',['Dijkstra: mỗi bước khẳng định một distance','Dijkstra: confirm one distance at a time'],[3,4,5],
['Link-state phát thông tin link để các router cùng area có map nhất quán sau hội tụ. Từ map đó, mỗi router chạy Dijkstra với chính nó làm source.','Link state disseminates links so area routers have a consistent map after convergence. Each router runs Dijkstra with itself as the source.'],[
['State cần giữ','State to track','D(v): best tentative cost từ source u đếnv. p(v): predecessor trên path đó. N′: tập nodes đã có shortest distance được khẳng định, không phải chỉ nodes trên một path duy nhất. Initialize N′={u}, direct neighbors bằng link cost, còn lại∞.','D(v) is the tentative best cost from sourceu; p(v) is its predecessor. N′ contains nodes whose shortest distances are finalized, not just the nodes on one path. Initialize N′={u}, neighbor distances to direct costs and others to∞.'],
['Chọn rồi relax','Select, then relax','Chọn w ngoài N′ có D nhỏ nhất, thêm vàoN′. Với neighborv chưa finalized, D(v)=min(D(v),D(w)+c(w,v)); nếu cải thiện, p(v)=w. Khi cost không âm, chọn minimum làm finalized distance an toàn. Tie có thể chọn theo rule cố định, shortest distances vẫn đúng.','Select the minimum-D unfinalized nodew, add it toN′, then relax each unfinalized neighborv with min(D(v),D(w)+c(w,v)); update p(v)=w when improved. Nonnegative costs justify finalization. Ties may follow a fixed rule while preserving shortest distances.'],
['Path và next hop','Path and next hop','Follow p từ destination ngược về source để reconstruct path, rồi lấy node đầu sau source làm next hop. Predecessor của destination thường không phải next hop của source. Mỗi router có tree riêng; không có một tree Dijkstra chung cho mọi source.','Follow predecessors backward from the destination to reconstruct a path, then take the first node after the source as next hop. A destination’s predecessor is often not the source’s next hop. Each source has its own shortest-path tree.'],
['Complexity','Complexity','Naive implementation scan khoảngn−1,n−2,…,1 nodes để chọn minimum: tổngn(n−1)/2, nênO(n²), cộng relaxations. Heap-based versions có bound khác; O(n²) trong module nói về scan implementation.','Naive minimum selection scans aboutn−1,n−2,…,1 nodes, totalingn(n−1)/2 and yieldingO(n²), with relaxations. Heap-based variants have different bounds; the course’sO(n²) refers to scanning.']],
['Topology trong slide: từu initialize v2,w5,x1,y∞,z∞. Chọnx: w=min(5,1+3)=4, y=1+1=2. Chọny trong tie: w=3,z=4. Final distances v2,x1,y2,w3,z4; tới z dùng next hopx, không phảiy.','Slide topology: fromu initialize v2,w5,x1,y∞,z∞. Selectingx gives w=min(5,1+3)=4 and y=2. Selectingy from the tie gives w3,z4. Final distances are v2,x1,y2,w3,z4. The next hop towardz isx, noty.'],
['Dijkstra tìm shortest-path tree, không phải minimum spanning tree tối thiểu tổng weight của toàn cây. STP Lesson1 còn là cơ chế khác.','Dijkstra’s shortest-path tree is not a minimum spanning tree minimizing total tree weight. Lesson1 STP is another distinct mechanism.'],
['D(w)=4,c(w,v)=2,D(v)=5. Relax đổi D(v) không?','With D(w)=4,c(w,v)=2,D(v)=5, does relaxation change D(v)?'],['Không: min(5,4+2)=5.','No: min(5,4+2)=5.'],'dijkstra');

u(3,'dv',['Distance vector và Bellman–Ford','Distance vector and Bellman–Ford'],[6,7],
['DV không hỏi toàn topology; nó hỏi từng neighbor “bạn đi tới đích tốn bao nhiêu?” rồi cộng chi phí để tới neighbor đó.','DV does not require the whole topology. It asks each neighbor its destination cost, then adds the cost of reaching that neighbor.'],[
['Công thức local','The local equation','Dₓ(y)=minᵥ{c(x,v)+Dᵥ(y)} trên neighborsv. c(x,v) là link local x biết; Dᵥ(y) là estimate neighbor quảng bá. Neighbor đạt minimum là next hop. Self-distance bằng0; destination chưa biết là∞.','Dₓ(y)=minᵥ{c(x,v)+Dᵥ(y)} over neighborsv. x knows its local c(x,v); Dᵥ(y) is the neighbor’s advertised estimate. The minimizing neighbor is the next hop. Self-distance is0; unknown destinations are∞.'],
['Iterative, asynchronous, distributed','Iterative, asynchronous, distributed','Iterative vì updates tiếp tục đến khi không đổi. Asynchronous vì không cần tất cả routers chạy cùng clock. Distributed vì routers chỉ exchange với neighbors và tự tính. Round-by-round table là cách minh họa, không yêu cầu protocol thực đồng bộ.','Updates iterate until stable; routers need not share a clock; neighbors exchange and compute locally. Round-based tables illustrate behavior but do not imply a synchronized protocol.'],
['Tính một ví dụ đầy đủ','A complete small example','Triangle x–y=2,y–z=1,x–z=7. Ban đầu vectors theo(x,y,z): x=(0,2,7),y=(2,0,1),z=(7,1,0). Sau trao đổi: x→z=min(7+0,2+1)=3; z→x=3; y giữ nguyên. Sau khi neighbor nhận thông tin mới mà không cải thiện nữa thì hội tụ.','For x–y2,y–z1,x–z7, initial vectors ordered(x,y,z) are x=(0,2,7),y=(2,0,1),z=(7,1,0). Exchanges give x→z=min(7+0,2+1)=3 and z→x3; y remains unchanged. Further exchanges with no improvement establish convergence.']],
['x giữ cả vector của mình và thông tin neighbors đã nhận. Nếu y quảng bá đếnz=1, x không ghi1 làm distance của mình; phải cộng link x–y=2 để được3.','x stores its own vector and received neighbor information. Ify advertises cost1 toz, x must add its link-to-y cost2 rather than adopt1 directly.'],
['Neighbor có thể gửi stale estimate. Công thức đúng với thông tin hiện có không có nghĩa path đang có thật sau failure.','A neighbor can advertise stale information. Correct local arithmetic does not prove the path still exists after failure.'],
['Link tớiA=3, A quảng bá cost7; link tớiB=6, B quảng bá2. Chọn ai?','NeighborA costs3 and advertises7; B costs6 and advertises2. Which next hop wins?'],['B: min(3+7,6+2)=8.','B: min(3+7,6+2)=8.'],'dv');

u(3,'count',['Count-to-infinity: tin cũ tạo vòng','Count-to-infinity: stale beliefs create loops'],[8],
['DV biết neighbor báo cost nhưng thường không biết toàn path bên trong cost đó. Nếu path neighbor phụ thuộc ngược vào mình, tin cũ có thể tạo mutual illusion sau failure.','DV knows a neighbor’s reported cost without generally knowing its full path. If that path depends back on the router, stale information can create mutual illusion after failure.'],[
['Good news nhanh','Good news travels quickly','Trong triangle x–y4,y–z1,x–z50, z tới x qua y với cost5. Nếu x–y giảm4→1, y báo1; z đổi thành2; y không cải thiện thêm. Thông tin tốt lan vài updates.','With x–y4,y–z1,x–z50, z reachesx throughy at cost5. If x–y falls to1, y advertises1, z changes to2 and y has no further improvement. Good news propagates in few updates.'],
['Bad news chậm','Bad news travels slowly','Nếu x–y tăng4→60, y còn thấy z quảng bá5 nên chọn1+5=6 thay direct60. Nhưng cost5 cũ của z dùng y! z nghe6 rồi chọn7 qua y; y nghe7 rồi chọn8… Data có thể bounce giữa y,z trong khi estimates tăng.','If x–y rises4→60, y still sees z’s old5 and chooses1+5=6 instead of direct60. But z’s old5 depended ony. z hears6 and chooses7 viay; y hears7 and chooses8, and so on. Data may loop while estimates increase.'],
['Khi nào thoát?','When does it stop?','Trong ví dụ có alternative x–z50, z cuối cùng dùng direct50; y đi qua z với51 tốt hơn60. Nếu không có alternative, tăng tới metric infinity của protocol. Số rounds phụ thuộc lịch updates/tie rule; quan trọng là feedback loop và slow convergence.','Here z eventually takes direct50, then y usesz for51 instead of60. Without an alternative, estimates can climb to protocol infinity. The number of rounds depends on scheduling/ties; the key is the feedback loop and slow convergence.']],
['Giá trị5 trong bước đầu không phải cost link y–z. Nó là estimate z→x trước sự cố. Phải viết rõ candidate y→x = local1 + stale5 =6 để thấy circular dependency.','The initial5 is not the y–z link cost. It is z’s pre-failure estimate tox. Writing candidate y→x as local1+stale5=6 exposes the circular dependency.'],
['IP TTL có thể chấm dứt vòng đời một data packet, nhưng không tự sửa routing tables đang sai.','IP TTL can stop an individual data packet’s loop, but cannot repair incorrect routing tables.'],
['Vì sao y không biết z đang dùng chính y để đến x?','Why does y fail to see that z reaches x through y?'],['DV cơ bản quảng bá distance, không quảng bá đầy đủ dependency/path để y nhận ra vòng đó.','Basic DV advertises distance without the full dependency/path needed to detect that loop.'],'count');

u(3,'poison',['Poison reverse: thông báo khác theo neighbor','Poison reverse: neighbor-specific advertisements'],[9],
['Nếu tôi tới x qua bạn, tôi báo cho bạn distance tới x là∞. Tôi vẫn giữ finite route thật để forward, chỉ poison advertisement ngược về next hop.','If I reachx through you, I advertise infinity tox back to you. I keep my real finite forwarding route and poison only the reverse advertisement.'],[
['Trước failure','Before failure','z tới x qua y với cost5. z quảng bá∞ cho y, để y không thể xem z là alternative tới x. Đến neighbor khác, z vẫn có thể quảng bá cost5. Poison phụ thuộc destination và neighbor, không phải xoá mọi route của z.','z reachesx throughy at5. Advertising∞ toy preventsy treatingz as an alternative. Other neighbors may still receive5. Poisoning depends on destination and neighbor, not wholesale removal ofz’s routes.'],
['Sau x–y tăng60','After x–y rises to60','y thấy z báo∞ nên chọn direct60 và báo z. z đổi sang direct50 tới x; vì không còn dùng y, z báo50 cho y. y chọn51 qua z và lần này y báo∞ ngược cho z.','y seesz’s∞ and chooses direct60, tellingz. z switches to direct50 and, no longer usingy, advertises50 toy. y selects51 throughz and now advertises∞ back toz.'],
['Giới hạn','Limitation','Nó chặn mutual dependency hai neighbor trong ví dụ, nhưng vòng ba node trở lên vẫn có thể hình thành vì poison không truyền toàn path. Phân biệt split horizon (không quảng bá lại) với poisoned reverse (quảng bá∞).','It prevents the two-neighbor mutual dependency in this example, but longer loops remain possible because it does not carry complete paths. Split horizon omits the reverse advertisement; poisoned reverse sends infinity.']],
['A dùng B tớiD cost9: trong bảngA là9,nextB; message A→B choD là∞. Hai số khác nhau không mâu thuẫn: một cái để forwarding, một cái để ngăn B tin sai.','A reachesD throughB at9: A’s table contains9,nextB, while its advertisement toB is∞. Different values serve different purposes: forwarding versus preventing a mistaken dependency.'],
['“Poison reverse loại bỏ mọi count-to-infinity” là sai. Biết rõ phạm vi hai-node mitigation.','“Poison reverse eliminates every count-to-infinity case” is false. Know the two-node scope.'],
['Khi đổi next hop từ B sang C, A poison cho ai?','When A switches its next hop from B to C, whom does it poison?'],['Poison về C cho destination đó; không còn phải poison về B chỉ vì trước đây đã dùng B.','Poison towardC for that destination; B need not remain poisoned just because it was the old next hop.'],'poison');

u(3,'rip',['RIP: DV thành routing protocol','RIP: DV as a routing protocol'],[10],
['RIP dùng distance-vector logic để quảng bá reachability đến subnets, với hop count làm metric và cơ chế timers để phát hiện neighbors biến mất.','RIP uses distance-vector logic to advertise subnet reachability, with hop count as its metric and timers for disappearing neighbors.'],[
['Bảng routing','Routing table','Một row gồm destination subnet, next router và metric hops. Nhận advertisement từ neighbor A, router cộng local hop rồi so với route hiện có. RIP response/advertisements được exchange định kỳ; RIPv2 hỗ trợ subnet masks/aggregation.','A row records destination subnet, next router and hop metric. On A’s advertisement, add the local hop and compare with the existing route. RIP responses/advertisements exchange periodically; RIPv2 supports subnet masks and aggregation.'],
['Transport và timeout','Transport and timeout','RIP messages dùng UDP port520, dù chức năng của nó là network routing. Học liệu dùng180s không nghe neighbor thì coi route qua neighbor không còn reachable. Default periodic response khoảng30s và metric16 là unreachable; usable path tối đa15 hops.','RIP messages use UDP port520 although their function is network routing. The course uses180s without hearing a neighbor to invalidate reachability. The usual periodic response is about30s; metric16 is unreachable, so usable routes have at most15 hops.'],
['Trade-offs','Trade-offs','Đơn giản và ít cần global map, nhưng hop count không phản ánh bandwidth/latency, diameter nhỏ do infinity16, và DV convergence có thể chậm. Timers định nghĩa khi phát hiện vấn đề; không đảm bảo ngay thời điểm link vật lý chết router đã biết.','It is simple and avoids a global map, but hop count ignores bandwidth/latency, infinity16 limits diameter and DV convergence can be slow. Timers define detection; a router need not know instantly when a physical path fails.']],
['D đang tới subnetz cost5 quaB. A quảng bá cost2 tới z; local D→A cost1 nên candidate3. D chuyển next hop sangA nếu route hợp lệ và tốt hơn.','D reaches subnetz at5 viaB. A advertises2; local D→A adds1, giving3. D selectsA if that route is valid and better.'],
['Protocol nằm trên UDP không làm mục tiêu của nó thành transport reliability. Phân biệt chức năng routing với cơ chế chở control messages.','Using UDP does not turn RIP’s purpose into transport reliability. Distinguish routing function from control-message carriage.'],
['Neighbor báo metric15; cộng một hop thì route usable không?','A neighbor advertises15; is the route usable after adding one hop?'],['Không với RIP:16 biểu thị unreachable.','No in RIP:16 denotes unreachable.']);

u(3,'ospf',['OSPF: flooding, LSDB và areas','OSPF: flooding, LSDB and areas'],[11],
['OSPF cung cấp cơ chế phân phối topology và tổ chức domain; Dijkstra là thuật toán local tính path từ topology đó. Hai tên không đồng nghĩa.','OSPF distributes topology and organizes the domain; Dijkstra locally computes paths from that topology. The two names are not synonymous.'],[
['LSAs tạo map','LSAs build the map','Routers phát LSAs về links/state, flood trong phạm vi thích hợp để LSDB nhất quán sau convergence. Link cost do operator đặt: có thể dựa capacity hoặc đều1. Mỗi router chạy SPF từ chính nó. OSPF hỗ trợ equal-cost multipath và authentication.','Routers flood LSAs about links/state within their appropriate scope to converge on consistent LSDBs. Operators configure costs, perhaps based on capacity or uniformly1. Each router runs SPF from itself. OSPF supports equal-cost multipath and authentication.'],
['Areas và backbone','Areas and the backbone','Area hạn chế topology detail phải giữ/flood. ABR nối area với backbone Area0 và trao đổi reachability/summary giữa areas. Inter-area path thông thường: source area→ABR→backbone→ABR→destination area. Không phải mọi router biết toàn bộ detailed topology của mọi area.','Areas limit detailed topology state/flooding. ABRs connect areas with backbone Area0 and exchange reachability/summaries. A normal inter-area path goes source area→ABR→backbone→ABR→destination area. Not every router has every area’s complete detailed topology.'],
['Updates và refresh','Updates and refresh','Topology change kích LSAs mới, không phải chờ periodic refresh. Học liệu nêu refresh mặc định30 phút. Sequence information phân biệt mới/cũ/duplicate, tránh xử lý vô hạn các copies flood. Area scale vẫn cần lưu state, CPU và convergence time.','Topology changes trigger new LSAs rather than waiting for periodic refresh. The course gives a default30-minute refresh. Sequence information distinguishes newer, older and duplicate advertisements. Area organization still entails state, CPU cost and convergence time.']],
['Router trongArea1 muốn đếnArea2: nó cần đủ reachability qua ABR/backbone, không cần detailed adjacency của mọi routerArea2. Hierarchy giảm thông tin phải giữ.','An Area1 router reachingArea2 needs reachability through the ABR/backbone, not detailed adjacency for every Area2 router. Hierarchy reduces required state.'],
['LS flooding là control traffic để dựng map. Data packets không được flood khắp AS như LSAs.','LS flooding distributes control information. Data packets are not flooded across the AS like LSAs.'],
['Link chết ngay sau refresh, OSPF có chờ30 phút không?','If a link fails just after refresh, must OSPF wait30 minutes?'],['Không: phát hiện change kích update; refresh là cơ chế định kỳ riêng.','No. Detected changes trigger updates; refresh is a separate periodic mechanism.'],'areas');

u(3,'ospf-processing',['Từ LSA đến FIB: vì sao có độ trễ hội tụ?','From LSA to FIB: why convergence takes time'],[12],
['Router có route processor xử lý control messages và interface cards/switching fabric chuyển data. Một LSA mới không ngay lập tức biến thành forwarding mới.','A route processor handles control messages while interface cards and switching fabric move data. A new LSA does not instantaneously become new forwarding behavior.'],[
['T1–T4: xử lý update','T1–T4: processing an update','Nhận LS Update chứa LSAs (T1). Với từng LSA, so sequence với LSDB: nếu mới, update database, schedule SPF và xác định interfaces cần flood (T2). Xử lý xong packet (T3), chuẩn bị/flood update ra neighbors (T4), có thể qua timer.','Receive an LS Update containing LSAs (T1). For each LSA, compare against the LSDB; if new, update the database, schedule SPF and select flooding interfaces (T2). Finish packet processing (T3), then prepare/flood updates (T4), possibly via timers.'],
['T5–T7: tính và cài','T5–T7: compute and install','SPF chạy (T5–T6), rồi result được cài FIB (T7). SPF tốn CPU nên thường được schedule/batch thay vì chạy lặp cho từng duplicate. Trong thời gian chuyển tiếp, routers có thể tạm dùng views/FIBs khác nhau.','SPF executes (T5–T6), then results are installed into the FIB (T7). CPU-intensive SPF can be scheduled/batched rather than repeated for each duplicate. During transition, routers may temporarily use different views/FIBs.'],
['Data packet đi đâu?','Where data packets go','Interface nhận packet → FIB lookup → switching fabric → output interface. Data forwarding không cần đợi một packet mới để mới chạy routing; nó dùng bảng đang có, có thể cũ trong convergence.','An incoming interface performs a FIB lookup, sends through the switching fabric and uses the output interface. Data forwarding uses the installed table, which can be temporarily stale during convergence.']],
['LSDB đã nhận link-cost mới ởt=10ms nhưng SPF được schedule tại20ms và cài FIB tại25ms. Data tại15ms có thể vẫn dùng route cũ. “Đã biết topology mới” khác “đã forward theo topology mới”.','The LSDB learns a change at10ms, SPF runs at20ms and the FIB is installed at25ms. Data at15ms may still use the old path. Learning topology and forwarding on it are distinct events.'],
['Convergence delay gồm detection, dissemination, scheduling, computation và installation; không chỉ độ phức tạp Dijkstra.','Convergence includes detection, dissemination, scheduling, computation and installation—not just Dijkstra complexity.'],
['LSA duplicate có cần SPF tính lại ngay không?','Does a duplicate LSA require immediate SPF recomputation?'],['Không nếu không thay topology state; kiểm tra sequence giúp bỏ xử lý dư.','Not if it changes no topology state; sequence checking prevents redundant work.'],'ospf');

u(3,'hot-potato',['Hot potato: chọn cửa ra gần nhất','Hot potato: choose the closest exit'],[13],
['Khi các external routes tương đương ở các tiêu chí BGP trước đó, router chọn egress có IGP cost thấp nhất. Đây là nơi thay đổi nội miền có thể đổi traffic liên miền.','When external routes tie on earlier BGP criteria, a router selects the egress with the lowest IGP cost. Internal changes can therefore alter interdomain traffic.'],[
['Điều kiện áp dụng','When it applies','Không chọn exit gần chỉ vì nó gần nếu route khác thắng LocalPref/AS_PATH trước. Hot potato là tie-break sau các policy/attribute relevant; đo gần bằng IGP cost chứ không khoảng cách địa lý.','Do not prefer a nearby exit over a route winning earlier LocalPref/AS_PATH criteria. Hot potato breaks a relevant tie using IGP cost rather than geographic distance.'],
['Mục tiêu local','A local objective','Đưa traffic ra khỏi AS sớm giảm tài nguyên vận chuyển nội bộ. Neighbor nhận traffic sớm hơn có thể phải chở xa hơn. Chọn local minimum không có nghĩa global latency/cost tối ưu.','Handing off early reduces internal transport resources. The receiving neighbor may carry traffic farther. A local minimum does not guarantee minimum global latency or cost.'],
['Tác động của thay cost','Impact of cost changes','Nếu IGP cost tới exit tăng vì link failure/weight change, router có thể chuyển exit dù BGP paths bên ngoài không đổi. Traffic matrix và tải các links khác có thể đổi theo; đây là lý do TE phải xét tương tác hai tầng routing.','A failure/weight change can raise an exit’s IGP cost and shift egress even if external BGP paths remain unchanged. Traffic matrices and link loads can shift, so traffic engineering must account for both routing layers.']],
['Dallas thấy SF cost9, NY cost10 với external routes ngang nhau →SF. Link change làm SF cost12 →NY. AS_PATH không cần thay để gây egress shift.','Dallas sees SF cost9 and NY10 with tied external routes, so choosesSF. A change raisesSF to12, shifting traffic toNY without changing AS_PATH.'],
['Không cộng IGP costs của tất cả AS để chạy một Dijkstra toàn Internet. BGP policies giữ quyền quyết định độc lập.','Do not sum every AS’s IGP costs into one Internet-wide Dijkstra. BGP policies preserve independent decisions.'],
['Exit xa hơn nhưng LocalPref cao hơn có thắng không?','Can a farther exit win with higher LocalPref?'],['Có. LocalPref được xét trước IGP cost trong thứ tự của module.','Yes. LocalPref precedes IGP cost in the module’s selection order.'],'hotpotato');

u(3,'te',['Mở rộng: measure → model → control','Extension: measure → model → control'],[14],
['Traffic engineering dùng mục tiêu vận hành để chọn IGP weights. Routing algorithm tính least-cost paths từ weights; nó không tự biết traffic matrix và mục tiêu cân tải.','Traffic engineering chooses IGP weights for operational objectives. Routing computes least-cost paths from those weights; it does not inherently know traffic demand and balancing goals.'],[
['Measure','Measure','Thu topology, link state/capacity, current weights và demands. Nguồn gồm SNMP polling/traps/MIBs, router configuration, IGP monitor, packet sampling, edge measurements kết hợp routes hoặc tomography từ aggregate link loads. Measurement có uncertainty.','Collect topology, link state/capacity, weights and demands via SNMP polling/traps/MIBs, configurations, IGP monitoring, packet samples, edge observations plus routes, or tomography from aggregate loads. Measurements contain uncertainty.'],
['Model','Model','Tính paths theo candidate weights; xét areas/summaries và ECMP. Kết hợp traffic demands với phần traffic trên mỗi path để dự báo load mỗi link. Tối ưu weight dựa model, không chỉ đếm hops.','Compute paths under candidate weights, including areas/summaries and ECMP. Combine demands with path fractions to predict each link’s load. Optimize weights based on the model rather than merely counting hops.'],
['Control','Control','Apply weights tới affected routers, LSAs lan, SPF/FIB cập nhật. Giai đoạn tạm không nhất quán có thể gây ảnh hưởng; đổi weights thường cân nhắc lúc thêm hardware, failure hoặc demand đổi đáng kể. Sau đó đo lại để đóng feedback loop.','Apply weights to affected routers, propagate LSAs and update SPF/FIBs. Transient inconsistencies create costs; changes are considered for new hardware, failures or substantial demand shifts. Measure again to close the feedback loop.']],
['Hai equal-cost paths mỗi path chở khoảng50% demand trong model. Demand100Mbps tạo50Mbps trên mỗi path; đổi weight để một path mất tư cách shortest có thể đẩy cả100Mbps lên path còn lại.','Two equal-cost paths each carry roughly50% in the model. A100Mbps demand sends50Mbps over each; changing a weight so one path is no longer shortest can shift all100Mbps to the other.'],
['ECMP splitting không bảo đảm từng packet hoặc từng flow được chia chính xác50/50 trong deployment; đó là approximation model.','ECMP does not guarantee exact50/50 splitting for every packet/flow in deployment; this is a modeling approximation.'],
['Vì sao model đúng topology nhưng thiếu traffic demand vẫn chưa đủ TE?','Why is topology without traffic demand insufficient for TE?'],['Vì path costs không cho biết bao nhiêu traffic sẽ đổ vào mỗi link; không dự báo được overload.','Path costs do not tell how much traffic uses each link, so overload cannot be predicted.']);
