u(1,'growth',['Vì sao Internet cần kiến trúc?','Why does the Internet need an architecture?'],[0,2,3],
['Hãy hình dung một cuộc gọi video từ điện thoại Wi-Fi đến laptop ở quốc gia khác. Hàng loạt thiết bị, công ty và công nghệ phải hợp tác dù không được thiết kế cùng lúc. Kiến trúc Internet tạo ra các quy tắc chung để sự hợp tác đó có thể mở rộng.','Imagine a video call from a Wi-Fi phone to a laptop in another country. Devices, companies and technologies built at different times must cooperate. Internet architecture supplies shared rules that let this cooperation scale.'],[
['Áp lực tăng trưởng','Growth pressure','Không chỉ số byte tăng: số người, IoT, ứng dụng và yêu cầu bảo mật cũng tăng. Video cần throughput; cuộc gọi cần delay thấp; tải file cần đúng dữ liệu. CDN đặt bản sao gần người dùng để giảm đường đi và tải backbone, nhưng phải giải quyết placement, caching và vận hành. AI vừa tạo thêm traffic/datacenter demand vừa hỗ trợ đo đạc và chẩn đoán mạng.','Growth includes users, IoT, applications and security demands, not just bytes. Video needs throughput; calls need low delay; files need correctness. CDNs place content near users to reduce distance and backbone load, at the cost of placement, caching and operational complexity. AI increases network demand and can also support measurement and diagnosis.'],
['Từ circuit đến packet','From circuits to packets','Circuit switching dành tài nguyên cho một cuộc liên lạc. Packet switching chia dữ liệu thành gói dùng chung links: phù hợp traffic máy tính có lúc bùng phát, lúc im lặng. Dùng chung hiệu quả hơn nhưng phát sinh queue, delay và loss; đây là nền của các cơ chế trong Lesson 2.','Circuit switching reserves resources for a communication. Packet switching divides data into packets sharing links, fitting bursty computer traffic. Sharing improves utilization but introduces queues, delay and loss—the motivation for Lesson 2.'],
['Các mốc và ý nghĩa','Milestones and their meaning','1962: Licklider hình dung mạng máy tính toàn cầu. 1965: Roberts/Merrill thử kết nối máy tính đường dài qua điện thoại. 1969: ARPANET có bốn host đầu. 1970: NCP giúp host giao tiếp; 1972: email cho thấy giá trị ứng dụng. Open architecture và TCP/IP nối các mạng độc lập; DNS phân tán ánh xạ tên khi bảng tên tập trung không còn đủ; Web là ứng dụng làm Internet dễ sử dụng hơn.','1962: Licklider envisioned global networked computing. 1965: Roberts and Merrill tested long-distance communication over a telephone line. 1969: ARPANET connected its first four hosts. NCP in 1970 enabled host communication; email in 1972 demonstrated application value. Open architecture and TCP/IP interconnected independent networks. DNS distributed name lookup as a central host table became impractical. The Web made Internet information easier to use.']],
['Nếu mọi cuộc gọi buộc mạng lõi phải chờ retransmission của từng frame mất, âm thanh có thể đến đúng nhưng quá muộn. Ngược lại, một file thiếu byte không sử dụng được. Cùng một mạng phải hỗ trợ cả hai nhu cầu.','If the core forced a call to wait for every lost frame to be retransmitted, speech might arrive intact but too late. A file missing bytes may be unusable. One network must accommodate both needs.'],
['Internet là hạ tầng mạng của các mạng; Web là một ứng dụng trên đó. Đừng học các con số tăng trưởng lịch sử như số liệu hiện tại.','The Internet is the network infrastructure; the Web is an application on it. Historical growth statistics are not current measurements.'],
['Vì sao thêm bandwidth chưa đủ giải quyết mọi vấn đề?','Why does more bandwidth not solve every problem?'],['Vẫn còn latency, loss, heterogeneity, security, quản lý và phối hợp giữa tổ chức. Kiến trúc giải quyết cách các thành phần hợp tác, không chỉ tốc độ một link.','Latency, loss, heterogeneity, security, management and interorganizational coordination remain. Architecture governs cooperation, not just one link’s speed.'],'history');

u(1,'layers',['Phân lớp: dịch vụ, giao thức, giao diện','Layering: service, protocol and interface'],[4,5],
['Đừng bắt đầu bằng thuộc tên layer. Hãy hỏi: thành phần này hứa cung cấp gì, dùng dịch vụ nào bên dưới, và trao đổi quy tắc gì với peer bên kia?','Start with responsibilities rather than layer names: what does this component promise, what service does it use below, and what rules does it exchange with its peer?'],[
['Service khác protocol','Service versus protocol','Service là điều layer cung cấp cho layer trên, ví dụ reliable byte stream. Protocol là quy tắc và định dạng trao đổi giữa các thực thể cùng layer để thực hiện lời hứa đó, ví dụ TCP sequence/ACK. Interface là cách truy cập dịch vụ; socket là giao diện application–transport.','A service is what a layer offers above, such as a reliable byte stream. A protocol is the rules and message format peers use to implement it, such as TCP sequence numbers and ACKs. An interface is how the service is accessed; sockets connect applications to transport.'],
['Lợi ích và giá phải trả','Benefits and costs','Modularity cho phép thay implementation nếu interface vẫn giữ lời hứa. Interoperability giúp thiết bị nhiều hãng tương tác. Chia trách nhiệm giúp mở rộng và debug. Đổi lại có header/processing overhead, chức năng lặp lại như recovery ở link và TCP, và đôi khi phải dùng thông tin xuyên layer.','Modularity permits implementation changes behind stable interfaces. Interoperability lets different vendors communicate. Separation helps scaling and diagnosis. Costs include header/processing overhead, duplicated functions such as link and TCP recovery, and occasional cross-layer dependencies.'],
['OSI 7 ↔ Internet 5','Seven OSI layers ↔ five Internet layers','OSI: Application, Presentation, Session, Transport, Network, Data Link, Physical. Mô hình Internet năm lớp gộp ba lớp trên thành Application; chức năng biểu diễn dữ liệu và quản lý session vẫn tồn tại trong ứng dụng/thư viện. Đây là mô hình trách nhiệm, không có nghĩa mọi thiết bị hiện thực đúng bảy module.','OSI lists Application, Presentation, Session, Transport, Network, Data Link and Physical. The five-layer Internet model groups the top three into Application; data representation and session management still exist in applications and libraries. This is a responsibility model, not a requirement for seven software modules.']],
['Browser dùng socket để gửi HTTP qua TCP. Đổi đường truy cập từ Ethernet sang Wi-Fi thường không đổi logic HTTP vì dịch vụ ở giữa vẫn tương thích. Nhưng RTT/loss có thể đổi nên hiệu năng vẫn đổi.','A browser sends HTTP through a TCP socket. Switching access from Ethernet to Wi-Fi usually preserves HTTP logic because intermediate services remain compatible. RTT and loss may still change, so performance need not stay identical.'],
['Peer communication là quan hệ logic; byte vẫn phải đi xuống stack, qua medium và lên stack bên nhận.','Peer communication is logical; bytes still travel down a stack, through a medium and up the receiver’s stack.'],
['Link-layer recovery và TCP recovery cùng tồn tại có mâu thuẫn không?','Is it contradictory to have both link recovery and TCP recovery?'],['Không: một cơ chế bảo vệ một link, cơ chế kia bảo vệ toàn đường end-to-end. Có trùng chức năng nhưng phạm vi khác.','No. One protects a local link, the other the complete end-to-end path. Their functions overlap but their scopes differ.'],'stack');

u(1,'upper',['Ứng dụng, biểu diễn và phiên','Application, presentation and session'],[6],
['Một ứng dụng mạng cần thống nhất cả ý nghĩa message lẫn cách biểu diễn byte và vòng đời tương tác. OSI đặt tên riêng cho ba nhóm trách nhiệm này.','A network application must agree on message meaning, byte representation and interaction lifetime. OSI names these three responsibilities separately.'],[
['Application: ý nghĩa thao tác','Application: operation semantics','HTTP mô tả web requests/responses; SMTP gửi email; FTP truyền file; DNS ánh xạ tên sang địa chỉ. Đơn vị thông tin ở đây là message. Application protocol quyết định câu yêu cầu/đáp ứng có nghĩa gì, không quyết định router tiếp theo.','HTTP describes web requests/responses; SMTP sends email; FTP transfers files; DNS maps names to addresses. The information unit is a message. An application protocol defines operation semantics, not the next router.'],
['Presentation: thống nhất biểu diễn','Presentation: common representation','Hai máy phải hiểu cùng byte sequence: encoding văn bản, format dữ liệu, compression, byte order big-endian/little-endian. Nếu không thống nhất, network có thể giao đủ mọi byte mà ứng dụng vẫn diễn giải sai.','Hosts must interpret the same bytes consistently: text encoding, data formats, compression and big/little endian byte order. The network may deliver every byte correctly while applications still interpret the data differently.'],
['Session: tổ chức tương tác','Session: organizing an interaction','Trong teleconference, audio và video thuộc cùng một cuộc gọi, có trạng thái bắt đầu/kết thúc. Quản lý nhóm luồng và phiên thuộc trách nhiệm này. Trong Internet, app/protocol/library thường tự thực hiện; application session không nhất thiết tương ứng một TCP connection.','A teleconference’s audio and video belong to a call with a start, end and shared state. Session functions organize that interaction. Internet applications, protocols or libraries implement them; one application session need not equal one TCP connection.']],
['Gửi số 258: một máy dùng byte 01 02, máy kia đọc little-endian có thể hiểu 513. TCP không sửa semantic mismatch này: hai app phải thống nhất representation.','Sending 258 as bytes 01 02 can produce 513 when interpreted in little-endian order. TCP cannot fix that semantic mismatch; the applications must agree on representation.'],
['Có TCP connection không có nghĩa đã có đúng user session hay đúng format. Transport chỉ cung cấp dịch vụ theo phạm vi của nó.','A TCP connection does not establish a valid user session or data format. Transport only provides its own service.'],
['Audio và video của một cuộc gọi thuộc nhóm chức năng OSI nào?','Which OSI responsibility associates audio and video with a single call?'],['Session quản lý sự liên kết đó; presentation xử lý biểu diễn/encoding của dữ liệu.','Session manages the association; presentation handles data representation and encoding.']);

u(1,'lower',['Transport → IP → link → bits','Transport → IP → link → bits'],[7,8],
['Cùng một dữ liệu đi qua nhiều phạm vi giao hàng. Ports chọn process, IP định vị qua nhiều mạng, còn link đưa frame đến node tiếp theo trên medium hiện tại.','The same data crosses several delivery scopes. Ports identify processes, IP supports internetwork delivery, and a link carries frames to the next node on the current medium.'],[
['Transport và network','Transport and network','TCP/UDP phục vụ process-to-process ở endpoints. TCP thêm reliability, ordered delivery, flow/congestion control; UDP tối giản. IP cung cấp datagram best-effort giữa hosts: có thể mất, lặp, đến sai thứ tự. Routing protocols xây thông tin để router chọn next hop.','TCP/UDP serve processes at endpoints. TCP adds reliability, ordering and flow/congestion control; UDP is minimal. IP offers best-effort host-to-host datagrams that may be lost, duplicated or reordered. Routing protocols build information routers use to choose next hops.'],
['Data link và physical','Data link and physical','Ethernet, Wi-Fi, PPP giao frame theo từng link. Một link có thể hỗ trợ retransmission cục bộ nhưng không bảo đảm cả đường. Physical biểu diễn bits bằng tín hiệu trên đồng, quang hoặc radio; Ethernet có thể chạy trên các medium khác nhau.','Ethernet, Wi-Fi and PPP deliver frames over individual links. Local retransmission may protect one link without guaranteeing an entire path. The physical layer encodes bits as signals over copper, fiber or radio; Ethernet can use different media.'],
['Tên đơn vị dữ liệu','Data-unit vocabulary','Application: message. Transport: TCP segment; UDP datagram (bài học dùng “segment” theo nghĩa chung). Network: IP datagram/packet. Link: frame. Physical: bits. “Payload” luôn tương đối: TCP segment là payload của IP packet.','Application: message. Transport: TCP segment or UDP datagram (the course also uses segment generically). Network: IP datagram/packet. Link: frame. Physical: bits. Payload is relative: a TCP segment is an IP packet’s payload.']],
['Wi-Fi truyền thành công đến home router, nhưng router ISP sau đó làm rơi IP packet vì queue đầy. Local link success không đồng nghĩa server đã nhận; TCP vẫn cần ACK từ endpoint.','Wi-Fi delivers successfully to the home router, but an ISP router later drops the IP packet because its queue is full. Local success does not mean server delivery; TCP still needs endpoint feedback.'],
['Không phải mọi link đều dùng MAC kiểu Ethernet. Khi vẽ MAC qua từng hop, ví dụ đang giả định các link Ethernet.','Not every link uses Ethernet-style MAC addresses. A per-hop MAC example assumes Ethernet links.'],
['Router chọn đường bằng port hay IP?','Does ordinary IP forwarding choose a path by port or IP?'],['Router thông thường tra destination IP/prefix. Port phục vụ transport demultiplexing; middlebox/policy có thể xét thêm trường khác.','Ordinary forwarding looks up the destination IP/prefix. Ports support transport demultiplexing; middleboxes or policies may inspect additional fields.']);

u(1,'encapsulation',['Theo chân một HTTP request','Follow an HTTP request'],[9],
['Mỗi layer bọc dữ liệu bên trên trong header riêng. Đi qua router, gói được tháo frame của link cũ rồi đóng vào frame của link mới.','Each layer wraps upper-layer data in its own header. At a router, the incoming link frame is removed and the IP packet is put in a new outgoing frame.'],[
['Ở sender','At the sender','HTTP tạo message M. TCP thêm HT: [HT|M]. IP thêm HN: [HN|HT|M]. Link thêm HL và có thể trailer: [HL|HN|HT|M|trailer]. Physical truyền bit encoding. Header không thay thế message; nó bổ sung control information.','HTTP creates M. TCP adds HT: [HT|M]. IP adds HN: [HN|HT|M]. The link adds HL and possibly a trailer: [HL|HN|HT|M|trailer]. The physical layer transmits an encoding of the bits. Headers add control information rather than replacing the message.'],
['Ở switch và router','At a switch and router','L2 switch dùng destination MAC để chọn port. Router xử lý IP, giảm TTL/hop limit và chọn next hop, rồi tạo frame phù hợp outgoing link. Source/destination IP thường giữ nguyên nếu không NAT; không phải toàn bộ IP header bất biến.','An L2 switch uses the destination MAC to choose an output. A router processes IP, decreases TTL/hop limit, selects the next hop and creates an outgoing frame. Source/destination IP addresses usually stay unchanged without NAT, but the entire IP header is not immutable.'],
['Ở receiver','At the receiver','Receiver gỡ link header, xử lý IP, chuyển payload tới TCP/UDP đúng protocol, demultiplex tới socket rồi giao application data. Router có thể chạy ứng dụng quản lý/routing của chính nó, dù ordinary transit forwarding chỉ cần L1–L3.','The receiver removes the link wrapper, processes IP, dispatches to TCP/UDP, demultiplexes to a socket and delivers application data. Routers can run their own management/routing applications even though ordinary transit forwarding only needs L1–L3.']],
['A gửi đến server S qua R1 và R2 trên ba Ethernet links. IP destination luôn S; frame destination lần lượt là MAC của R1, R2 và S. A không đặt MAC của S từ đầu vì S không ở local link.','A sends to server S through R1 and R2 over three Ethernet links. The destination IP remains S; frame destinations are the MAC addresses of R1, R2 and S respectively. A does not initially use S’s MAC because S is not on the local link.'],
['Chú ý “đổi frame từng routed hop”, không phải đổi địa chỉ MAC mỗi khi qua L2 switch.','Frame addressing changes across routed hops, not merely on every L2 switch traversal.'],
['Tại sao IP packet có destination là server nhưng frame lại gửi đến router?','Why is an IP packet addressed to a server inside a frame addressed to a router?'],['Server là đích end-to-end; router là node tiếp theo có thể giao trực tiếp trên local link. Hai địa chỉ trả lời hai câu hỏi khác nhau.','The server is the end-to-end destination; the router is the directly reachable next node. The addresses answer different questions.'],'packet');

u(1,'end-to-end',['End-to-end: đặt chức năng ở đâu?','End-to-end: where should functions live?'],[10],
['Chức năng chỉ có thể hoàn chỉnh nhờ hiểu biết của endpoints cần được kiểm tra/thực hiện ở endpoints. Lõi mạng đơn giản, tổng quát giúp nhiều loại ứng dụng cùng tồn tại.','A function whose complete correctness requires endpoint knowledge belongs at the endpoints. A simple, general core accommodates different application requirements.'],[
['Lập luận về correctness','The correctness argument','Giả sử từng link đều kiểm tra lỗi: file vẫn có thể hỏng trong buffer, phần mềm hoặc lưu trữ. Để biết file đích đúng file nguồn, ứng dụng có thể kiểm tra checksum/hash end-to-end. Link recovery giúp performance nhưng không thay được phép kiểm tra toàn đường.','Even if every link checks errors, a file may be corrupted in buffering, software or storage. The application can verify source and destination data with an end-to-end checksum/hash. Local recovery improves performance but cannot replace complete endpoint verification.'],
['Khác nhu cầu ứng dụng','Different application needs','File transfer muốn đủ byte và đúng thứ tự; video call có thể bỏ audio quá trễ để giữ tính thời gian thực. Ép một service phức tạp duy nhất vào lõi sẽ buộc mọi app chịu cùng trade-off.','File transfer values complete, ordered bytes. A live call may discard late audio to maintain real-time interaction. A complex universal core service would impose one trade-off on all applications.'],
['Khả năng tiến hóa','Evolution at the edges','App developer có thể triển khai dịch vụ mới bằng thay endpoints thay vì nâng cấp từng router của nhiều tổ chức. Core tập trung giao packet, trong khi security/session/reliability theo yêu cầu đặt gần người tạo và tiêu thụ dữ liệu.','Developers can deploy new services by changing endpoints instead of upgrading every organization’s routers. The core transports packets while application-specific security, sessions and reliability remain near producers and consumers.']],
['Một cửa hàng nhận file đơn hàng qua TCP: TCP ACK không chứng minh đơn hàng đã ghi thành công vào database. App cần response xác nhận transaction; đây là correctness ở cấp cao hơn byte delivery.','A shop receives an order over TCP. A TCP ACK does not prove the order was committed to a database. An application response confirms the transaction—a higher correctness level than byte delivery.'],
['End-to-end là lập luận thiết kế, không cấm network hỗ trợ. Cần phân biệt “hỗ trợ hiệu năng” với “đủ để bảo đảm correctness”.','End-to-end is a design argument, not a ban on network assistance. Distinguish performance support from sufficient correctness guarantees.'],
['Link reliability làm TCP reliability thừa không?','Does link reliability make TCP reliability redundant?'],['Không. Link có phạm vi một hop và không bao quát mọi nguyên nhân lỗi end-to-end.','No. A link covers one hop and cannot cover every end-to-end failure cause.']);

u(1,'nat',['NAT và firewall: lợi ích đổi lấy state','NAT and firewalls: benefits at the cost of state'],[11],
['NAT cho nhiều thiết bị private chia sẻ public IPv4. Nó làm được điều này bằng sửa địa chỉ/port và nhớ bản dịch, nên kết nối phụ thuộc vào một middlebox.','NAT lets private devices share a public IPv4 address by rewriting addresses/ports and retaining mappings. Communication consequently depends on middlebox state.'],[
['Outbound và inbound','Outbound and inbound translation','Host 10.0.0.4:3345 gửi đến server. NAT chọn public 203.0.113.9:5001, thay source tuple và lưu mapping. Reply gửi tới public tuple đó; NAT tra bảng và thay destination về 10.0.0.4:3345. Hai host có cùng private source port vẫn có thể phân biệt bằng public mappings khác nhau.','Host 10.0.0.4:3345 sends to a server. NAT chooses public 203.0.113.9:5001, rewrites the source tuple and saves the mapping. Replies to that public tuple are translated back to the private destination. Hosts using identical private source ports can have different public mappings.'],
['Vì sao ảnh hưởng end-to-end?','Why end-to-end is affected','Private addresses được dùng lại ở nhiều LAN và không được route trực tiếp trên Internet. Outside host thường không thể tự mở kết nối tới host private nếu chưa có mapping/config phù hợp. NAT restart làm mất state có thể làm hỏng kết nối đang hoạt động.','Private addresses are reused across LANs and are not directly routed on the public Internet. Outside hosts usually cannot initiate connections without suitable mappings/configuration. Lost NAT state can interrupt established communication.'],
['Firewall và workarounds','Firewalls and workarounds','Firewall quyết định allow/drop theo policy, không chỉ forward. STUN giúp app biết public tuple NAT cấp; UDP hole punching tạo state để hỗ trợ peer-to-peer khi NAT behavior cho phép. Đây là thêm phối hợp ở endpoints; không bảo đảm xuyên mọi NAT/firewall.','A firewall allows or drops traffic according to policy. STUN helps discover a NAT-assigned public tuple. UDP hole punching establishes state for peer-to-peer traffic when NAT behavior allows it. These require extra endpoint coordination and do not bypass every NAT/firewall.']],
['Laptop A và B cùng gửi từ port 4000: NAT có thể dùng public :5001 cho A và :5002 cho B. Reply :5002 phải đến B. Nếu không lưu mapping, public IP đơn lẻ không đủ xác định máy nhận.','Laptops A and B both use source port 4000. NAT can allocate public :5001 for A and :5002 for B. A reply to :5002 must reach B. The shared public IP alone is insufficient without the mapping.'],
['NAT và firewall thường cùng một box nhưng là hai chức năng khác nhau. Address translation không tự nó là một chính sách bảo mật đầy đủ.','NAT and firewall functions often share a box but are distinct. Address translation alone is not a complete security policy.'],
['Mapping bị mất có thể ảnh hưởng connection dù link còn hoạt động không?','Can losing a mapping break communication while all links still work?'],['Có. Đường vật lý còn nhưng NAT không còn biết chuyển public reply về private endpoint nào.','Yes. Physical connectivity survives, but the NAT may no longer know the private destination of returning traffic.'],'nat');

u(1,'hourglass',['Hourglass và EvoArch','The hourglass and EvoArch'],[12,13],
['Nhiều công nghệ ở đáy, nhiều ứng dụng ở đỉnh, rất ít giao thức ở giữa. IP là điểm chung quan trọng; bài học cũng nhấn mạnh TCP/UDP như vùng waist ổn định.','Many technologies sit below and many applications above a small protocol waist. IP is the crucial common layer; the lesson also emphasizes the stable TCP/UDP region.'],[
['Interoperability → dependency','Interoperability → dependency','Mọi link có thể chở IP và mọi app có thể xây trên transport chung. Đổi mới ở hai đầu dễ hơn thay protocol ở giữa vì nhiều hệ điều hành, app, middlebox và operators đều phụ thuộc. Đó là ossification: khó thay dù giải pháp mới tốt hơn một tiêu chí kỹ thuật.','Links can carry IP and applications can use shared transports. Edge changes are easier than replacing middle protocols depended on by operating systems, apps, middleboxes and operators. This is ossification: replacement is difficult even if an alternative is technically superior in some respect.'],
['EvoArch: đồ thị dependency','EvoArch: a dependency graph','Node là protocol trong layered DAG. Substrates nằm dưới và cung cấp dịch vụ; products nằm trên và phụ thuộc vào node. Layer generality mô tả khả năng được chọn làm substrate: thấp thường tổng quát, cao thường chuyên biệt. Evolutionary value tăng khi các products giá trị phụ thuộc vào nó.','Nodes are protocols in a layered directed acyclic graph. Substrates provide lower-layer services; products are higher-layer dependents. Layer generality affects substrate selection: lower services are often general, upper services specialized. Evolutionary value comes from valuable products depending on a protocol.'],
['Một vòng tiến hóa','One evolutionary round','Sinh protocol → chọn dependencies → tính lại value → cạnh tranh cùng layer khi products trùng đủ nhiều → loại protocol yếu với xác suất cao hơn. Nếu product mất substrate duy nhất, có thể chết dây chuyền. Qua nhiều vòng, middle protocols giá trị cao tồn tại thành waist. Đây là mô hình giải thích, không phải packet protocol chạy trên router.','Introduce protocols, choose dependencies, recompute value, compete within layers where products overlap, and preferentially remove weaker competitors. Dependents losing their only substrate may also die. Repeated rounds can create a high-value middle waist. This is an explanatory model, not a packet protocol executed by routers.'],
['Bài học triển khai','Deployment lessons','TCP/IP được ứng dụng hữu ích như email/FTP/Telnet hỗ trợ adoption. TCP/UDP ổn định còn tạo evolutionary shield cho IPv4. Thiết kế clean-slate vẫn có thể lại thành hourglass; coexistence, transition và waist có các dịch vụ tổng quát ít overlap đáng cân nhắc.','Useful apps such as email/FTP/Telnet helped TCP/IP adoption. Stable TCP/UDP also shielded IPv4 evolutionarily. A clean-slate design could form another hourglass; coexistence, transitions and general waist services with less overlap deserve attention.']],
['Protocol P nhanh hơn TCP 10% nhưng chưa có ứng dụng dùng. Protocol Q cũ hơn, được nhiều app quan trọng dùng. Trong EvoArch, Q có thể có value lớn hơn P: value đo dependency/adoption, không trực tiếp đo throughput.','Protocol P is 10% faster than TCP but has no applications. Older Q supports many important apps. Q can have greater EvoArch value because the model measures dependency/adoption, not throughput directly.'],
['Products ở trên; substrates ở dưới. Protocol cùng layer không tự động là competitor: cần overlap về products theo mô hình.','Products are above; substrates are below. Same-layer protocols are not automatically competitors; product overlap matters in the model.'],
['Vì sao một protocol tốt hơn vẫn khó thay IP?','Why can a better protocol still fail to replace IP?'],['Nó cần ecosystem adoption và đường transition, không chỉ lợi ích kỹ thuật. Nhiều dependents làm việc thay đổi core tốn phối hợp.','It needs ecosystem adoption and a transition path, not just technical advantages. Numerous dependents create coordination costs.'],'hourglass');

u(1,'redesign',['Mở rộng: clean-slate, 4D, AIP','Extension: clean-slate, 4D and AIP'],[14],
['Trang tùy chọn này hỏi: nếu thiết kế lại với security, manageability và accountability từ đầu, kiến trúc sẽ khác gì?','This optional page asks how architecture changes when security, manageability and accountability become initial design goals.'],[
['Clean-slate như quá trình thử nghiệm','Clean-slate as experimentation','Không chỉ đề xuất replacement cuối cùng: cần testbed lớn, nhiều technology, real traffic, opt-in users và kiến trúc cùng tồn tại. Thử nghiệm có thể tạo nâng cấp tương thích, kiến trúc mới, hoặc cho thấy phần thiết kế hiện tại vẫn hợp lý.','It is more than proposing a replacement. Large testbeds need diverse technology, real traffic, opt-in users and coexistence. Experiments may yield incremental upgrades, new architectures or evidence that existing choices remain practical.'],
['4D: bốn plane','4D: four planes','Data forwards packets. Discovery tìm topology/state. Dissemination phân phối thông tin và chỉ dẫn. Decision tính quyết định từ network-wide view và điều khiển forwarding. Khác biệt là mục tiêu toàn mạng và direct control; hướng này góp phần thúc đẩy SDN.','Data forwards packets. Discovery learns topology/state. Dissemination distributes information/instructions. Decision uses a network-wide view to control forwarding. The emphasis on network objectives and direct control helped motivate SDN.'],
['AIP: ai chịu trách nhiệm?','AIP: who is accountable?','Địa chỉ AD:EID phân biệt administrative domain và end host với self-certifying identity. Source accountability nhắm chống spoofing/truy nguồn, có cơ chế shut-off unwanted traffic. Control-plane accountability xét origin và path authentication. Đây là proposal được học, không phải tính chất sẵn có của IP thông thường.','AD:EID identifies the administrative domain and end host using self-certifying identities. Source accountability targets spoofing and attribution, including shut-off mechanisms. Control-plane accountability examines origin and path authentication. These are proposal features, not properties of ordinary IP.']],
['Một advertisement nói “prefix P thuộc tôi”: origin authentication kiểm tra quyền originate. Một path bị sửa: path authentication kiểm tra đường được quảng bá. Hai kiểm tra không giống nhau.','An advertisement says “I originate P”: origin authentication checks that authority. A modified advertised path concerns path authentication. These are different checks.'],
['Nhãn “optional” giữ đúng vị trí trong tài liệu; nắm ý tưởng nếu muốn đào sâu, không thay thời gian luyện nội dung core.','The optional label preserves its source role: use it for depth without displacing core practice.'],
['Trong 4D, plane nào tính quyết định và plane nào forward?','Which 4D plane decides and which forwards?'],['Decision tính từ network-wide view; Data thực thi forwarding.','Decision computes using a network-wide view; Data performs forwarding.']);

u(1,'bridges',['Thiết bị mạng và learning bridge','Network devices and learning bridges'],[15,16],
['Switch không được phát sẵn danh sách vị trí mọi máy. Nó học qua traffic: nhìn source để học, nhìn destination để chuyển tiếp.','A switch does not start with every host location. It learns from traffic: the source teaches location, the destination selects forwarding.'],[
['Hub, switch, router','Hub, switch, router','Hub/repeater L1 lặp signals, không hiểu địa chỉ; hosts dùng chung collision domain. Bridge/L2 switch xử lý MAC/frame và tách việc forward theo port. Router/L3 switch xử lý IP để nối networks. Tất cả có giới hạn capacity; output queue đầy vẫn có thể drop.','L1 hubs/repeaters repeat signals without address awareness; attached hosts share a collision domain. Bridges/L2 switches use MAC addresses and frame forwarding by port. Routers/L3 switches use IP between networks. Finite output capacity and buffers can still cause drops.'],
['Thuật toán mỗi frame','Per-frame algorithm','1. Ghi source MAC → ingress port. 2. Tra destination. Nếu biết và ở port khác: forward một port. Nếu biết ở chính ingress: filter, không gửi lại. Nếu unknown hoặc broadcast: flood các forwarding ports khác ingress. Entries có thể aging để thích ứng host di chuyển.','1. Learn source MAC → ingress port. 2. Look up the destination. If known on another port, forward there. If known on the ingress port, filter. For unknown/broadcast destinations, flood the other forwarding ports. Aging allows stale entries to expire.'],
['Tại sao reply hữu ích?','Why replies matter','Frame đầu A→B dạy switch vị trí A, chưa chắc vị trí B. Khi B reply, source B dạy vị trí B. Sau đó unicast có thể chọn lọc cả hai chiều. Nhiều MAC có thể cùng map một port nếu bên đó có switch khác.','The first A→B frame teaches A’s location, not necessarily B’s. B’s reply teaches B’s source location. Subsequent unicast can be selective in both directions. Multiple MACs can map to one port when another switch is downstream.']],
['Bảng rỗng: A trên p1 gửi B trên p2. Switch học A→p1 và flood p2,p3. B reply qua p2: học B→p2 và gửi riêng p1. A gửi B lần nữa: chỉ p2.','Empty table: A on p1 sends to B on p2. Learn A→p1 and flood p2,p3. B replies on p2: learn B→p2 and forward only p1. The next A→B frame uses only p2.'],
['Học từ destination là lỗi phổ biến. Destination chỉ cho biết ai được tìm, không chứng minh người đó nằm ở ingress.','Learning from the destination is a common error. It identifies the intended recipient, not a host proven reachable via ingress.'],
['Tại sao known destination ở cùng ingress phải filter?','Why filter a known destination on the ingress port?'],['Destination đã ở cùng phía frame đi vào; gửi lại không giúp giao hàng và gây traffic dư.','The destination is already on the side the frame came from; forwarding back adds no useful delivery.'],'bridge');

u(1,'stp',['STP: từ vòng lặp đến cây','STP: from loops to a tree'],[17],
['Redundant links giúp dự phòng nhưng flooding trên cycle có thể không dừng. STP chọn topology forwarding liên thông, không có cycle, bằng thông điệp phân tán.','Redundant links provide backup but flooding over cycles can persist. STP uses distributed messages to choose a connected forwarding topology without cycles.'],[
['Vấn đề vòng lặp','The loop problem','Ethernet frame không có IP-style hop limit. Copies có thể chạy vòng, nhân traffic, làm MAC table thay đổi vì cùng source tới nhiều port. Learning không tự giải cycle; cần kiểm soát topology cho phép forwarding.','Ethernet frames lack an IP-style hop limit. Copies can circulate, amplify traffic and destabilize learning as one source arrives through different ports. Learning alone does not eliminate cycles; forwarding topology must be controlled.'],
['Bầu root và so sánh','Electing a root and comparing paths','Mô hình lớp dùng message <sender, root, distance>. Ban đầu mỗi bridge tự nhận root, distance 0. Ưu tiên root ID nhỏ nhất; cùng root chọn path cost nhỏ nhất; hòa thì sender ID nhỏ hơn. Khi nhận neighbor distance d, candidate distance của mình là d+1 trong mô hình hop-count.','The course model sends <sender, root, distance>. Initially every bridge claims root with distance zero. Prefer the lowest root ID, then lowest path cost, then lower sender ID. Receiving a neighbor’s distance d gives a candidate local distance d+1 in the hop-count model.'],
['Root port, designated và blocked','Root, designated and blocked ports','Non-root chọn root port tốt nhất. Trên mỗi segment, bridge có đường tốt nhất đến root làm designated forwarder; các port thừa bị block. Trong đồ thị point-to-point đơn giản, cây n bridges có n−1 active edges. Không block root port chỉ vì neighbor có đường tốt hơn: chính neighbor đó thường là đường về root.','A non-root bridge selects its best root port. Each segment has a designated forwarder with the best path to the root; redundant ports block. A simple point-to-point tree with n bridges has n−1 active edges. Do not block a root port merely because its neighbor has a better root path—that is often the route to the root.'],
['Convergence và failure','Convergence and failures','Ổn định khi các bridge đồng ý root và không còn configuration tốt hơn làm đổi port/path. Physical links vẫn tồn tại. Failure/topology change khiến thuật toán chạy lại để có thể kích hoạt link trước đó blocked.','Stability means bridges agree on the root and no better configuration changes their paths/ports. Physical links remain. A failure or topology change triggers recomputation, potentially activating a formerly blocked link.']],
['Triangle B1–B2–B3, mọi edge cost 1. B1 root. B2 và B3 đều chọn trực tiếp B1. Trên B2–B3, cost tới root hòa nên B2 thắng theo ID; port phía B3 block. Còn hai active edges nối đủ ba bridge.','Triangle B1–B2–B3 with unit costs: B1 is root. B2 and B3 choose their direct B1 links. On B2–B3 their root costs tie, so B2 wins by ID and B3’s port blocks. Two active edges connect all three bridges.'],
['Message model đơn giản không phải đầy đủ BPDU IEEE: real STP có bridge/port identifiers và link costs. Khi làm bài, dùng đúng giả định đề.','The simplified message is not the complete IEEE BPDU: real STP has bridge/port identifiers and link costs. Use the exercise’s assumptions.'],
['B4 nhận <2,1,2> và <3,1,1>. Chọn neighbor nào?','B4 receives <2,1,2> and <3,1,1>. Which neighbor wins?'],['Chọn B3 vì candidate cost 2 nhỏ hơn 3; sender ID chỉ tie-break sau root và cost.','B3 wins: candidate cost 2 is lower than 3. Sender ID only breaks a tie after root and cost.'],'stp');
