u(4,'ecosystem',['AS, ISP, CDN, IXP và PoP','AS, ISP, CDN, IXP and PoP'],[0,2],
['Internet không có một operator biết và quyết định toàn bộ. Các AS tự quản policies, vừa cạnh tranh vừa cần hợp tác để customers liên lạc toàn cầu.','No single operator decides everything on the Internet. Autonomous systems control their policies, competing while cooperating to connect customers globally.'],[
['AS là boundary quản trị','An AS is an administrative boundary','AS là nhóm routers/networks cùng administrative authority và routing policy, có ASN để nhận diện. Một ISP có thể vận hành một hoặc nhiều AS; một CDN cũng có thể vận hành AS. AS không đồng nghĩa một router hay một subnet.','An AS groups routers/networks under an administrative authority and routing policy, identified by an ASN. An ISP may operate one or many ASes; a CDN may also operate ASes. An AS is neither a single router nor a subnet.'],
['Các vai trò','The roles','Access ISPs nối end users; regional/global ISPs cung cấp reach rộng hơn trong mô hình phân tầng. CDN đưa content gần users và tăng quyền kiểm soát delivery. IXP cung cấp switching infrastructure để ASes interconnect. PoP là điểm thiết bị của provider mà customer có thể nối vào.','Access ISPs connect end users; regional/global ISPs supply broader reach in the hierarchical model. CDNs place content near users and control delivery. IXPs provide interconnection switching infrastructure. A PoP is a provider equipment location where customers can attach.'],
['Multi-homing và flattening','Multihoming and flattening','Multi-homing nối nhiều upstream providers để đa dạng đường và dự phòng. Peering/CDNs/IXPs tạo links trực tiếp, khiến topology ít phân tầng cứng hơn Internet ban đầu. Tiers là mô hình giúp hiểu quan hệ, không phải mọi packet buộc qua Tier1.','Multihoming connects to multiple upstream providers for path diversity and resilience. Peering, CDNs and IXPs add direct connections, flattening the early hierarchy. Tiers are a useful model, not a requirement that all traffic cross a Tier1.']],
['User ISP và CDN cùng có mặt ởIXP có thể trao đổi trực tiếp. Request không nhất thiết đi access→regional→Tier1→regional→CDN nếu policy cho phép direct peering.','A user ISP and CDN at the same IXP can exchange directly. A request need not traverse access→regional→Tier1→regional→CDN if direct peering is permitted.'],
['IXP fabric là hạ tầng interconnection, không tự động là một provider transit cho mọi Internet destination.','An IXP fabric enables interconnection; it is not automatically a transit provider for every destination.'],
['IGP và BGP phân chia trách nhiệm theo boundary nào?','What boundary separates IGP and interdomain BGP roles?'],['IGP tìm đường trong administrative domain; BGP trao reachability/policy giữa ASes, và iBGP phân phối external routes bên trong AS.','IGP finds internal paths; BGP exchanges inter-AS reachability/policy, while iBGP distributes external routes inside an AS.'],'ecosystem');

u(4,'business',['Transit và peering: ai trả cho ai?','Transit and peering: who pays whom?'],[3],
['Quan hệ kinh doanh quyết định route nào có lợi để sử dụng/quảng bá. Hãy gắn một route với nguồn học: customer, peer hay provider.','Business relationships influence useful route choices and advertisements. Label a route by where it was learned: customer, peer or provider.'],[
['Customer–provider','Customer–provider','Customer trả provider để có transit đến các destinations provider cung cấp, thường bao gồm global connectivity. Provider có động lực mang customer traffic vì có doanh thu. Một AS có thể vừa là customer của upstream vừa là provider của downstream.','A customer pays a provider for transit to destinations the provider offers, often global connectivity. The provider earns revenue carrying customer traffic. An AS can be an upstream customer and a downstream provider simultaneously.'],
['Peering','Peering','Peers thường trao reachability tới chính họ và customers, không chia toàn bộ provider routes. Settlement-free nghĩa không thanh toán transit giữa hai peers; vẫn có chi phí router, circuit, port và operations. Peering có điều kiện business, traffic balance và policy; paid peering cũng tồn tại.','Peers commonly exchange their own/customer reachability rather than all provider routes. Settlement-free means no transit payment between the peers, not zero equipment, circuit, port or operating costs. Peering depends on business/traffic policies; paid peering also exists.'],
['Cách tính phí','Charging models','Học liệu mô tả fixed price trong bandwidth range và usage-based tính theo samples (ví dụ mỗi5phút), lấy95th percentile. Xếp samples, bỏ khoảng5% cao nhất, dùng mức còn lại làm billing reference theo hợp đồng. Không phải thu đúng tổng bytes hay peak lớn nhất.','The lesson describes fixed pricing within a bandwidth range and usage-based billing from samples, for example every5minutes, using the95th percentile. Sort samples, discard roughly the highest5%, and use the resulting level as the contractual reference. This is not simply total bytes or the single highest peak.']],
['Hai access ISPs có nhiều traffic đến customers của nhau: peer trực tiếp giúp cả hai giảm lượng traffic phải mua upstream transit. Provider lớn không mặc nhiên đồng ý peer với mạng nhỏ nếu lợi ích không cân xứng.','Two access ISPs exchanging substantial customer traffic can reduce paid upstream transit by peering. A large provider need not agree to peer with a small network if the benefits are asymmetric.'],
['Một AS không có một “loại quan hệ” duy nhất; relationship được xác định theo từng cặp neighbors.','An AS has no single universal relationship type; each neighboring pair has a relationship.'],
['Settlement-free peering có nghĩa không trả phí IXP port không?','Does settlement-free peering eliminate IXP port fees?'],['Không. Nó nói về thanh toán giữa peers; infrastructure fees vẫn có thể có.','No. It concerns payments between peers; infrastructure fees may remain.']);

u(4,'policy',['Import và export: route đi ngược traffic','Import and export: advertisements attract traffic'],[4],
['Quảng bá “tôi tới được prefix P” cho neighbor là lời mời neighbor gửi traffic tới P qua mình. Vì vậy export có hậu quả tài chính và vận hành.','Advertising reachability to P invites a neighbor to send P-bound traffic through you. Export policy therefore has financial and operational consequences.'],[
['Bảng export chuẩn của module','The module’s export matrix','Customer-learned routes: export cho customers, peers và providers. Peer/provider-learned routes: export cho customers, không export cho peers/providers khác. Own originated routes cũng thường quảng bá rộng theo policy. Mô hình này tránh làm unpaid transit giữa các bên không phải customer.','Customer-learned routes are exported to customers, peers and providers. Peer/provider-learned routes go to customers, not other peers/providers. Own routes are also commonly exported broadly subject to policy. This avoids unpaid transit between noncustomers.'],
['Import preference','Import preference','Khi nhiều valid routes đến cùng prefix: customer > peer > provider theo business model. Customer tạo revenue, peer tránh transit charge, provider tốn tiền. Import filtering có thể loại route trước ranking; một route bị filter không còn là ứng viên dù AS_PATH ngắn.','For valid routes to the same prefix, typical preference is customer > peer > provider: revenue, settlement-free exchange, then paid transit. Import filters can remove routes before ranking; a filtered route cannot win because of a short AS_PATH.'],
['Valley-free intuition','Valley-free intuition','Dưới assumptions quan hệ này, path data đi lên customer→provider zero/nhiều lần, có thể qua một peer, rồi đi xuống provider→customer. Sau khi đi xuống, không đi lên lại để tạo free transit. Đây là model policies phổ biến, không luật mọi AS bắt buộc.','Under these relationship assumptions, data paths go uphill customer→provider zero or more times, optionally cross one peer edge, then downhill provider→customer. Going downhill then uphill would create unpaid transit. This is a common policy model, not a universal law.']],
['X học prefixP từ providerA và export cho providerB. B có thể gửi traffic quaX để tớiA, trong khiX không đượcA/B trả transit. Vì vậy typical policy chặn export ấy. Nhưng X export P cho customerC là đúng dịch vụ C đã mua.','X learnsP from providerA and exports it to providerB. B can then transitX towardA without payingX. Typical policy blocks that export. ExportingP to customerC provides the service C purchased.'],
['Đừng đọc arrow advertisement như arrow data. Advertisement P từA→X có thể tạo data path X→A tớiP.','Do not confuse advertisement and data direction. An advertisement fromA toX can create a P-bound data path fromX toA.'],
['X học route từ peer, được export cho customer hay provider?','May X export a peer-learned route to a customer or provider?'],['Customer: có theo mô hình; provider: không theo typical no-free-transit policy.','Customer: yes in the model. Provider: no under typical no-free-transit policy.'],'policy');

u(4,'bgp',['BGP: messages, prefix và AS_PATH','BGP: messages, prefixes and AS_PATH'],[5,6],
['BGP là control-plane protocol trao reachable prefixes và attributes qua TCP sessions. Nó cần scale và thể hiện policy của các AS độc lập.','BGP exchanges reachable prefixes and attributes over TCP sessions as a control-plane protocol. It must scale and express independent AS policies.'],[
['Design goals','Design goals','Scalability: prefixes, ASes, churn và convergence. Policy: filters/ranking do AS tự đặt và có thể giữ kín. Cooperation: quyết định local nhưng tạo reachability toàn cầu. Security không phải thiết kế ban đầu đầy đủ; announcements sai/misconfiguration có thể gây outage vượt khỏi AS.','Goals include scaling prefixes/ASes/churn/convergence; independent, potentially private filtering/ranking policies; and cooperation yielding global reachability. Strong security was not fully built into the original design, so erroneous announcements can disrupt other ASes.'],
['Session và messages','Sessions and messages','Peers lập TCP session; OPEN thương lượng BGP session. UPDATE announce route mới/changed hoặc withdraw route không còn khả dụng. KEEPALIVE giữ session khi không có updates. NOTIFICATION báo lỗi/đóng session là loại message chuẩn bổ sung. Sau initial exchange, changes chủ yếu incremental thay vì gửi toàn bảng liên tục.','Peers establish TCP and negotiate BGP using OPEN. UPDATE announces new/changed routes or withdraws unavailable ones. KEEPALIVE maintains idle sessions. NOTIFICATION reports errors/closure as another standard type. After initial exchange, routing changes are mainly incremental rather than constant full-table transfers.'],
['Route gồm gì?','What is a route?','Destination là IP prefix, không phải từng host riêng. AS_PATH là chuỗi ASes quảng bá đã đi qua; eBGP thường prepend ASN mình. Thấy ASN mình trong path thì reject để tránh AS loop. NEXT_HOP là IP cần reach để dùng route; không phải luôn next physical neighbor của router internal.','Destinations are prefixes rather than individual hosts. AS_PATH records traversed ASes; eBGP normally prepends the advertising ASN. Seeing one’s own ASN rejects an AS loop. NEXT_HOP is the IP that must be reachable to use a route, not always an internal router’s immediate physical neighbor.']],
['AS65003 originate P; AS65002 nghe path[65003], quảng bá cho65001 thành[65002,65003]. Nếu65003 nghe path chứa65003 quay lại, nó không chọn route loop đó.','AS65003 originatesP. AS65002 hears[65003] and advertises[65002,65003] to65001. If65003 receives a path containing itself, it rejects that looping route.'],
['AS_PATH ngắn không chắc latency thấp; BGP không nhìn mọi internal hop/queue trong các AS. TCP chở BGP updates không làm BGP thành thuật toán congestion control.','A short AS_PATH does not guarantee low latency; BGP does not expose all internal hops/queues. TCP carrying updates does not make BGP a congestion-control algorithm.'],
['Withdrawal có nhất thiết do cable đứt không?','Must a withdrawal mean a broken cable?'],['Không. Failure, mất session hoặc policy change đều có thể khiến route bị rút.','No. Failures, session loss or policy changes can withdraw routes.'],'aspath');

u(4,'ibgp',['iBGP, eBGP và IGP phối hợp','How iBGP, eBGP and IGP cooperate'],[7],
['eBGP học external reachability từ AS khác; iBGP chia sẻ external routes trong AS; IGP tìm đường nội bộ để tới next hop đã chọn.','eBGP learns reachability from another AS; iBGP shares external routes within an AS; an IGP finds internal paths to the chosen next hop.'],[
['Phân loại session','Classifying sessions','Hai BGP peers cùng ASN → iBGP; khác ASN → eBGP. Đó là quan hệ control session, không mô tả từng physical link. Một internal router có thể reach BGP peer qua nhiều intermediate routers.','Peers in the same AS use iBGP; different ASes use eBGP. This classifies a control session, not each physical link. An internal router may reach a peer over multiple intermediate routers.'],
['Full mesh để disseminate','A full mesh for dissemination','Mô hình module dùng full mesh giữa BGP routers: n(n−1)/2 sessions. Basic iBGP không relay iBGP-learned routes sang iBGP peers khác; full mesh tránh visibility gaps. Route reflectors là cơ chế scale thay full mesh, có thêm rules và risks.','The course uses a full mesh among BGP routers, with n(n−1)/2 sessions. Basic iBGP does not relay iBGP-learned routes to other iBGP peers, so the mesh avoids visibility gaps. Route reflectors scale beyond this model with additional rules and risks.'],
['NEXT_HOP resolution','NEXT_HOP resolution','BGP chọn external prefix→BGP next hop; IGP resolve next hop thành output/interface local. Khi đưa route qua iBGP, next hop có thể được giữ nguyên hoặc chỉnh next-hop-self theo cấu hình. Không nên giả định mọi iBGP advertisement tự đổi next hop thành border router.','BGP selects a prefix’s BGP next hop; the IGP resolves it to a local output/interface. An iBGP advertisement may preserve that next hop or use configured next-hop-self. It does not automatically become the advertising border router in every case.']],
['BorderE họcP qua eBGP, nói cho internalR qua iBGP. R chọn route ấy, nhưng first physical hop có thể là routerM trên đường IGP tớiE/next hop. iBGP session không phải tunnel data trực tiếp R→E.','BorderE learnsP over eBGP and informs internalR over iBGP. R selects it, but the first physical hop may beM on the IGP path toE/the next hop. An iBGP session is not a direct data tunnel.'],
['iBGP không thay OSPF. BGP route có thể “biết” prefix mà không dùng được nếu NEXT_HOP không reachable.','iBGP does not replace OSPF. A learned BGP prefix may be unusable if its NEXT_HOP is unreachable.'],
['6 BGP routers full mesh cần bao nhiêu sessions?','How many sessions connect6 BGP routers in a full mesh?'],['6×5/2=15 logical sessions; không yêu cầu15 physical cables.','6×5/2=15 logical sessions, not necessarily15 physical cables.'],'ibgp');

u(4,'selection',['Chọn route: so theo thứ tự, không cộng điểm','Route selection: ordered comparisons, not scoring'],[8],
['BGP so các route đến cùng prefix theo thứ tự attributes. Criterion đầu tiên phân biệt được hai route quyết định; các tiêu chí sau không cứu được route đã thua.','BGP compares routes to the same prefix in attribute order. The first distinguishing criterion decides; later criteria cannot rescue a route already eliminated.'],[
['Pipeline của router','Router pipeline','Receive advertisements → import filters/attribute assignment → decision process → selected route/RIB và FIB với next-hop resolution → export filters → advertisements cho neighbors. Import/export có thể khác cho từng neighbor.','Receive advertisements → import filters/attribute assignment → decision process → selected route/RIB and resolved FIB → export filters → neighbor advertisements. Import/export can differ by neighbor.'],
['Thứ tự trong slide module','The module slide’s order','1 cao nhất LocalPref. 2 ngắn nhất AS_PATH. 3 thấp nhất origin type. 4 thấp nhất MED khi comparison áp dụng. 5 eBGP-learned trước iBGP-learned. 6 IGP cost thấp nhất tới border/next hop. 7 router ID thấp nhất để tie-break. Đây là simplified ordering đã đối chiếu hình slide, không phải mọi vendor đầy đủ.','1 highest LocalPref;2 shortest AS_PATH;3 lowest origin type;4 lowest MED when applicable;5 eBGP-learned over iBGP-learned;6 lowest IGP cost to the border/next hop;7 lowest router ID. This is the verified simplified slide order, not every vendor’s full implementation.'],
['Origin và MED context','Origin and MED context','Origin preference thông thường IGP < EGP < incomplete; origin attribute không phải việc route được nghe qua iBGP hay eBGP. MED mặc định thường chỉ compare routes từ cùng neighboring AS, trừ policy thay đổi. Luôn kiểm tra assumptions đề.','Origin preference is normally IGP < EGP < incomplete; the ORIGIN attribute is not whether the route was learned via iBGP/eBGP. MED is normally compared among routes from the same neighboring AS unless policy changes that. Check exercise assumptions.']],
['A:LocalPref300,path5,IGP20. B:LocalPref200,path2,IGP1. A thắng ngay ởLocalPref, dù B ngắn/gần hơn. Nếu LocalPref bằng nhau, path2 củaB mới thắng.','A has LocalPref300,path5,IGP20. B has LocalPref200,path2,IGP1. A wins immediately on LocalPref despite B being shorter/nearer. With tied LocalPref, B’s path2 would win.'],
['Không so LocalPref giữa hai prefixes khác nhau rồi dùng prefix đó thay prefix kia. Route selection theo prefix; data forwarding còn dùng longest-prefix match.','Do not compare LocalPref across different prefixes as substitutes. Selection is per prefix; packet forwarding also uses longest-prefix match.'],
['Hai route hòa trước IGP cost; costs4 và9. Chọn route nào và gọi là gì?','Two routes tie before IGP cost; costs are4 and9. Which wins and what is this called?'],['Cost4 thắng bằng closest-exit/hot-potato criterion.','Cost4 wins through closest-exit/hot-potato selection.'],'bgpselect');

u(4,'attributes',['LocalPref và MED: exit hay entry?','LocalPref and MED: exit or entry?'],[8],
['Hai thuộc tính đều ảnh hưởng routing nhưng khác người đặt, hướng traffic muốn điều khiển và chiều ưu tiên.','Both attributes influence routing but differ in who sets them, which traffic direction they target and which value wins.'],[
['LocalPref: tôi chọn đường ra','LocalPref: choosing my exit','AS tự đặt LocalPref, phân phối bên trong AS để ưu tiên egress. Số cao hơn thắng. Customer300, peer200, provider100 là ví dụ illustrative để encode business preference, không phải chuẩn bắt buộc. Đây là knob outbound từ góc nhìn AS đặt nó.','The AS assigns LocalPref and distributes it internally to prefer an exit. Higher wins. Customer300,peer200,provider100 illustrate business preferences rather than mandated values. It controls outbound traffic from the assigning AS’s perspective.'],
['MED: gợi ý neighbor chọn đường vào','MED: suggesting an entry to a neighbor','ASB có hai interconnects vớiASA; B quảng bá cùng prefix với MED10 tạiR1 và50 tạiR2. A có thể chọnR1 nếu tiêu chí trước hòa và A compare/honor MED. Lower wins. B ảnh hưởng inbound vàoB, không ép neighbor bỏ LocalPref của họ.','B has two interconnects withA and advertises a prefix with MED10 atR1 and50 atR2. A may chooseR1 if earlier criteria tie and its policy compares/honors MED. Lower wins. B influences inbound traffic but cannot override the neighbor’s LocalPref.'],
['Policy tags và phạm vi','Policy tags and scope','Nguồn có ví dụ dùng attribute để đánh dấu quan hệ khi filter. Nên tách ý tưởng “gắn metadata cho route” khỏi ý nghĩa chuẩn MED: MED là exit discriminator, không tự mã hóa customer/peer/provider. Communities là cơ chế tag policy phổ biến; phần core cần hiểu filters/ranking thực hiện policy.','The source discusses tagging routes for filtering. Separate generic route metadata from MED’s standard discriminator role: MED does not inherently encode customer/peer/provider status. Communities commonly carry policy tags; the core lesson is how filters and rankings implement policy.']],
['B muốn inbound quaR1, đặt MED10. Nhưng A đặt LocalPref cao hơn choR2 vì business. R2 vẫn thắng vì A xét LocalPref trước MED. B chỉ ảnh hưởng, không có quyền quyết định policy củaA.','B requests inbound viaR1 using MED10. A assigns higher LocalPref toR2 for business reasons. R2 still wins because A compares LocalPref first. B influences rather than controls A’s policy.'],
['“Inbound/outbound” phải gắn với AS nào đang đặt thuộc tính; đổi góc nhìn sẽ dễ đảo nghĩa.','Always state whose inbound/outbound traffic is meant. Switching viewpoints easily reverses the meaning.'],
['LocalPref và MED, giá trị nào ưu tiên?','Which values are preferred for LocalPref and MED?'],['LocalPref cao hơn; MED thấp hơn khi được compare.','Higher LocalPref; lower MED when comparison applies.']);

u(4,'risks',['Scalability, route leaks và flap damping','Scalability, route leaks and flap damping'],[9],
['BGP state và update churn có thể tăng mạnh khi faults hoặc misconfiguration xuất hiện. Protocol design cần operational safeguards, không chỉ route-selection logic.','Faults and misconfiguration can amplify BGP state and update churn. Operating the protocol requires safeguards beyond route-selection logic.'],[
['Prefix growth','Prefix growth','Nhiều more-specific prefixes tăng memory và processing. Aggregation giảm advertisements khi reachability/policy cho phép; filters giới hạn overly-specific prefixes; max-prefix giới hạn lượng route mỗi session. Small AS có thể dùng default route thay full table nếu phù hợp.','More-specific prefixes increase memory/processing. Aggregation reduces advertisements when reachability/policy permit; filters limit overly specific routes; max-prefix constrains per-session route counts. A small AS may use a default route instead of a full table when suitable.'],
['Churn và damping','Churn and damping','Repeated announcements/withdrawals gây processor load, propagation và instability. Flap damping tích penalty theo changes, suppress route khi vượt threshold và reuse sau decay. Đổi lại route đã tốt trở lại có thể còn bị suppress, ảnh hưởng reachability.','Repeated announcements/withdrawals cause processing load and instability. Flap damping accumulates penalties, suppresses a route above a threshold and reuses it after decay. A repaired route can remain suppressed, harming reachability.'],
['Misconfiguration lan rộng','Misconfiguration propagates','Export sai provider/peer route có thể tạo route leak; originate không đúng prefix có thể hút traffic sai. Filters cần xét nguồn, prefix và policy; chỉ có AS_PATH loop prevention không đủ bảo đảm route hợp pháp.','Exporting a provider/peer route incorrectly can leak routes; originating an incorrect prefix can misdirect traffic. Filters must consider origin, prefix and policy. AS_PATH loop prevention alone does not establish legitimacy.']],
['AS chỉ nên advertise203.0.113.0/24 nhưng nhận lỗi gửi hàng nghìn routes. Max-prefix có thể giới hạn tác động session; import/export filtering ngăn routes không được phép. Damping nhằm route churn, không thay prefix validation.','An AS meant to advertise203.0.113.0/24 accidentally sends thousands of routes. Max-prefix limits session impact and filters restrict unauthorized routes. Damping targets churn, not prefix validation.'],
['Aggregation cần thật sự có reachability phù hợp; quảng bá supernet không reachable có thể tạo blackhole.','Aggregation requires appropriate reachability; advertising an unreachable supernet can create blackholes.'],
['Vì sao không đặt flap damping cực mạnh cho mọi prefix?','Why not apply extremely aggressive damping to every prefix?'],['Vì giảm updates có thể đổi lấy outage kéo dài cho route đã phục hồi; cần cân trade-off availability.','Because fewer updates can come at the cost of prolonged suppression of recovered routes and reduced availability.']);

u(4,'ixp',['IXP: fabric chung, policies riêng','IXP: shared fabric, independent policies'],[10],
['IXP cho nhiều participant ASes nối routers vào hạ tầng switching chung và trao traffic trực tiếp. Cùng ởIXP không tự động có nghĩa mọi cặp đều peer.','An IXP connects participant routers to shared switching infrastructure for direct traffic exchange. Presence alone does not automatically establish peering between every pair.'],[
['Tham gia thế nào?','How participation works','AS cần ASN public, router có BGP, port/circuit tới fabric và thỏa thuận terms củaIXP. Public peering dùng shared switching fabric; bilateral policies vẫn do participants quyết định. Chi phí có thể gồm connection setup, recurring port và membership.','Participation requires a public ASN, a BGP-capable router, a port/circuit to the fabric and agreement to IXP terms. Public peering uses shared switching while bilateral policies remain with participants. Costs can include setup, port fees and membership.'],
['Tại sao có lợi?','Why it helps','Giữ local traffic local, giảm upstream transit cost, giảm path delay và tăng interconnection choices. IXP có thể trải nhiều colocation sites với redundant switching; không nhất thiết một chiếc switch hoặc một tòa nhà.','Keeping local traffic local can reduce upstream cost and delay while improving interconnection options. An IXP may span colocation sites with redundant switching, rather than one switch or building.'],
['Các dịch vụ','Services','Public peering; private interconnect chuyên dụng; route servers vàSLAs; remote access qua resellers; có nơi hỗ trợ mobile peering. DDoS blackholing giúp tránh traffic tấn công tới target, nhưng cũng drop traffic tới target đó. Một sốIXP cung cấp IRR, DNS/root/ccTLD, NTP, monitoring hoặc speed tests.','Services include public peering, dedicated private interconnects, route servers/SLAs and reseller remote access, sometimes mobile peering. DDoS blackholing blocks target-bound traffic, including legitimate traffic to that target. Some IXPs offer IRR, DNS/root/ccTLD, NTP, monitoring or speed tests.']],
['ISP và CDN đều nối fabric nhưng chưa trao routes/policy phù hợp: physical connectivity tồn tại mà prefix chưa usable. Khi BGP peering được cấu hình, họ có thể gửi data trực tiếp qua fabric.','An ISP and CDN can be attached physically without usable prefix reachability until routing/policy is established. Once BGP peering is configured, they can exchange data directly through the fabric.'],
['IXP participant không buộc mua transit từ mọi participant. Public peering “settlement-free” vẫn có infrastructure costs và có thể có thỏa thuận paid peering riêng.','Participants need not buy transit from every other participant. Settlement-free public peering still has infrastructure costs and may coexist with paid peering agreements.'],
['Private interconnect khác public peering ở đâu?','How does a private interconnect differ from public peering?'],['Nó cung cấp kết nối riêng cho hai bên thay vì dùng chung public fabric để exchange traffic.','It provides a dedicated connection between two parties instead of using the shared public exchange fabric.'],'ixp');

u(4,'route-server',['Route server: control plane, không chở data','Route server: control plane without data transit'],[11],
['Full bilateral peering giữa n participants cần n(n−1)/2 sessions. Route server giúp participants trao routing information qua ít sessions hơn, nhưng data vẫn đi giữa họ.','Full bilateral peering among n participants needs n(n−1)/2 sessions. A route server reduces session management while data still travels between participants.'],[
['Master và participant RIB','Master and participant RIBs','Mô hình module có Master RIB và participant-specific RIBs. Import filters kiểm tra participant có được quảng bá prefix ấy không. Export filters thể hiện participant cho phép peers nào nhận routes. RS thực hiện selection/filtering, không phải broadcast mọi route vô điều kiện.','The course model has a Master RIB and participant-specific RIBs. Import filters validate what a participant may advertise. Export filters express which participants may receive routes. The server selects/filters rather than broadcasting everything unconditionally.'],
['Bốn bước X→RS→Z','Four steps from X through RS to Z','1 X announceP vào X-specific RIB. 2 Import filter cho phép →Master RIB. 3 Export policy cho Z nhận →Z-specific RIB. 4 RS announceP choZ với X là NEXT_HOP. Nếu một filter từ chối, route không tớiZ theo đường này.','1 X announcesP into its RIB.2 Passing import policy admits it to the Master RIB.3 Export permission places it in Z’s RIB.4 RS advertisesP toZ withX as NEXT_HOP. A rejecting filter prevents this propagation.'],
['Đường control khác data','Control and data paths differ','BGP messages X→RS→Z; data tớiP đi Z→IXP switching fabric→X. RS không cần nằm trên data path. Một RS minh họa có n participant sessions; deployment thường có nhiều RS dự phòng nên tổng sessions tăng tương ứng nhưng vẫn dễ quản lý hơn all-pairs.','BGP messages travel X→RS→Z, while P-bound data goes Z→IXP fabric→X. The RS need not forward the data. One illustrative server needs n participant sessions; deployments often use redundant servers, increasing sessions but retaining simpler management than all-pairs.']],
['10 ASes all-pairs:45 sessions. MộtRS:10 participant sessions. AS3 nhận route củaAS7 quaRS nhưng data gửi NEXT_HOP AS7, không gửi quaRS rồi mới tớiAS7.','Ten ASes need45 all-pairs sessions; oneRS uses10 participant sessions. AS3 learnsAS7’s route viaRS but sends data toAS7’s next hop rather than throughRS.'],
['RS không thay policies bằng “everyone peers with everyone”. Export restrictions vẫn được áp dụng cho từng participant.','The RS does not mean everyone automatically peers with everyone; participant-specific restrictions remain.'],
['RS announce route củaX choZ; NEXT_HOP ai trong mô hình?','When RS advertises X’s route to Z, who is NEXT_HOP in this model?'],['X, để data đi trực tiếp từZ tớiX qua fabric.','X, so data goes directly fromZ toX through the fabric.'],'route-server');

u(4,'remote',['Mở rộng: suy luận remote peering','Extension: inferring remote peering'],[12],
['Remote peering dùng provider/reseller chở kết nối tớiIXP mà AS không cần đặt router trực tiếp tại facility củaIXP. Connectivity logic không nói hết physical path.','Remote peering uses a provider/reseller to reach an IXP without the AS’s router physically residing in an IXP facility. Logical connectivity does not expose the entire physical path.'],[
['Vì sao dùng?','Why use it?','Giảm rào cản geographic/cost cho mạng nhỏ; tận dụng transport/reseller ports để tới nhiềuIXPs. Đổi lại có phụ thuộc thêm và latency/physical route không dễ suy ra từBGP adjacency.','It lowers geographical/cost barriers for smaller networks using transport/reseller ports to reach IXPs. It adds dependencies, and latency/physical routes cannot be inferred easily from BGP adjacency.'],
['RTT không đủ','RTT alone is insufficient','RTT từ vantage point trongIXP tới participant interface chỉ là một tín hiệu. IXP có nhiều facilities và paths thay đổi khiến local/remote phân loại sai nếu chỉ đặt một RTT threshold.','RTT from an IXP vantage point to a participant interface is one signal. Multisite IXPs and varying paths make a single latency threshold unreliable for classifying local versus remote.'],
['Kết hợp bằng chứng','Combine evidence','Port capacity nhỏ có thể gợi reseller virtual port; tìm co-location chung giữaAS vàIXP; suy luận router nối nhiềuIXPs dựa shared facilities; xem private peers tại cùng facility. Mỗi evidence có uncertainty, không biến metadata thành proof tuyệt đối.','Small port capacity can suggest reseller virtual ports; examine shared colocation, multi-IXP router/facility relationships and private peers at the same facility. Each signal is uncertain rather than definitive proof.']],
['RTT thấp nhưng không có colocated facility đáng tin cậy: chưa đủ kết luận local. Có thể là remote transport gần, hoặc metadata thiếu; cần thêm port/router/colocation evidence.','Low RTT without reliable shared-colocation evidence is insufficient to conclude local presence. Nearby remote transport or incomplete metadata may explain it; obtain more evidence.'],
['Số liệu capacity/IXP count trong paper lịch sử không được dùng như thống kê Internet hiện tại.','Historical paper capacities and IXP counts are not current Internet statistics.'],
['Một measurement RTT có xác định chắc remote peering không?','Can one RTT measurement determine remote peering with certainty?'],['Không; cần nhiều nguồn evidence và nêu uncertainty.','No. Combine evidence and state uncertainty.']);

u(4,'verification',['Mở rộng: kiểm tra BGP configuration','Extension: checking BGP configuration'],[13],
['Một config đúng syntax vẫn có thể làm routes không lan tới nơi cần hoặc traffic không tới đích. Static analysis tìm faults trước deployment.','A syntactically valid configuration can hide routes or send traffic incorrectly. Static analysis looks for such faults before deployment.'],[
['Path visibility','Path visibility','Destinations phải được disseminate đúng trong network. Full-mesh/route-reflector lỗi, cluster problems hoặc session chỉ cấu hình một phía có thể partition signaling, khiến router không thấy usable route.','Destinations must be disseminated appropriately. Full-mesh/route-reflector mistakes, cluster issues or one-sided session configuration can partition signaling and hide usable routes.'],
['Route validity','Route validity','Traffic theo route phải tới destination. Import/export filtering không nhất quán, policy cũ còn sót, undefined references, AS prepending hoặc NEXT_HOP handling sai có thể phá correctness. Không phải bản thân next-hop-self luôn sai; cấu hình và interaction mới quyết định.','Traffic following a route should reach its destination. Inconsistent filters, leftover policies, undefined references, AS prepending or incorrect NEXT_HOP handling can break correctness. Next-hop-self is not inherently wrong; its configuration and interactions matter.'],
['rcc workflow và giới hạn','rcc workflow and limits','Router Configuration Checker normalize vendor configs về route dissemination/filtering/ranking model rồi kiểm tra và báo faults. Có thể dùng trước deployment hoặc audit live configs. Theo nguồn, rcc không sound/complete tuyệt đối: có false positives và missed faults.','The Router Configuration Checker normalizes vendor configs into dissemination/filtering/ranking models, checks them and reports faults. It can run predeployment or audit live configs. The source notes it is neither fully sound nor complete: false positives and missed faults remain possible.']],
['R1 có route nhưng không advertise qua iBGP session bị thiếu tớiR2: visibility fault. R2 có route nhưng NEXT_HOP không resolve đúng làm blackhole: vấn đề validity/reachability của forwarding.','R1 knows a route but a missing iBGP session hides it fromR2: a visibility fault. R2 knows a route whose next hop cannot be resolved properly: a forwarding validity/reachability problem.'],
['Không có warning từ static checker không chứng minh mọi behavior live đều đúng. Model và phạm vi check có giới hạn.','No static warning is not proof of all live behavior. The checker’s model and scope are limited.'],
['Visibility và validity khác nhau thế nào?','How do visibility and validity differ?'],['Visibility: router có học được route cần thiết không. Validity: traffic sử dụng route có tới đúng destination không.','Visibility asks whether routers learn necessary routes; validity asks whether traffic using them reaches the destination.']);
