window.QUESTION_BANK={1:[],2:[],3:[],4:[],5:[],6:[],7:[],8:[],9:[],10:[],11:[],12:[]};
const pair=x=>Array.isArray(x)?x:String(x).includes('|')?String(x).split('|'):[String(x),String(x)];
function makeQuestion(n,chapter,prompt,answers,explanation,type='Khái niệm / Concept',trap){const c=COURSE.find(c=>c.lesson===n&&c.id===chapter);const opts=answers.map(pair),shift=(QUESTION_BANK[n].length*3+1)%4;const rotated=opts.map((_,i)=>opts[(i+shift)%4]);QUESTION_BANK[n].push({chapter,prompt:pair(prompt),options:rotated,correct:(4-shift)%4,explanation:explanation?pair(explanation):[`${pair(answers[0])[0]} — ${c.intro[0]}`,`${pair(answers[0])[1]} — ${c.intro[1]}`],trap:trap?pair(trap):c.pitfall,type})}
function concept(n,chapter,prompt,...options){makeQuestion(n,chapter,prompt,options)}
concept(1,'growth','Web và Internet liên hệ thế nào?|How are the Web and Internet related?','Web là ứng dụng trên Internet|The Web is an application on the Internet','Hai tên của cùng một protocol|Two names for one protocol','Internet chỉ tồn tại bên trong browser|The Internet exists only inside browsers','Web là physical medium của Internet|The Web is the Internet’s physical medium');
concept(1,'growth','Vì sao packet switching hợp bursty traffic?|Why does packet switching suit bursty traffic?','Flows chia sẻ link thay vì luôn giữ circuit riêng|Flows share links instead of constantly reserving circuits','Mọi packet được bảo đảm không queue|Every packet is guaranteed no queue','Nó loại bỏ nhu cầu địa chỉ|It eliminates addressing','Nó yêu cầu mọi source gửi liên tục|It requires every source to transmit continuously');
concept(1,'layers','“Reliable byte stream” mô tả gì?|What does “reliable byte stream” describe?','Service cung cấp cho application|A service offered to the application','MAC address của receiver|The receiver’s MAC address','Cách biểu diễn tín hiệu quang|An optical signal encoding','Một route trong FIB|A route in the FIB');
concept(1,'layers','Socket nằm ở boundary nào trong model?|Where is the socket boundary in the model?','Application–transport|Application–transport','Network–physical|Network–physical','Physical–copper|Physical–copper','Router–router luôn trực tiếp|Always directly between routers');
concept(1,'upper','Byte order mismatch thuộc trách nhiệm nào?|Which responsibility concerns byte-order mismatch?','Presentation|Presentation','Bầu root STP|STP root election','Chọn egress BGP|BGP egress selection','Physical power supply|Physical power supply');
concept(1,'upper','Ghép audio/video vào cùng call thuộc khái niệm nào?|Which concept groups audio/video into one call?','Session|Session','ARP forwarding|ARP forwarding','Congestion avoidance|Congestion avoidance','Link metric|Link metric');
concept(1,'lower','Link reliability bảo vệ phạm vi nào?|What scope does link reliability protect?','Một local link|One local link','Toàn bộ Internet path|The entire Internet path','Database transaction của app|The application database transaction','Mọi session trong host|Every host session');
concept(1,'encapsulation','Router không NAT thường giữ gì trong packet transit?|What does a non-NAT router normally preserve?','Source/destination IP addresses|Source/destination IP addresses','Destination MAC qua mọi routed hop|Destination MAC across every routed hop','TTL nguyên vẹn qua mọi hop|Unchanged TTL across every hop','Toàn bộ frame gốc không đổi|The complete original frame unchanged');
concept(1,'encapsulation','Payload của IP datagram có thể là gì?|What can an IP datagram carry as payload?','TCP segment|A TCP segment','Toàn bộ physical cable|The complete physical cable','Bảng STP root của toàn LAN|The whole LAN’s STP root table','Chỉ riêng IP header|Only the IP header');
concept(1,'end-to-end','ACK TCP cho order chứng minh điều gì?|What does a TCP ACK of order bytes establish?','Nhận bytes ở TCP, chưa chứng minh DB commit|TCP receipt, not database commit','DB chắc chắn đã commit|The database has certainly committed','Người dùng đã đọc order|The user has read the order','NAT không có state|NAT has no state');
concept(1,'end-to-end','Lõi đơn giản hỗ trợ đổi mới thế nào?|How does a simple core support innovation?','App mới có thể triển khai chủ yếu ở endpoints|New apps can largely deploy at endpoints','Mọi app phải sửa từng router|Every app must modify every router','Loại bỏ mọi header|It removes all headers','Bắt mọi app dùng cùng reliability trade-off|It forces one reliability trade-off on all apps');
concept(1,'nat','NAT dùng gì để giao reply đúng private host?|How does NAT deliver a reply to the private host?','Translation mapping cho public tuple|A public-tuple translation mapping','Chỉ destination MAC của remote server|Only the remote server’s destination MAC','Broadcast mọi reply ra Internet|Broadcasting every reply to the Internet','Một DNS record thay tất cả state|One DNS record replacing all state');
concept(1,'nat','STUN chủ yếu giúp gì trong topic này?|What does STUN principally help with here?','Khám phá NAT public address/port|Discovering the NAT public address/port','Bầu bridge root|Electing a bridge root','Xóa mọi firewall policy|Removing all firewall policy','Tạo guarantee TCP không loss|Guaranteeing TCP never loses data');
concept(1,'hourglass','Substrate của một protocol nằm ở đâu?|Where is a protocol’s substrate?','Layer dưới cung cấp service|A lower layer supplying service','Layer trên dùng protocol đó|An upper layer depending on it','Luôn cùng layer cạnh tranh|Always a same-layer competitor','Một router ID trong STP|An STP router identifier');
concept(1,'hourglass','Evolutionary value tăng chủ yếu theo gì?|What chiefly increases evolutionary value?','Giá trị dependents/products|Value of dependent products','Chỉ tốc độ clock CPU|Only CPU clock speed','Tuổi protocol càng trẻ càng cao|Younger protocol age alone','Số cổng MAC của switch|The switch’s MAC port count');
concept(1,'hourglass','Ossification là gì?|What is ossification?','Core khó đổi vì deployment/dependencies|A core resistant to change due to deployment/dependencies','Tất cả edges ngừng đổi mới|All edge innovation stops','Packet không có IP header|Packets have no IP header','Mọi protocol mới thắng ngay|Every new protocol immediately wins');
concept(1,'redesign','Trong4D, plane nào tính từ network-wide view?|Which4D plane computes using a network-wide view?','Decision|Decision','Data|Data','Physical|Physical','Presentation|Presentation');
concept(1,'bridges','Switch học entry mới từ gì?|What teaches a switch a new entry?','Source MAC và ingress port|Source MAC and ingress port','Destination MAC và random port|Destination MAC and random port','TCP ACK và cwnd|TCP ACK and cwnd','AS_PATH và LocalPref|AS_PATH and LocalPref');
concept(1,'bridges','Known destination cùng ingress cần làm gì?|What happens for a known destination on ingress?','Filter frame|Filter the frame','Flood trở lại ingress|Flood back onto ingress','Thay destination IP|Change the destination IP','Tăng TTL vô hạn|Increase TTL indefinitely');
concept(1,'stp','STP giữ redundancy bằng cách nào?|How does STP retain physical redundancy?','Block forwarding trên một số ports|Block forwarding on selected ports','Cắt bỏ cables vĩnh viễn|Permanently remove cables','Chỉ xóa TCP sessions|Only delete TCP sessions','Bắt all ports forward mọi broadcast|Make all ports forward every broadcast');

concept(2,'transport','Network layer không phân biệt được gì chỉ bằng IP?|What can the network layer not distinguish with an IP alone?','Process/socket cần nhận|The receiving process/socket','Host destination address|The destination host address','Destination IP prefix|The destination IP prefix','Host source address|The source host address');
concept(2,'sockets','TCP accepted sockets cùng local port phân biệt bằng gì?|How are accepted TCP sockets on one local port distinguished?','Full4-tuple|The full4-tuple','Chỉ destination port|Only destination port','Chỉ UDP length|Only UDP length','Chỉ initial TTL|Only initial TTL');
concept(2,'sockets','Persistent HTTP trong ví dụ giảm gì?|What does persistent HTTP reduce in the example?','Số lần tạo TCP connection lặp lại|Repeated TCP connection creation','Mọi nhu cầu ACK|All need for ACKs','Mọi byte HTTP header|All HTTP header bytes','Số layer xuống còn một|The stack to one layer');
concept(2,'udp','UDP checksum cung cấp chức năng nào?|What function does the UDP checksum provide?','Error detection, không recovery|Error detection, not recovery','Retransmission tự động|Automatic retransmission','Reliable ordering|Reliable ordering','Congestion avoidance mặc định|Default congestion avoidance');
concept(2,'udp','Checksum UDP có bao gồm app data không?|Does UDP checksum coverage include application data?','Có, cùng header và pseudo-header|Yes, with header and pseudo-header','Không, chỉ ports|No, only ports','Không, chỉ length|No, only length','Chỉ nếu dùng TCP|Only when using TCP');
concept(2,'handshake','ACK cuối handshake có SYN bằng gì?|What is SYN in the final handshake ACK?','0','1','Bằng rwnd|Equal to rwnd','Bằng client port|Equal to the client port');
concept(2,'handshake','FIN từA nói điều gì?|What does A’s FIN mean?','A hết data gửi trong chiều của nó|A has finished sending its direction','B bắt buộc đã hết data ngay|B must immediately have no data left','Mọi router ngừng forward|All routers stop forwarding','Đã xóa physical link|The physical link was deleted');
concept(2,'arq','Nhược điểm stop-and-wait trên RTT lớn?|What limits stop-and-wait over large RTTs?','Link có thể idle lâu trong lúc chờ ACK|The link can idle while waiting for ACKs','Không cần timeout|It never needs a timeout','Mỗi packet buộc qua BGP RS|Every packet traverses a route server','Không cần sequence numbers|No sequence numbers are needed');
concept(2,'arq','SACK khác cumulative ACK ở điểm nào?|How does SACK add to cumulative ACKs?','Báo các blocks out-of-order đã nhận|Reports received out-of-order blocks','Bỏ hết sequence numbering|Removes sequence numbering','Bảo đảm không bao giờ timeout|Guarantees no timeout','Cho app nhận stream sai thứ tự|Delivers the stream out of order to the app');
concept(2,'ack','ACK=k thường nghĩa gì?|What does ACK=k normally mean?','Byte kế tiếp mong đợi làk|The next expected byte isk','Bytek chắc chắn đã nhận|Bytek is definitely received','Đã nhậnk packets|Exactlyk packets arrived','Đã đọc app toàn bộ bytes|The app consumed every byte');
concept(2,'ack','Fast retransmit classic được kích bởi gì?|What triggers classic fast retransmit?','Ba duplicate ACKs|Three duplicate ACKs','Ba new SYNs|Three new SYNs','rwnd luôn bằng0|rwnd always equaling0','Router đổi MAC|A router changing MAC');
concept(2,'flow','App đọc chậm làm biến nào giảm khi buffer đầy dần?|Which variable shrinks as slow reads fill the buffer?','rwnd','AS_PATH','SYN','MSS luôn giảm|MSS always shrinks');
concept(2,'flow','Zero-window probe giải vấn đề gì?|What does a zero-window probe address?','Sender không biết window đã mở lại|The sender missing a reopened window','Router quên OSPF topology|A router forgetting OSPF topology','BGP longest prefix|BGP longest prefix','MAC flooding loop|A MAC flooding loop');
concept(2,'congestion','Goal nào nhắm tránh queue dài?|Which goal targets long queues?','Low delay|Low delay','Higher header count|Higher header count','Longest path|Longest path','Maximum buffer occupancy|Maximum buffer occupancy');
concept(2,'cwnd','Window limit kết hợp là gì?|What is the combined window constraint?','min(cwnd,rwnd)','cwnd+rwnd','max(cwnd,rwnd)','cwnd×rwnd');
concept(2,'reno','Congestion avoidance Reno tăng xấp xỉ bao nhiêu?|How fast does Reno congestion avoidance grow approximately?','1MSS mỗiRTT|1MSS per RTT','1MSS mỗiACK bất kể window|1MSS per ACK regardless of window','Double mỗiRTT|Double each RTT','Không tăng sau handshake|No increase after handshake');
concept(2,'reno','Timeout trong Reno model dẫn tới gì?|What follows timeout in the Reno model?','cwnd về1MSS và slow start|cwnd returns to1MSS and slow start','Luôn giữ cwnd cũ|Always retain the old cwnd','Luôn tăng gấp đôi|Always double cwnd','Xóa IP addresses|Delete IP addresses');
concept(2,'fairness','Per-flow fairness có bảo đảm per-app fairness không?|Does per-flow fairness guarantee per-app fairness?','Không, app có thể mở nhiều flows|No, an app can open multiple flows','Có trong mọi network|Yes in every network','Có nếu app dùng cùng DNS|Yes if apps use the same DNS','Có nếu chỉ có một IXP|Yes if there is one IXP');
concept(2,'cubic','Biến thời gian t trong CUBIC là gì?|What is time t in CUBIC?','Thời gian từ loss/congestion event gần nhất|Elapsed time since the last loss/congestion event','Tổng số TCP ports|The total TCP port count','Sequence number hiện tại|The current sequence number','SốAS trong AS_PATH|The AS_PATH length');
concept(2,'datacenter','TIMELY dựa đặc trưng nào?|What feedback characterizes TIMELY?','RTT và gradient RTT|RTT and its gradient','MAC table aging|MAC-table aging','BGP LocalPref|BGP LocalPref','Số bridge roots|The number of bridge roots');

concept(3,'routing','Forwarding là tác vụ nào?|Which task is forwarding?','Dùng FIB chuyển packet input→output|Use the FIB to move packets input→output','Thiết kế business relationships|Design business relationships','Tính toàn bộ topology mỗi packet|Recompute all topology per packet','Lập user session|Establish a user session');
concept(3,'routing','“Shortest” trong graph được định nghĩa bởi gì?|What defines “shortest” in a cost graph?','Tổng configured edge costs nhỏ nhất|Minimum sum of configured edge costs','Luôn khoảng cách địa lý nhỏ nhất|Always minimum geographic distance','Luôn ítAS nhất|Always fewest ASes','Luôn ít TCP bytes nhất|Always fewest TCP bytes');
concept(3,'dijkstra','N′ trong Dijkstra là gì?|What is N′ in Dijkstra?','Nodes có shortest distances đã finalized|Nodes with finalized shortest distances','Một packet queue|A packet queue','Chỉ neighbors trực tiếp của destination|Only direct destination neighbors','Nodes chưa bao giờ được xem|Nodes never examined');
concept(3,'dijkstra','p(v) cho biết gì?|What does p(v) represent?','Predecessor trên best path tớiv|The predecessor on the best path tov','Luôn first hop từ source|Always the source’s first hop','Loss probability của TCP|TCP loss probability','Port number củaHTTP|HTTP port number');
concept(3,'dijkstra','O(n²) của module đến từ gì?|Why is the module’s Dijkstra O(n²)?','Scan remaining nodes để tìm minimum mỗi vòng|Scanning remaining nodes for the minimum each round','Một TCP SYN có n²bits|A TCP SYN hasn²bits','Mọi link có n²cost|Every link hasn²cost','Bắt n²ASes tham gia|Requiring n²ASes');
concept(3,'dv','DV thường exchange thông tin với ai?|With whom does DV normally exchange information?','Direct neighbors|Direct neighbors','Mọi application users|All application users','Một DNS root duy nhất|One DNS root','Chỉ destination host|Only the destination host');
concept(3,'dv','Asynchronous DV nghĩa gì?|What does asynchronous DV mean?','Không yêu cầu routers cập nhật cùng clock|Routers need not update on one clock','Không được gửi updates|Updates are prohibited','Cần mọi node update đồng thời|All nodes must update simultaneously','Không bao giờ converge|It never converges');
concept(3,'dv','DV cộng hai đại lượng nào?|What two quantities does DV add?','Local neighbor-link cost và neighbor distance|Local neighbor-link cost and neighbor distance','Hai MAC addresses|Two MAC addresses','cwnd và rwnd|cwnd and rwnd','Hai LocalPrefs|Two LocalPrefs');
concept(3,'count','Count-to-infinity bắt nguồn chủ yếu từ gì?|What principally causes count-to-infinity?','Stale mutually dependent distance estimates|Stale mutually dependent distance estimates','TCP byte overflow|TCP byte overflow','DNS cache tăng tuổi|DNS cache aging','IP header quá nhỏ|An undersized IP header');
concept(3,'count','IP TTL có tự sửa DV tables không?|Does IP TTL repair DV tables?','Không, chỉ giới hạn vòng đời data packet|No, it limits data-packet lifetime','Có, nó chạy Bellman–Ford|Yes, it runs Bellman–Ford','Có, nó đổi link cost về0|Yes, it sets link costs to0','Có, nó gửi SACK|Yes, it sends SACK');
concept(3,'poison','Poison reverse gửi∞ cho ai?|To whom is infinity advertised by poison reverse?','Neighbor đang là next hop tới destination đó|The neighbor used as next hop for that destination','Mọi neighbor bất kể route|Every neighbor for every route','Chỉ source application|Only the source application','Không gửi cho ai|Nobody');
concept(3,'poison','Poison reverse bảo đảm gì trong ví dụ?|What does poison reverse address in the example?','Ngăn mutual loop giữa hai neighbors|Prevents the two-neighbor mutual loop','Loại mọi loop độ dài bất kỳ|Eliminates every length of loop','Không bao giờ cần updates|Eliminates all updates','Biến DV thành global map|Turns DV into a global map');
concept(3,'rip','RIP control messages được chở bằng gì?|What carries RIP control messages?','UDP port520|UDP port520','TCP port80|TCP port80','HTTP requests|HTTP requests','Chỉ Ethernet broadcasts không IP|Only Ethernet broadcasts without IP');
concept(3,'rip','Metric16 trong RIP biểu thị gì?|What does RIP metric16 mean?','Unreachable|Unreachable','Best possible path|Best possible path','TTL mặc định|The default TTL','BGP MED thấp nhất|The lowest BGP MED');
concept(3,'ospf','LSDB detailed topology thường có phạm vi gì?|What is the usual scope of detailed OSPF LSDB topology?','Area phù hợp củaLSA|The LSA’s appropriate area','MọiAS trên Internet|Every Internet AS','Mọi TCP flow|Every TCP flow','Chỉ một application|One application');
concept(3,'ospf','Vai trò backbone Area0?|What is the backbone Area0 role?','Nối routing giữa các areas|Connect routing between areas','Chở riêng UDP payload|Carry only UDP payload','Thay toàn bộ BGP policies|Replace all BGP policies','Bầu root Ethernet|Elect an Ethernet root');
concept(3,'ospf-processing','Sau SPF, kết quả ảnh hưởng forwarding bằng cách nào?|How does SPF affect forwarding?','Cài next-hop entries vàoFIB|Install next-hop entries in the FIB','Chỉ đổi HTTP body|Only alter HTTP bodies','Xóa mọi ports|Delete every port','Tăng cwnd trực tiếp|Directly increase cwnd');
concept(3,'ospf-processing','Vì sao SPF được schedule/batch?|Why schedule/batch SPF?','Giảm CPU cost khi nhiều updates|Reduce CPU cost across multiple updates','Vì SPF không có input|Because SPF has no input','Vì data packet luôn tự chọn route|Because data always selects its own route','Để bỏ qua mọi failure|To ignore every failure');
concept(3,'hot-potato','Hot potato dùng tiêu chí gì khi external routes hòa?|What breaks a relevant external-route tie in hot potato routing?','IGP cost tới egress thấp nhất|Lowest IGP cost to egress','Destination MAC lớn nhất|Largest destination MAC','TCP sequence nhỏ nhất|Smallest TCP sequence','Global latency chắc chắn thấp nhất|Guaranteed minimum global latency');
concept(3,'te','Traffic-engineering loop đúng thứ tự?|What is the traffic-engineering loop order?','Measure→model→control|Measure→model→control','Forward→encrypt→DNS|Forward→encrypt→DNS','SYN→FIN→ARP|SYN→FIN→ARP','Root→peer→provider|Root→peer→provider');

concept(4,'ecosystem','AS xác định boundary nào?|What boundary does an AS identify?','Administrative/routing-policy domain|An administrative/routing-policy domain','Luôn một physical building|Always one physical building','Một UDP socket|One UDP socket','Chỉ một subnet /24|Only one /24 subnet');
concept(4,'business','Customer–provider khác peering ở điều gì?|What distinguishes customer-provider transit from typical peering?','Customer trả để mua transit|The customer pays for transit','Provider không bao giờ forward|The provider never forwards','Peers bắt buộc trao toàn Internet routes|Peers must exchange all Internet routes','Mọi relationship đều miễn phí|Every relationship is free');
concept(4,'policy','Typical import preference là gì?|What is the typical import preference?','Customer>peer>provider|Customer>peer>provider','Provider>peer>customer|Provider>peer>customer','Peer>provider>customer|Peer>provider>customer','Chỉ AS_PATH, bỏ business|Only AS_PATH, ignoring business');
concept(4,'policy','Provider-learned route thường export cho ai?|To whom is a provider-learned route normally exported?','Customers|Customers','Mọi providers|All providers','Mọi peers|All peers','Không bao giờ cho customers|Never to customers');
concept(4,'policy','Quảng bá routeP cho neighbor có xu hướng gây gì?|What can advertising P to a neighbor cause?','Neighbor gửi P-bound traffic qua mình|The neighbor sends P-bound traffic through you','Traffic tự đi theo hướng advertisement|Traffic must follow the advertisement direction','Tăng số physical cables|Increase physical cable count','Xóa mọi policy|Delete all policy');
concept(4,'bgp','UPDATE dùng để làm gì?|What does UPDATE do?','Announce/withdraw routes|Announce/withdraw routes','Chở HTTP HTML thayIP|Carry HTML instead of IP','Tăng receive buffer|Increase receive buffers','Bầu STP root|Elect an STP root');
concept(4,'bgp','Thấy ASN mình trong AS_PATH thường làm gì?|What normally happens on seeing one’s own ASN in AS_PATH?','Reject route loop|Reject the looping route','Ưu tiên route ấy|Prefer that route','Giảm MSS|Decrease MSS','Đổi toàn bộ MAC|Change every MAC');
concept(4,'ibgp','iBGP thay thế IGP không?|Does iBGP replace an IGP?','Không, external route distribution khác internal paths|No, external distribution differs from internal paths','Có trong mọiAS|Yes in every AS','Chỉ cần iBGP để biết mọi link cost|iBGP alone learns every link cost','IGP chỉ chạy giữaASes|IGPs only run between ASes');
concept(4,'selection','Route thua LocalPref có thắng lại nhờ IGP thấp không?|Can lower IGP cost rescue a route losing on LocalPref?','Không theo thứ tự module|Not in the module’s order','Có, luôn cộng hai điểm|Yes, always add both scores','Có nếu MAC đẹp hơn|Yes with a better MAC','Có nếu payload lớn|Yes for large payloads');
concept(4,'selection','MED thường được compare giữa routes nào?|Between which routes is MED normally compared?','Từ cùng neighboring AS|Routes from the same neighboring AS','Mọi prefixes khác nhau|All different prefixes','Mọi MAC table entries|All MAC entries','Bất kỳ flowUDP nào|Any UDP flows');
concept(4,'attributes','LocalPref chủ yếu điều khiển gì?|What does LocalPref primarily control?','Outbound exit củaAS đặt nó|The assigning AS’s outbound exit','Inbound bắt neighbor luôn obey|Inbound with mandatory neighbor obedience','Physical link encoding|Physical link encoding','TCP receiver buffer|TCP receiver buffer');
concept(4,'attributes','MED thường ưu tiên giá trị nào?|Which MED value is normally preferred?','Thấp hơn khi compare|Lower when comparable','Cao hơn luôn|Always higher','Bằng TCP port|Equal to TCP port','Bằng ASN mình|Equal to one’s ASN');
concept(4,'risks','Max-prefix nhắm giới hạn gì?|What does max-prefix limit?','Lượng routes nhận theo session|Route count received per session','Payload bytes mỗiTCP ACK|Payload bytes per TCP ACK','Số bits trongMAC|The bits in a MAC','Số app messages chắc chắn nhận|Guaranteed app message count');
concept(4,'risks','Trade-off của flap damping?|What is the flap-damping trade-off?','Giảm churn nhưng có thể suppress route đã tốt lại|Less churn but possible suppression after recovery','Tăng guarantees mọi path|Guaranteed improvement of every path','Luôn giảm RTT về0|Always reduce RTT to0','Loại mọi route leaks tự động|Automatically remove all route leaks');
concept(4,'ixp','Cùng nốiIXP có tự động peer mọi cặp không?|Does IXP attachment automatically peer every pair?','Không, cần routing/policy agreement|No, routing/policy agreement is needed','Có, switch tự đặt LocalPref|Yes, the switch assigns LocalPref','Có, không cần BGP|Yes, no BGP is needed','Có, mọiASN đều giống nhau|Yes, all ASNs are identical');
concept(4,'route-server','RS choZ route từX, data path theo model là gì?|RS gives Z a route from X. What is the data path?','Z→fabric→X|Z→fabric→X','Z→RS→X luôn|Always Z→RS→X','X→RS→Z bắt buộc cho mọi data|Always X→RS→Z for all data','Z không thể forward|Z cannot forward');
concept(4,'route-server','RS import filter kiểm tra gì?|What does an RS import filter check?','Participant được advertise route đó không|Whether the participant may advertise that route','User password của web app|The web app user’s password','Receiver rwnd|The receiver’s rwnd','Checksum UDP payload|The UDP payload checksum');
concept(4,'remote','Vì sao chỉ RTT khó xác định remote peering?|Why is RTT alone insufficient for remote-peering inference?','Multisite topology/path variation gây ambiguity|Multisite topology/path variation causes ambiguity','RTT luôn bằng0|RTT is always0','Không có cách đoRTT|RTT cannot be measured','BGP tự ghi tọa độ chính xác|BGP records exact coordinates');
concept(4,'verification','Path visibility fault nghĩa gì?|What is a path-visibility fault?','Route không được propagate tới router cần biết|A route is not propagated to a router needing it','Packet có payload quá nhỏ|A packet payload is too small','MSS cao hơn1|MSS is greater than1','Không có video stream|No video stream exists');
concept(4,'verification','rcc báo không có faults có bảo đảm tuyệt đối không?|Does a clean rcc result provide an absolute guarantee?','Không, có thể missed faults|No, faults can be missed','Có, nó mô phỏng mọi tương lai|Yes, it simulates all future events','Có, BGP không có state|Yes, BGP is stateless','Có, nó thay router hardware|Yes, it replaces router hardware');

function numeric(n,ch,prompt,value,wrong,why){const distinct=[...new Set(wrong)].filter(v=>v!==value);let candidate=value+1;while(distinct.length<3){if(candidate!==value&&!distinct.includes(candidate))distinct.push(candidate);candidate++}makeQuestion(n,ch,prompt,[value,...distinct.slice(0,3)],why,'Áp dụng có biến thể / Application variant')}
for(let k=0;k<4;k++){
  const p=100+k*75,ht=20,hn=20,hl=14;
  numeric(1,'encapsulation',`Message${p}bytes, TCP header20, IP header20. IP datagram dài bao nhiêu (không options)?|Message${p}bytes with20-byte TCP and IP headers. What is IP datagram length, without options?`,p+40,[p+20,p+54,p],`${p}+20+20=${p+40}bytes; không cộng link header vào IP length.|${p}+20+20=${p+40}bytes; link headers are outside IP length.`);
  numeric(1,'encapsulation',`IP datagram${p}bytes, Ethernet header14 và trailer4; bỏ preamble/gap. Frame dài bao nhiêu?|IP datagram${p}bytes, Ethernet header14 and trailer4; ignore preamble/gap. Frame length?`,p+18,[p+14,p,p+40],`Frame=${p}+14+4=${p+18}bytes; payload ở đây là toàn IP datagram.|Frame=${p}+14+4=${p+18}bytes; the payload is the complete IP datagram.`);
  const nodes=5+k*2,edges=nodes+3;
  numeric(1,'stp',`Đồ thị point-to-point liên thông có${nodes}bridges. Cây forwarding có bao nhiêu edges?|A connected point-to-point graph has${nodes}bridges. How many edges are in a forwarding tree?`,nodes-1,[nodes,nodes+1,nodes*(nodes-1)/2],`Cây liên thông không cycle cóV−1=${nodes-1}edges. Không phải mọi physical edge đều active.|A connected acyclic tree hasV−1=${nodes-1}edges. Physical edges can remain blocked.`);
  numeric(1,'stp',`${nodes}bridges và${edges}physical edges, cây point-to-point sauSTP cần bao nhiêu edges không active?|${nodes}bridges and${edges}physical edges: how many edges are inactive after a point-to-point spanning tree?`,edges-(nodes-1),[edges-nodes,nodes-1,edges],`${edges}−(${nodes}−1)=${edges-nodes+1}. Đếm edges, không đếm tổng blocked ports trong mọi topology.|${edges}−(${nodes}−1)=${edges-nodes+1}. This counts edges, not blocked ports in arbitrary LAN models.`);
  const ids=[12+k,5+k,30+k,20+k];numeric(1,'stp',`IDs ${ids.join(',')}; cùngpriority, root theo mô hình nhỏ nhất là ai?|IDs${ids.join(',')}, equal priority: which ID becomes root in the minimum-ID model?`,ids[1],[ids[0],ids[2],ids[3]],`Minimum bridgeID=${ids[1]}. Root không chọn theo độ lớn topology hay thứ tự gửi trước.|Minimum bridgeID=${ids[1]}; topology size or first transmission does not determine the root.`);
  numeric(1,'stp',`Neighbor quảng bá root-distance${k+2}; link cost1. Candidate distance của mình?|A neighbor advertises root-distance${k+2}over a cost1 link. What is your candidate distance?`,k+3,[k+2,k+1,k+4],`Candidate=${k+2}+1=${k+3}. Distance trong message là của sender.|Candidate=${k+2}+1=${k+3}; the advertised distance belongs to the sender.`);
  const ports=4+k;numeric(1,'bridges',`Switch${ports}forwarding ports, unknown unicast vào1port. Flood bao nhiêu output ports?|A switch with${ports}forwarding ports receives unknown unicast on one port. How many outputs are flooded?`,ports-1,[ports,1,0],`Flood trừ ingress:${ports}−1=${ports-1}; giả định các ports còn lại đều forwarding.|Flood excluding ingress:${ports}−1=${ports-1}, assuming all other ports forward.`);
  const dest=['B','C','D','E'][k];makeQuestion(1,'bridges',`Đã học${dest}→p${k+2}; frame từA vàop1 tới${dest}. Output nào?|Learned${dest}→p${k+2}; A’s frame entersp1 for${dest}. Which output?`,[`p${k+2}`,'Mọi port trừp1|All exceptp1','Chỉp1|Onlyp1','Không port vì đã known|None because it is known'],`Known unicast tra destination và dùngp${k+2}; học source vẫn xảy ra trước.|Known unicast uses destination portp${k+2}; source learning still occurs.`,'Application variant');
  const privatePort=3300+k,publicPort=5001+k;makeQuestion(1,'nat',`Mapping10.0.0.${k+2}:${privatePort}↔203.0.113.9:${publicPort}. Reply về public tuple được giao đâu?|Mapping10.0.0.${k+2}:${privatePort}↔203.0.113.9:${publicPort}. Where is a reply delivered?`,[`10.0.0.${k+2}:${privatePort}`,`10.0.0.${k+2}:${publicPort}`,`203.0.113.9:${privatePort}`,'Mọi private hosts|Every private host'],`Tra cả mapping: restore private IP và private port, không giữ public translated port.|Use the mapping to restore both the private IP and port, not the translated public port.`,'Application variant');
  const layers=[['HTTP','Application','Network','Data link','Physical'],['TCP','Transport','Application','Network','Physical'],['IP','Network','Transport','Data link','Presentation'],['Ethernet','Data link','Network','Transport','Session']][k];makeQuestion(1,'lower',`${layers[0]} thuộc layer nào trong Internet model?|Which Internet-model layer contains${layers[0]}?`,layers.slice(1),`Phân loại theo trách nhiệm:${layers[0]}→${layers[1]}. Tên đơn vị và scope của layer giúp kiểm tra đáp án.|Classify by responsibility:${layers[0]}→${layers[1]}. Use data units and scope to check the answer.`,'Application variant');

  const seq=1000+k*700,len=300+k*100;numeric(2,'ack',`Mọi byte trước${seq}đã nhận; seq${seq},length${len}đến liên tục. ACK?|All bytes before${seq}are received; seq${seq},length${len}arrives contiguously. ACK?`,seq+len,[seq+len-1,seq+1,len],`ACK=seq+length=${seq+len}, byte kế tiếp mong đợi, không phải byte cuối.|ACK=seq+length=${seq+len}, the next expected byte, not the last received byte.`);
  numeric(2,'handshake',`SYN khôngdata seq${seq}. Server ACK số nào?|A data-free SYN has seq${seq}. What does the server acknowledge?`,seq+1,[seq,seq+len,1],`SYN chiếm1sequence number nên ACK=${seq+1}.|SYN consumes one sequence number, so ACK=${seq+1}.`);
  const buf=8000+k*1000,occ=3000+k*500;numeric(2,'flow',`Buffer${buf}bytes, occupied${occ}. rwnd?|Buffer${buf}bytes with${occ}occupied. rwnd?`,buf-occ,[buf+occ,buf,occ],`rwnd=RcvBuffer−occupied=${buf}−${occ}=${buf-occ}.|rwnd=RcvBuffer−occupied=${buf}−${occ}=${buf-occ}.`);
  const cw=6000+k*1000,rw=9000+k*500,out=4000;numeric(2,'cwnd',`cwnd${cw},rwnd${rw},outstanding${out}bytes. Gửi thêm tối đa?|cwnd${cw},rwnd${rw},outstanding${out}bytes. Maximum new sending?`,Math.min(cw,rw)-out,[Math.min(cw,rw),Math.max(cw,rw)-out,cw+rw-out],`Allowance=max(0,min(${cw},${rw})−${out})=${Math.min(cw,rw)-out}bytes.|Allowance=max(0,min(${cw},${rw})−${out})=${Math.min(cw,rw)-out}bytes.`);
  numeric(2,'reno',`Slow start từ1MSS, threshold chưa chạm, mỗi segment được ACK. Sau${k+2}RTTs,cwnd?|Slow start from1MSS, threshold not reached, every segment ACKed. cwnd after${k+2}RTTs?`,2**(k+2),[k+3,2**(k+1),2**(k+3)],`Mô hình double mỗiRTT:1×2^${k+2}=${2**(k+2)}MSS.|The model doubles each RTT:1×2^${k+2}=${2**(k+2)}MSS.`);
  const w=10+k*3;numeric(2,'reno',`Congestion avoidance,cwnd${w}MSS. Khôngloss sau3RTTs,cwnd≈?|Congestion avoidance starts at${w}MSS. No loss over3RTTs. cwnd≈?`,w+3,[w*8,w+1,w/2],`Additive increase≈1MSS/RTT nên${w}+3=${w+3}, không double.|Additive increase≈1MSS/RTT gives${w}+3=${w+3}, not doubling.`);
  const window=10000+k*5000;numeric(2,'cwnd',`W=${window}bytes,RTT0.1s, khônglimit khác. Rate bao nhiêu bytes/s?|W=${window}bytes,RTT0.1s, no other limits. Rate in bytes/s?`,window*10,[window,window*100,window/10],`Rate≈W/RTT=${window}/0.1=${window*10}bytes/s. Đơn vị không phải bits/s.|Rate≈W/RTT=${window}/0.1=${window*10}bytes/s, not bits/s.`);
  const factor=[4,9,16,25][k],div=Math.sqrt(factor);makeQuestion(2,'throughput',`Loss probability tăng${factor}lần, MSS/RTT không đổi. Rate theo model thay thế nào?|Loss probability grows${factor}times with fixedMSS/RTT. How does model throughput change?`,[`Giảm${div}lần|Decreases${div}-fold`,`Giảm${factor}lần|Decreases${factor}-fold`,`Tăng${div}lần|Increases${div}-fold`,'Không đổi|Unchanged'],`BW∝1/√p, nên ratio=1/√${factor}=1/${div}.|BW∝1/√p, so the ratio is1/√${factor}=1/${div}.`,'Application variant');
  const flows=5+k,owned=2;makeQuestion(2,'fairness',`${flows}flows chia đềuR; một app sở hữu${owned}flows. App được fraction nào?|${flows}flows equally shareR; one app owns${owned}flows. What is its share?`,[`2/${flows}`,`1/${flows}`,`1/${flows-1}`,'Toàn bộR|All ofR'],`Share=${owned}×R/${flows}; per-flow khác per-app fairness.|Share=${owned}×R/${flows}; per-flow and per-app fairness differ.`,'Application variant');
  numeric(2,'udp',`UDP payload${p}bytes. UDP length gồm header là bao nhiêu?|UDP payload${p}bytes. What is UDP length including its header?`,p+8,[p,p+20,p+28],`Header UDP8bytes, length=${p}+8=${p+8}; IP header nằm ngoài.|UDP’s header is8bytes, so length=${p}+8=${p+8}; IP headers are outside.`);

  const a=2+k,b=5+k,cost=a+2;numeric(3,'routing',`A→B cost${a},B→C cost2,A→C cost${b+4}. Least costA→C?|A–B costs${a},B–C2,A–C${b+4}. Least costA→C?`,cost,[b+4,a,b+6],`QuaB=${a}+2=${cost}, nhỏ hơn direct${b+4}.|ViaB costs${a}+2=${cost}, below direct${b+4}.`);
  numeric(3,'dijkstra',`D(v)=${9+k},D(w)=${3+k},c(w,v)=2. Relax cho D(v) mới?|D(v)=${9+k},D(w)=${3+k},c(w,v)=2. New D(v) after relaxation?`,5+k,[9+k,3+k,11+k],`min(${9+k},${3+k}+2)=${5+k}. p(v) đổi thànhw khi cải thiện.|min(${9+k},${3+k}+2)=${5+k}; improving the cost also sets p(v)=w.`);
  numeric(3,'dv',`X→A link${a},A báo đếnD cost3; X→B link${b},B báo cost4. Dx(D)?|X–A costs${a},A advertisesD=3; X–B costs${b},B advertisesD=4. Dx(D)?`,a+3,[3,b+4,a],`min(${a}+3,${b}+4)=${a+3}; phải cộng local link.|min(${a}+3,${b}+4)=${a+3}; include the local link cost.`);
  numeric(3,'dv',`DirectX→D=${a}; neighborN cost2 báoD=${b}. Dx(D)?|DirectX–D=${a}; neighborN costs2 and advertisesD=${b}. Dx(D)?`,a,[b+2,b,a+2],`Direct${a} rẻ hơn2+${b}; không phải cứ nhận advertisement là đổi next hop.|Direct${a} is cheaper than2+${b}; a new advertisement need not change the next hop.`);
  numeric(3,'rip',`RIP neighbor báo metric${4+k}. Qua một link local, candidate metric?|A RIP neighbor advertises metric${4+k}. What is the metric through one local hop?`,5+k,[4+k,3+k,16],`RIP cộng1hop:${4+k}+1=${5+k}, vẫn dưới infinity16.|RIP adds one hop:${4+k}+1=${5+k}, still below infinity16.`);
  const size=4+k;numeric(3,'dijkstra',`Naive minimum scans(n−1)+…+1 với n=${size}. Tổng số scans đơn vị?|For n=${size}, naive selection scans(n−1)+…+1. What is the total?`,size*(size-1)/2,[size*size,size*(size+1)/2,size-1],`n(n−1)/2=${size*(size-1)/2}; asymptoticallyO(n²).|n(n−1)/2=${size*(size-1)/2}; asymptoticallyO(n²).`);
  const letters=[['A','B','C','D'],['P','Q','R','S'],['U','V','W','Z'],['H','J','K','M']][k];makeQuestion(3,'dijkstra',`Shortest path${letters.join('→')}. Next hop từ${letters[0]}tới${letters[3]}?|Shortest path${letters.join('→')}. Next hop from${letters[0]}to${letters[3]}?`,[letters[1],letters[2],letters[3],letters[0]],`Next hop là node đầu sau source:${letters[1]}; predecessor của destination là${letters[2]}, không phải next hop.|The first node after the source is${letters[1]}; destination predecessor${letters[2]}is not the source’s next hop.`,'Application variant');
  makeQuestion(3,'poison',`A tới prefixP${k}quaB cost${7+k}. A báo cost gì choB với poison reverse?|A reachesP${k}throughB at cost${7+k}. What does A advertise toB with poison reverse?`,['∞',7+k,0,8+k],`A giữ finite${7+k}để forwarding nhưng quảng bá∞ về next hopB cho destination đó.|A keeps finite${7+k}for forwarding but advertises∞ back toB for that destination.`,'Application variant');
  makeQuestion(3,'hot-potato',`External routes hòa; egressE1 IGP${9+k},E2 IGP${5+k}. Chọn exit?|External routes tie;E1 IGP${9+k},E2 IGP${5+k}. Choose the exit.`,['E2','E1','Luôn source router|Always the source router','Không thể dùng IGP|IGP cannot be used'],`E2 có cost nội bộ thấp hơn. Các BGP criteria trước được giả định hòa.|E2 has lower internal cost; earlier BGP criteria are assumed tied.`,'Application variant');
  numeric(3,'routing',`Path link costs${k+1},3,2. Total cost?|Path link costs${k+1},3,2. Total cost?`,k+6,[3,k+1,k+5],`Cộng edges:${k+1}+3+2=${k+6}. Không lấy max edge hay chỉ đếm3hops.|Sum edges:${k+1}+3+2=${k+6}, rather than max edge or simply3hops.`);

  const nn=5+k;numeric(4,'ibgp',`${nn}BGP routers iBGP full mesh: sessions?|${nn}BGP routers in an iBGP full mesh: sessions?`,nn*(nn-1)/2,[nn,nn*(nn-1),nn-1],`Unordered pairs n(n−1)/2=${nn*(nn-1)/2}; logical sessions.|Unordered pairs n(n−1)/2=${nn*(nn-1)/2}; these are logical sessions.`);
  numeric(4,'route-server',`${nn}participants từall-pairs chuyển sang mộtRS, mỗiAS1session. Giảm bao nhiêu sessions?|${nn}participants change from all-pairs to oneRS, one session per AS. How many sessions are saved?`,nn*(nn-1)/2-nn,[nn*(nn-1)/2,nn,nn-1],`All-pairs=${nn*(nn-1)/2}; RS=${nn}; saved=${nn*(nn-1)/2-nn}. Giả định mộtRS, không redundancy.|All-pairs=${nn*(nn-1)/2}; RS=${nn}; saved=${nn*(nn-1)/2-nn}, assuming one nonredundant RS.`);
  makeQuestion(4,'selection',`Cùngprefix: A LocalPref${300+k},path5; B LocalPref200,path2. Chọn?|Same prefix:A LocalPref${300+k},path5;B LocalPref200,path2. Winner?`,['A','B','Cộng LocalPref vớipath|Add LocalPref and path','Luôn chọn cả hai|Always choose both'],`A thắng LocalPref trước khi xét path length. B ngắn hơn không cứu được nó.|A wins on LocalPref before path length; B’s shorter path cannot rescue it.`,'Application variant');
  makeQuestion(4,'selection',`Cùngprefix vàLocalPref: A AS_PATH${5+k}hops, B${2+k}hops. Chọn?|Same prefix andLocalPref:A AS_PATH${5+k}hops,B${2+k}hops. Winner?`,['B','A','Chọn routerID trước|Compare router ID first','Không compare được AS_PATH|AS_PATH cannot be compared'],`B có AS_PATH ngắn hơn và thắng ở criterion đó; chưa xét các tiêu chí sau.|B has the shorter AS_PATH and wins there before later criteria.`,'Application variant');
  makeQuestion(4,'attributes',`Cùngneighbor AS, criteria trước hòa: MEDA=${50+k},MEDB=${10+k}. Chọn?|Same neighbor AS and tied earlier criteria:MEDA=${50+k},MEDB=${10+k}. Winner?`,['B','A','Luôn MED lớn hơn|Always higher MED','Luôn bỏ qua MED|Always ignore MED'],`MED thấp hơn được ưu tiên khi comparable:${10+k}<${50+k}.|Lower comparable MED wins:${10+k}<${50+k}.`,'Application variant');
  makeQuestion(4,'selection',`TrướcIGP hòa: routeA cost${4+k},B cost${9+k}. Chọn?|Tied beforeIGP:routeA costs${4+k},B${9+k}. Winner?`,['A','B','AS_PATH tự tăng|AS_PATH automatically increases','Không route nào|Neither route'],`A thắng IGP cost (hot potato) vì các criteria trước hòa.|A wins the IGP-cost hot-potato criterion after earlier ties.`,'Application variant');
  makeQuestion(4,'policy',`PrefixP${k}: customer path5,peer path2,provider path1; typical import policy. Chọn source?|ForP${k}:customer path5,peer path2,provider path1 under typical import policy. Preferred source?`,['Customer','Peer','Provider','Chỉ dùng default luôn|Always only default'],`Customer preference được encode trước path length. Path dài hơn vẫn có thể thắng policy.|Customer preference precedes path length, so a longer customer route can win.`,'Application variant');
  const relations=[['peer','provider',false],['provider','customer',true],['customer','peer',true],['provider','peer',false]][k];makeQuestion(4,'policy',`Học từ${relations[0]}, export sang${relations[1]}. Typical policy?|Learned from${relations[0]}, export to${relations[1]}. Typical policy?`,[relations[2]?'Cho phép|Allow':'Chặn|Block',relations[2]?'Chặn|Block':'Cho phép|Allow','Chỉ dựa MSS|Depends only on MSS','Chỉ dựa checksum|Depends only on checksum'],`Customer routes có thể export rộng; peer/provider routes chỉ sang customers. Áp đúng hàng/cột matrix.|Customer routes can export broadly; peer/provider routes go only to customers. Apply the corresponding matrix row/column.`,'Application variant');
  const as=65001+k;makeQuestion(4,'bgp',`AS${as}học path[65100,65200] quaeBGP rồi export eBGP thông thường. Path mới?|AS${as}learns[65100,65200]and normally exports over eBGP. New path?`,[`[${as},65100,65200]`,`[65100,65200,${as}]`,'[65100,65200]','[]'],`Normal eBGP advertisement prepend ownASN vào đầu AS_PATH, không đổi thứ tự path cũ.|Normal eBGP advertisement prepends the local ASN, retaining the previous path order.`,'Application variant');
  const base=10+k*5;numeric(4,'business',`20samples sorted:${base}đến${base+19}Mbps, mỗi số1lần. Bỏ highest5%(1sample), lấymax còn lại. Billing rate?|20sorted samples:${base}through${base+19}Mbps, each once. Discard highest5%(one sample), take remaining max. Billing rate?`,base+18,[base+19,base+10,base],`Theo convention đề, bỏ${base+19}; cao nhất còn lại${base+18}. Không lấy peak ban đầu hay average.|Under the stated convention, discard${base+19}; the remaining maximum is${base+18}, not the original peak or average.`);
}

/* Lessons 5–12: 15 source-grounded concepts × 4 retrieval angles = 60 original items per lesson. */
function buildConceptPractice(n,concepts){
  const pick=(i,field)=>[concepts[i],concepts[(i+3)%concepts.length],concepts[(i+7)%concepts.length],concepts[(i+11)%concepts.length]].map(x=>x[field]);
  concepts.forEach((x,i)=>{
    const chapter=COURSE.find(c=>c.lesson===n&&c.id===x.chapter),why=[`${x.term[0]}: ${x.key[0]} ${chapter.intro[0]}`,`${x.term[1]}: ${x.key[1]} ${chapter.intro[1]}`];
    makeQuestion(n,x.chapter,[`Định nghĩa đúng nhất của “${x.term[0]}” là gì?`,`What best defines “${x.term[1]}”?`],pick(i,'key'),why,'Nhận diện / Recognition',chapter.pitfall);
    makeQuestion(n,x.chapter,x.scene,pick(i,'term'),why,'Tình huống / Scenario',chapter.pitfall);
    makeQuestion(n,x.chapter,[`Trong reasoning về ${x.term[0]}, kết luận nào đúng?`,`Which conclusion is correct when reasoning about ${x.term[1]}?`],pick(i,'key'),why,'Phân biệt / Distinction',chapter.pitfall);
    makeQuestion(n,x.chapter,[`${x.scene[0]} Cơ chế nào giải thích trực tiếp nhất?`,`${x.scene[1]} Which mechanism explains it most directly?`],pick(i,'term'),why,'Ứng dụng / Application',chapter.pitfall);
  });
}
const C=(chapter,vi,en,kvi,ken,svi,sen)=>({chapter,term:[vi,en],key:[kvi,ken],scene:[svi,sen]});

buildConceptPractice(5,[
 C('l5-pipeline','Data plane fast path','Data-plane fast path','Tra FIB, switch, queue và transmit từng packet bằng installed state.','Look up the FIB, switch, queue, and transmit each packet using installed state.','Router đã có FIB đúng và đang xử lý packet ở line rate.','A router has a correct FIB and is processing a packet at line rate.'),
 C('l5-pipeline','Control plane','Control plane','Tính, duy trì và cài forwarding state ở nhịp chậm hơn.','Compute, maintain, and install forwarding state at a slower timescale.','OSPF nhận link-state update rồi recompute routes.','OSPF receives a link-state update and recomputes routes.'),
 C('l5-pipeline','Output queue','Output queue','Hấp thụ burst khi packet tới nhanh hơn output link tạm thời phục vụ.','Absorb bursts when packets temporarily arrive faster than the output link serves.','Ba input cùng nhắm một output đang bận.','Three inputs target one busy output.'),
 C('l5-switching','Memory switching','Memory switching','Mỗi packet được write rồi read qua shared memory, nên memory bandwidth giới hạn throughput.','Each packet is written and read through shared memory, so memory bandwidth bounds throughput.','Fabric cần hai memory transfers cho mỗi packet.','The fabric needs two memory transfers per packet.'),
 C('l5-switching','Shared bus','Shared bus','Chỉ một packet dùng internal bus tại một thời điểm.','Only one packet uses the internal bus at a time.','Outputs rảnh nhưng hai inputs vẫn tranh cùng backplane.','Outputs are idle but two inputs still contend for one backplane.'),
 C('l5-switching','Crossbar parallelism','Crossbar parallelism','Nhiều transfers chạy cùng slot nếu không chung input hoặc output.','Multiple transfers run in one slot if they share neither input nor output.','A→Y và B→X chạy đồng thời, A→Y và B→Y thì không.','A→Y and B→X run together, while A→Y and B→Y cannot.'),
 C('l5-lpm','Longest-prefix match','Longest-prefix match','Trong các prefixes cùng match destination, chọn prefix có nhiều leading bits nhất.','Among prefixes matching a destination, select the one with the most leading bits.','/8, /16 và /24 cùng match một địa chỉ.','A /8, /16, and /24 all match one address.'),
 C('l5-lpm','CIDR','CIDR','Dùng prefix độ dài tùy ý để aggregate address space thay fixed classes.','Use arbitrary-length prefixes to aggregate address space instead of fixed classes.','Một organization được cấp 203.0.113.0/24.','An organization receives 203.0.113.0/24.'),
 C('l5-unibit','Best-so-far trong trie','Trie best-so-far','Giữ prefix hợp lệ sâu nhất đã gặp rồi trả nó khi path fail.','Remember the deepest valid prefix and return it when the path fails.','Search đi qua prefix /8 rồi gặp empty child ở sâu hơn.','A search passes a valid /8 and later hits an empty child.'),
 C('l5-unibit','Unibit trie','Unibit trie','Đọc một address bit mỗi level, worst case tới address width accesses.','Consume one address bit per level, with worst case up to the address width in accesses.','IPv4 lookup có thể cần 32 node visits.','An IPv4 lookup may require 32 node visits.'),
 C('l5-unibit','Path compression','Path compression','Nén chuỗi one-way nodes thành bit string để giảm nodes/accesses.','Compress a chain of one-way nodes into a bit string to reduce nodes and accesses.','Một prefix path dài không có nhánh trong nhiều levels.','A long prefix path has no branch for many levels.'),
 C('l5-multibit','Stride','Stride','Số address bits được đọc ở mỗi multibit trie node.','The number of address bits consumed at each multibit-trie node.','Node stride3 có tới tám child choices.','A stride-3 node has up to eight child choices.'),
 C('l5-multibit','Controlled prefix expansion','Controlled prefix expansion','Mở prefix tới stride boundary bằng mọi missing-bit combinations.','Extend a prefix to a stride boundary with every missing-bit combination.','Prefix 101* phải nằm trong table stride2 ở boundary4.','Prefix 101* must fit a stride-2 table at boundary4.'),
 C('l5-multibit','Variable-stride trie','Variable-stride trie','Chọn stride khác theo node để cân memory với accesses.','Choose a different stride per node to balance memory and accesses.','Nhánh sparse cần2 bits, nhánh dense cần3 bits.','A sparse branch needs2 bits while a dense branch needs3.'),
 C('l5-design','Pipeline bottleneck','Pipeline bottleneck','Stage bão hòa đầu tiên giới hạn sustainable router throughput.','The first saturated stage limits sustainable router throughput.','LPM1ns nhưng shared bus thấp hơn aggregate input rate.','LPM takes1ns, but the shared bus is slower than aggregate input rate.')
]);

buildConceptPractice(6,[
 C('l6-classification','Packet classification','Packet classification','Match nhiều header fields để chọn policy action, không chỉ output theo destination.','Match multiple header fields to select a policy action, not just an output by destination.','Firewall dùng source, destination, ports và TCP flags.','A firewall uses source, destination, ports, and TCP flags.'),
 C('l6-classification','Linear rule search','Linear rule search','Kiểm rules tuần tự, đơn giản nhưng miss cost tăng O(N).','Check rules sequentially; simple, but miss cost grows O(N).','Một miss phải đọc cả10,000-rule ACL.','A miss must read an entire10,000-rule ACL.'),
 C('l6-classification','Edge classification with labels','Edge classification with labels','Classify một lần ở ingress rồi core dùng MPLS label hoặc DiffServ mark.','Classify once at ingress, then let the core use an MPLS label or DiffServ mark.','Core routers tránh lặp multidimensional lookup.','Core routers avoid repeating multidimensional lookups.'),
 C('l6-tries','Set-pruning trie','Set-pruning trie','Replicate compatible source rules dưới destination nodes để lookup nhanh hơn nhưng tốn memory.','Replicate compatible source rules under destination nodes for faster lookup at high memory cost.','Một source prefix xuất hiện trong nhiều destination subtries.','One source prefix appears in many destination subtries.'),
 C('l6-tries','Backtracking classifier','Backtracking classifier','Lưu rule một lần rồi thử source tries ở destination ancestors khi fail.','Store a rule once and try source tries at destination ancestors after failure.','Longest destination node không có source match.','The longest destination node has no source match.'),
 C('l6-tries','Grid switch pointer','Grid switch pointer','Precompute jump tới next viable source trie thay vì retraverse ancestors.','Precompute a jump to the next viable source trie instead of retraversing ancestors.','Source-trie lookup fail và đi thẳng node X.','A source-trie lookup fails and jumps directly to node X.'),
 C('l6-hol','Head-of-line blocking','Head-of-line blocking','Head chờ busy output chặn packets sau dù outputs của chúng rảnh.','A head packet waiting for a busy output blocks later packets whose outputs are idle.','Single input FIFO bắt đầu bằng packet tới output1 đang bận.','A single input FIFO begins with a packet for busy output1.'),
 C('l6-hol','Virtual output queue','Virtual output queue','Mỗi input tách một queue cho mỗi output để lộ eligible packets.','Each input separates one queue per output to expose eligible packets.','Packet tới output3 vẫn đi dù VOQ1 bị nghẽn.','A packet for output3 proceeds while VOQ1 is congested.'),
 C('l6-matching','Request–grant–accept','Request–grant–accept','Tạo conflict-free crossbar matching bằng local iterative choices.','Build a conflict-free crossbar matching through iterative local choices.','Mỗi output grant một input và mỗi input accept một output.','Each output grants one input and each input accepts one output.'),
 C('l6-matching','Valid matching','Valid matching','Mỗi input và output xuất hiện tối đa một lần trong slot.','Each input and output appears at most once in a slot.','A scheduler đề xuất A→1, B→2, C→4 cùng lúc.','A scheduler proposes A→1, B→2, C→4 simultaneously.'),
 C('l6-drr','Bit-by-bit fair queueing','Bit-by-bit fair queueing','Dùng virtual finish round để mô phỏng chia bandwidth theo bits.','Use virtual finish rounds to emulate bit-level bandwidth sharing.','Scheduler chọn head packet có F nhỏ nhất.','A scheduler chooses the head packet with the smallest F.'),
 C('l6-drr','Deficit Round Robin','Deficit Round Robin','Thêm quantum mỗi lượt và carry unused byte credit khi queue còn backlogged.','Add a quantum each visit and carry unused byte credit while a queue remains backlogged.','Packet750 chờ lượt sau với deficit300 và quantum500.','A750-byte packet waits for the next visit with deficit300 and quantum500.'),
 C('l6-token','Token bucket','Token bucket','Rate R giới hạn average, capacity B cho accumulated burst credit.','Rate R limits the average and capacity B permits accumulated burst credit.','Flow idle rồi gửi burst bằng số tokens đã tích.','A flow idles and then sends a burst using accumulated tokens.'),
 C('l6-leaky','Traffic shaping','Traffic shaping','Buffer excess để gửi sau, đổi loss lấy delay.','Buffer excess for later transmission, trading loss for delay.','Packet vượt profile chờ đến khi có token.','An out-of-profile packet waits until a token is available.'),
 C('l6-leaky','Traffic policing','Traffic policing','Drop hoặc remark excess ngay để enforce contract không queue chờ.','Drop or remark excess immediately to enforce a contract without a waiting queue.','Packet tới khi bucket không còn credit bị đánh dấu thấp.','A packet arriving with no bucket credit is marked down.')
]);

buildConceptPractice(7,[
 C('l7-motivation','Device diversity problem','Device diversity problem','Nhiều boxes/protocols/interfaces làm box-by-box management khó tự động hóa.','Many boxes, protocols, and interfaces make box-by-box management hard to automate.','Policy phải cấu hình router, firewall, NAT và load balancer khác nhau.','A policy must configure different routers, firewalls, NATs, and load balancers.'),
 C('l7-motivation','Logical centralization','Logical centralization','Cung cấp một control authority/view dù implementation có nhiều servers.','Provide one control authority and view even when implemented by many servers.','Apps thấy một controller service trên cluster ba nodes.','Applications see one controller service on a three-node cluster.'),
 C('l7-history','Active networking','Active networking','Cho code programmable chạy trong network nodes, scope tham vọng nhưng deployment khó.','Let programmable code run in network nodes; ambitious in scope but hard to deploy.','Capsule mang code in-band trong packet.','A capsule carries code in-band in a packet.'),
 C('l7-history','Control/data separation era','Control/data separation era','Đưa route control ra server qua open interface để operator có network-wide control.','Move route control to servers through an open interface for network-wide operator control.','ISP muốn traffic engineering mà không đổi forwarding ASIC.','An ISP wants traffic engineering without replacing forwarding ASICs.'),
 C('l7-history','OpenFlow rule model','OpenFlow rule model','Pattern, priority, actions và counters tạo deployable programmable interface.','A pattern, priority, actions, and counters form a deployable programmable interface.','Switch firmware cho testbed cài experimental flow rules.','Switch firmware lets a testbed install experimental flow rules.'),
 C('l7-planes','Data plane','Data plane','Thực hiện local per-packet match/action ở fast timescale.','Execute local per-packet match-action at a fast timescale.','Switch forward packet theo installed output rule.','A switch forwards a packet according to an installed output rule.'),
 C('l7-planes','Control plane','Control plane','Tính paths/policies và phân phối forwarding state.','Compute paths and policies and distribute forwarding state.','Controller recompute path sau link failure.','A controller recomputes a path after a link failure.'),
 C('l7-planes','Management plane','Management plane','Cho operator định intent, config và monitoring lifecycle.','Let operators define intent, configuration, and monitoring lifecycle.','Admin đặt policy không cho guest tới finance subnet.','An administrator sets a policy denying guest access to a finance subnet.'),
 C('l7-architecture','Flow-based forwarding','Flow-based forwarding','Match fields across layers thay vì chỉ destination IP.','Match fields across layers instead of only destination IP.','Rule match VLAN, source, TCP port và forward queue5.','A rule matches VLAN, source, TCP port, and forwards to queue5.'),
 C('l7-architecture','Network-control application','Network-control application','Đọc abstract state và tính desired network behavior.','Read abstract state and compute desired network behavior.','Traffic-engineering app chạy constrained shortest path.','A traffic-engineering app runs a constrained shortest path.'),
 C('l7-controller','Southbound interface','Southbound interface','Nối controller với controlled devices cho events, stats và commands.','Connect the controller to controlled devices for events, statistics, and commands.','Switch gửi port-down, controller gửi flow-mod.','A switch sends port-down and a controller sends flow-mod.'),
 C('l7-controller','Northbound interface','Northbound interface','Cho applications đọc/write controller abstractions và subscribe events.','Let applications read or write controller abstractions and subscribe to events.','Routing app hỏi topology graph qua API.','A routing app requests a topology graph through an API.'),
 C('l7-controller','Network-wide state','Network-wide state','Lưu hosts, links, switches, counters và installed/desired rules.','Store hosts, links, switches, counters, and installed or desired rules.','Controller database cập nhật host mới và link load.','A controller database updates a new host and link load.'),
 C('l7-odl','Configuration datastore','Configuration datastore','Lưu intended persistent configuration, chưa chứng minh device đã converge.','Store intended persistent configuration without proving device convergence.','RESTCONF PUT ghi desired flow.','A RESTCONF PUT writes a desired flow.'),
 C('l7-odl','Operational datastore','Operational datastore','Phản ánh current observed state do managed devices báo.','Reflect current observed state reported by managed devices.','App đọc port thực tế đang down.','An application reads that a port is actually down.')
]);

buildConceptPractice(8,[
 C('l8-landscape','Network virtualization','Network virtualization','Tạo logical topologies/addressing trên shared physical infrastructure.','Create logical topologies and addressing over shared physical infrastructure.','Hai tenants thấy switches riêng trên cùng fabric.','Two tenants see separate switches on one shared fabric.'),
 C('l8-landscape','Network operating system','Network operating system','Cung cấp shared state, services và abstractions cho control apps.','Provide shared state, services, and abstractions for control applications.','Apps reuse topology and device-management modules.','Applications reuse topology and device-management modules.'),
 C('l8-openflow','Flow entry','Flow entry','Gồm match, priority, action/instruction, counters và lifecycle state.','Contains a match, priority, action or instruction, counters, and lifecycle state.','Packet tăng counter rồi output port3.','A packet increments a counter and exits port3.'),
 C('l8-openflow','Table miss','Table miss','Không rule match; pipeline có thể drop, continue hoặc gửi controller.','No rule matches; the pipeline may drop, continue, or contact the controller.','First packet của unknown flow tạo packet-in.','The first packet of an unknown flow creates a packet-in.'),
 C('l8-openflow','OVSDB','OVSDB','Quản vSwitch instances, interfaces, tunnels, queues và QoS, bổ sung OpenFlow.','Manage virtual-switch instances, interfaces, tunnels, queues, and QoS, complementing OpenFlow.','Controller attach tunnel interface vào Open vSwitch.','A controller attaches a tunnel interface to Open vSwitch.'),
 C('l8-controllers','Physically distributed controller','Physically distributed controller','Scale/failover bằng nhiều nodes nhưng duy trì logical common service.','Scale and fail over with multiple nodes while maintaining one logical service.','Controller nodes ở nhiều data centers replicate state.','Controller nodes in multiple data centers replicate state.'),
 C('l8-controllers','ONOS mastership','ONOS mastership','Mỗi switch có một master controller, backups tiếp quản qua election khi failure.','Each switch has one master controller; backups take over through election after failure.','C1 fail và C2 trở thành master của S1.','C1 fails and C2 becomes master for S1.'),
 C('l8-controllers','Weak consistency','Weak consistency','Cho availability/scale tốt hơn nhưng apps có thể thấy stale controller state.','Improve availability and scale while applications may see stale controller state.','Hai replicas tạm thời có topology versions khác nhau.','Two replicas temporarily hold different topology versions.'),
 C('l8-p4','P4 reconfigurability','P4 reconfigurability','Cho đổi parser và packet-processing pipeline bằng chương trình.','Allow a program to change the parser and packet-processing pipeline.','Switch được thêm custom telemetry header handling.','A switch gains handling for a custom telemetry header.'),
 C('l8-p4','Protocol independence','Protocol independence','Program khai báo headers/parser thay fixed protocol list.','The program declares headers and parsers instead of using a fixed protocol list.','Target parse một new encapsulation do program định nghĩa.','A target parses a new encapsulation defined by the program.'),
 C('l8-p4','Target independence','Target independence','Compiler map một P4 program sang different hardware/software targets.','A compiler maps one P4 program to different hardware or software targets.','Cùng source compile cho ASIC và software switch.','The same source compiles for an ASIC and a software switch.'),
 C('l8-p4','Configure vs populate','Configure versus populate','Configure định pipeline structure; populate đổi concrete table entries.','Configure defines pipeline structure; populate changes concrete table entries.','Thêm route entry không sửa parser.','Adding a route entry does not change the parser.'),
 C('l8-apps','Closed-loop SDN control','Closed-loop SDN control','Observe metrics, decide policy, install rules, verify và repeat.','Observe metrics, decide policy, install rules, verify, and repeat.','DDoS app thấy counters tăng rồi rate-limit ingress.','A DDoS app sees rising counters and rate-limits ingress.'),
 C('l8-sdx','Virtual SDX switch','Virtual SDX switch','Cho mỗi AS viết isolated policy như có switch riêng trên shared IXP fabric.','Let each AS write isolated policy as if it had a private switch on a shared IXP fabric.','AS A steer port80 to B và443 to C.','AS A steers port80 to B and443 to C.'),
 C('l8-sdx','Application-specific peering','Application-specific peering','Chọn peer/path theo application header fields, vượt destination-only BGP.','Choose a peer or path by application header fields beyond destination-only BGP.','Video traffic dùng peer khác web traffic.','Video traffic uses a different peer than web traffic.')
]);

buildConceptPractice(9,[
 C('l9-goals-dns','Confidentiality','Confidentiality','Chỉ authorized parties đọc message content.','Only authorized parties can read message content.','Attacker sniff ciphertext nhưng không hiểu plaintext.','An attacker sniffs ciphertext but cannot read plaintext.'),
 C('l9-goals-dns','Integrity','Integrity','Phát hiện message bị sửa, chèn hoặc xóa.','Detect message modification, insertion, or deletion.','Receiver xác minh data không đổi in transit.','A receiver verifies data was not changed in transit.'),
 C('l9-goals-dns','Authentication','Authentication','Xác minh communicating entity đúng identity đã claim.','Verify that a communicating entity has the identity it claims.','Client kiểm tra server certificate.','A client checks a server certificate.'),
 C('l9-goals-dns','Fast-flux service network','Fast-flux service network','Rapid DNS rotation qua compromised proxies để che và giữ mothership online.','Rapidly rotate DNS through compromised proxies to hide and preserve a mothership.','TTL hết và domain trả tập agents hoàn toàn mới.','A TTL expires and the domain returns an entirely new agent set.'),
 C('l9-reputation','FIRE longevity signal','FIRE longevity signal','Persistent high malicious-IP ratio phân biệt rogue network khỏi transient compromise.','A persistent high malicious-IP ratio distinguishes a rogue network from transient compromise.','Một small AS host phishing nhiều tháng.','A small AS hosts phishing for many months.'),
 C('l9-reputation','ASwatch','ASwatch','Dùng BGP rewiring, prefix churn và routing dynamics để chấm bulletproof-like AS.','Use BGP rewiring, prefix churn, and routing dynamics to score bulletproof-like ASes.','AS đổi upstream liên tục và announce small prefixes ngắn hạn.','An AS changes upstreams frequently and announces small prefixes briefly.'),
 C('l9-hijack','Exact-prefix hijack','Exact-prefix hijack','Attacker và owner announce cùng prefix, tạo competing origins/routes.','An attacker and owner announce the same prefix, creating competing origins or routes.','Hai AS originate cùng /16.','Two ASes originate the same /16.'),
 C('l9-hijack','Subprefix hijack','Subprefix hijack','Attacker announce more-specific prefix để thắng data-plane LPM.','An attacker announces a more-specific prefix to win data-plane LPM.','Owner /16 nhưng attacker announce một /24 bên trong.','The owner has a /16 but an attacker announces an internal /24.'),
 C('l9-hijack','MOAS','MOAS','Cùng prefix được nhiều origin AS announce; có thể legitimate hoặc hijack.','The same prefix is announced by multiple origin ASes and may be legitimate or a hijack.','Monitor thấy origin đổi từ một thành hai AS.','A monitor sees a prefix move from one to two origin ASes.'),
 C('l9-artemis','ARTEMIS','ARTEMIS','So BGP feeds với owner-configured prefixes/origins/paths để detect nhanh và mitigate.','Compare BGP feeds with owner-configured prefixes, origins, and paths for rapid detection and mitigation.','Owner nhận update cho prefix mình với unauthorized origin.','An owner receives an update for its prefix with an unauthorized origin.'),
 C('l9-artemis','Prefix deaggregation mitigation','Prefix deaggregation mitigation','Owner announce more-specific components để LPM kéo traffic lại.','The owner announces more-specific components so LPM pulls traffic back.','Victim /24 announce hai /25 sau hijack.','A victim /24 announces two /25s after a hijack.'),
 C('l9-ddos','Reflection attack','Reflection attack','Spoof victim source trong requests để legitimate responders reply tới victim.','Spoof the victim as request source so legitimate responders reply to the victim.','Bots hỏi một triệu DNS servers bằng victim IP.','Bots query one million DNS servers using the victim IP.'),
 C('l9-ddos','Amplification factor','Amplification factor','Response/request size ratio nhân attacker request bandwidth.','The response-to-request size ratio multiplies attacker request bandwidth.','60-byte query tạo3000-byte response.','A60-byte query creates a3000-byte response.'),
 C('l9-defense','BGP FlowSpec','BGP FlowSpec','Phân phối multi-field traffic matches và drop/rate/redirect actions qua BGP.','Distribute multi-field traffic matches and drop, rate, or redirect actions through BGP.','ISP cài rule chỉ drop UDP11211 tới victim.','An ISP installs a rule dropping only UDP11211 to a victim.'),
 C('l9-blackhole','Remote-triggered blackholing','Remote-triggered blackholing','Community-tagged route làm provider/IXP discard mọi traffic tới attacked prefix.','A community-tagged route makes a provider or IXP discard all traffic to an attacked prefix.','Victim announce /32 với provider:666.','A victim announces a /32 with provider:666.')
]);

buildConceptPractice(10,[
 C('l10-gfw','DNS injection','DNS injection','On-path censor race fake DNS reply cho selected query.','An on-path censor races a fake DNS reply for a selected query.','Client nhận bogus A record trước authoritative answer.','A client receives a bogus A record before the authoritative answer.'),
 C('l10-techniques','IP packet dropping','IP packet dropping','Discard traffic tới blocked IPs; cheap nhưng dễ overblock shared hosts.','Discard traffic to blocked IPs; cheap but prone to overblocking shared hosts.','Hai websites cùng IP đều mất dù chỉ một bị cấm.','Two websites sharing an IP both fail although only one is banned.'),
 C('l10-techniques','DNS poisoning','DNS poisoning','Trả no answer hoặc wrong mapping cho targeted hostname.','Return no answer or a wrong mapping for a targeted hostname.','Resolver trả incorrect IP cho blocked domain.','A resolver returns an incorrect IP for a blocked domain.'),
 C('l10-techniques','Proxy content inspection','Proxy content inspection','Inline reconstruct application content để block page/object precise nhưng costly.','Reconstruct application content inline to block precise pages or objects at high cost.','System cho domain nhưng chặn một URL path.','A system allows a domain but blocks one URL path.'),
 C('l10-techniques','TCP RST injection','TCP RST injection','Forge reset trong valid sequence space để endpoints đóng connection.','Forge a reset in the valid sequence space so endpoints close a connection.','GET chứa keyword và client nhận nhiều RST.','A GET contains a keyword and the client receives multiple RSTs.'),
 C('l10-measure','Vantage diversity','Vantage diversity','Đo nhiều regions/ISPs/times để tránh gắn một path thành whole-country behavior.','Measure many regions, ISPs, and times to avoid treating one path as a whole country.','Hai providers trong cùng country cho results khác nhau.','Two providers in one country produce different results.'),
 C('l10-measure','Intent attribution','Intent attribution','Loại CDN, cache, failure và misconfiguration trước khi gọi anomaly là censorship.','Eliminate CDN, cache, failure, and misconfiguration explanations before labeling an anomaly censorship.','Unexpected DNS IP vẫn có valid certificate/content.','An unexpected DNS IP still has a valid certificate and content.'),
 C('l10-iris','Infrastructure resolver vantage','Infrastructure resolver vantage','Dùng open resolvers trong ISP/cloud thay home devices để scale và giảm user risk.','Use open resolvers in ISP or cloud infrastructure instead of home devices for scale and lower user risk.','Scanner loại likely residential forwarders.','A scanner removes likely residential forwarders.'),
 C('l10-iris','Consistency metric','Consistency metric','So IP, AS, content, cert hoặc PTR patterns across observations.','Compare IP, AS, content, certificate, or PTR patterns across observations.','Một resolver trả AS khác mọi controls.','One resolver returns an AS unlike all controls.'),
 C('l10-iris','Independent verifiability','Independent verifiability','Dùng external evidence như valid domain TLS cert để xác nhận reply.','Use external evidence such as a valid domain TLS certificate to verify a reply.','Outlier IP trình browser-trusted cert đúng hostname.','An outlier IP presents a browser-trusted certificate for the right hostname.'),
 C('l10-disruption','Routing disruption','Routing disruption','Withdraw/change prefixes khiến global control-plane reachability biến mất.','Withdraw or alter prefixes so global control-plane reachability disappears.','Collectors thấy hàng nghìn country prefixes withdrawn.','Collectors see thousands of country prefixes withdrawn.'),
 C('l10-disruption','Data-plane filtering','Data-plane filtering','Routes còn visible nhưng matching packets bị drop.','Routes remain visible while matching packets are dropped.','BGP bình thường nhưng active probes fail.','BGP looks normal but active probes fail.'),
 C('l10-augur','Augur probe','Augur probe','Gửi SYN-ACK tới reflector và đọc RST IPID để sample global counter.','Send SYN-ACK to a reflector and read the RST IPID to sample its global counter.','Measurement machine thấy IPID6 rồi8.','A measurement machine sees IPID6 and then8.'),
 C('l10-augur','Augur perturbation','Augur perturbation','Spoof reflector source tới site để site kích reflector gửi RST và increment IPID.','Spoof the reflector as source toward a site so the site triggers a reflector RST and IPID increment.','Site SYN-ACK tới reflector sau spoofed SYN.','A site sends SYN-ACK to a reflector after a spoofed SYN.'),
 C('l10-ethics','Measurement data minimization','Measurement data minimization','Chỉ probe/log fields cần thiết và bảo vệ identifiers để giảm participant harm.','Probe and log only necessary fields and protect identifiers to reduce participant harm.','Study bỏ raw home IPs và query payload không cần thiết.','A study omits raw home IPs and unnecessary query payloads.')
]);

buildConceptPractice(11,[
 C('l11-media','Stored streaming','Stored streaming','Prefetch recorded content, hỗ trợ seek và continuous playout với large buffer.','Prefetch recorded content and support seeking and continuous playout with a large buffer.','Lecture bắt đầu trước khi full file download.','A lecture starts before the full file downloads.'),
 C('l11-media','Conversational media','Conversational media','Ưu tiên sub-400ms turn-taking delay hơn perfect retransmitted delivery.','Prioritize sub-400ms turn-taking delay over perfect retransmitted delivery.','Users nói chồng nhau khi delay tăng.','Users talk over one another as delay rises.'),
 C('l11-voip','Sampling and quantization','Sampling and quantization','Đo analog signal nhiều lần/s rồi map amplitudes sang finite-bit values.','Measure an analog signal many times per second and map amplitudes to finite-bit values.','PCM speech dùng8000 samples/s và8 bits/sample.','Speech PCM uses8000 samples/s and8 bits/sample.'),
 C('l11-voip','VoIP signaling','VoIP signaling','Locate users, establish/redirect, negotiate và manage participants.','Locate users, establish or redirect sessions, negotiate, and manage participants.','SIP callee accept call và agree codec.','A SIP callee accepts a call and agrees on a codec.'),
 C('l11-qos','End-to-end delay','End-to-end delay','Tổng encoding, packetization, network, playout và decoding delays.','The sum of encoding, packetization, network, playout, and decoding delays.','Mouth-to-ear latency vượt400ms.','Mouth-to-ear latency exceeds400ms.'),
 C('l11-qos','Delay jitter','Delay jitter','Variation in packet delay, không phải chỉ average delay.','Variation in packet delay, not merely average delay.','Voice packets lần lượt mất80,180,90ms.','Voice packets take80,180,90ms.'),
 C('l11-qos','Playout buffer','Playout buffer','Giữ arrivals rồi drain đều, giảm late gaps nhưng tăng all-packet delay.','Hold arrivals and drain steadily, reducing late gaps but increasing all-packet delay.','Receiver chờ thêm60ms trước phát audio.','A receiver waits an extra60ms before playing audio.'),
 C('l11-loss','Forward error correction','Forward error correction','Gửi redundant parity/copy để reconstruct loss không round trip.','Send redundant parity or copies to reconstruct loss without a round trip.','Mỗi n audio chunks kèm XOR chunk.','Every n audio chunks include an XOR chunk.'),
 C('l11-loss','Interleaving','Interleaving','Phân tán consecutive audio chunks qua packets để burst loss thành gaps nhỏ.','Disperse consecutive audio chunks across packets so burst loss becomes small gaps.','Một packet loss ảnh hưởng nhiều nonadjacent snippets.','One packet loss affects several nonadjacent snippets.'),
 C('l11-loss','Error concealment','Error concealment','Receiver repeat/interpolate short missing audio locally.','The receiver repeats or interpolates short missing audio locally.','Lost 10ms được thay bằng previous sample.','A lost10ms interval is replaced by the previous sample.'),
 C('l11-compression','I/P/B frames','I, P, and B frames','I độc lập; P dùng past; B dùng past và future references.','I is independent, P uses the past, and B uses past and future references.','Mất I-frame phá decode nhiều dependent frames.','Losing an I frame breaks many dependent frames.'),
 C('l11-http','HTTP paced streaming','HTTP paced streaming','Client dùng range/segment requests và ON-OFF buffer thresholds.','The client uses range or segment requests and ON-OFF buffer thresholds.','Buffer full nên player đợi trước GET tiếp.','The buffer is full, so the player waits before the next GET.'),
 C('l11-dash','DASH manifest','DASH manifest','Liệt kê representations, segments và URLs để client biết options.','List representations, segments, and URLs so the client knows its options.','Player tải metadata trước segment đầu.','A player downloads metadata before the first segment.'),
 C('l11-rate','Rate-based adaptation','Rate-based adaptation','Estimate future capacity từ past chunk throughput rồi chọn rate có safety margin.','Estimate future capacity from past chunk throughput and choose a rate with a safety margin.','Harmonic mean estimate được quantize xuống bitrate.','A harmonic-mean estimate is quantized down to a bitrate.'),
 C('l11-buffer','Buffer-based adaptation','Buffer-based adaptation','Chọn rate tăng theo buffer occupancy với reservoir/cushion regions.','Choose a rate increasing with buffer occupancy using reservoir and cushion regions.','Near-empty buffer ép minimum representation.','A near-empty buffer forces the minimum representation.')
]);

buildConceptPractice(12,[
 C('l12-why','Content delivery network','Content delivery network','Distributed edge servers/caches serve replicas closer to users.','Distributed edge servers and caches serve replicas closer to users.','Popular video được phục vụ từ ISP-local cache.','A popular video is served from an ISP-local cache.'),
 C('l12-why','Origin shielding','Origin shielding','Cache repeated objects để giảm origin bandwidth/load và failure exposure.','Cache repeated objects to reduce origin bandwidth, load, and failure exposure.','Một edge fetch một lần rồi serve nghìn hits.','An edge fetches once and serves thousands of hits.'),
 C('l12-placement','Enter deep','Enter deep','Đặt nhiều clusters nhỏ sâu trong access ISPs để rút path.','Place many small clusters deep inside access ISPs to shorten paths.','Cache chỉ cách users một ISP hop.','A cache is only one ISP hop from users.'),
 C('l12-placement','Bring home','Bring home','Đặt ít clusters lớn tại IXPs/key sites để dễ pool/maintain.','Place fewer large clusters at IXPs or key sites for easier pooling and maintenance.','Regional mega-cluster phục vụ nhiều access networks.','A regional mega-cluster serves many access networks.'),
 C('l12-operation','DNS CDN delegation','DNS CDN delegation','Provider DNS trả CDN hostname, rồi CDN authoritative chọn edge IP.','Provider DNS returns a CDN hostname, then the CDN authoritative system selects an edge IP.','video.provider CNAME tới a1130.cdn.','video.provider CNAMEs to a1130.cdn.'),
 C('l12-operation','LDNS mapping bias','LDNS mapping bias','CDN thường thấy resolver location thay vì actual client location.','A CDN often sees resolver location instead of actual client location.','Remote public resolver làm user map sai region.','A remote public resolver maps a user to the wrong region.'),
 C('l12-cluster','Passive cluster measurement','Passive cluster measurement','Dùng QoE của existing sessions/subnets để map future clients.','Use QoE from existing sessions and subnets to map future clients.','Controller học rebuffer rate cho subnet→cluster pairs.','A controller learns rebuffer rates for subnet-to-cluster pairs.'),
 C('l12-cluster','Controlled exploration','Controlled exploration','Gửi một ít clients tới alternatives để cập nhật performance knowledge.','Send a small fraction of clients to alternatives to refresh performance knowledge.','Current-best policy thử cluster B cho1% sessions.','A current-best policy tests cluster B for1% of sessions.'),
 C('l12-server','Lazy cache fill','Lazy cache fill','Cold server fetch object từ origin on demand rồi cache cho future hits.','A cold server fetches an object from origin on demand and caches it for future hits.','First request chậm hơn later requests.','The first request is slower than later requests.'),
 C('l12-server','Consistent hashing','Consistent hashing','Map servers/objects vào ring và assign object cho clockwise successor.','Map servers and objects onto a ring and assign an object to its clockwise successor.','Server fail chỉ remap keys trong một ring interval.','A server failure remaps keys in one ring interval.'),
 C('l12-dns','Recursive DNS query','Recursive DNS query','Server được hỏi chịu trách nhiệm trả final answer thay client.','The queried server assumes responsibility for returning a final answer.','Host yêu cầu LDNS resolve full name.','A host asks its local resolver to resolve the full name.'),
 C('l12-dns','Iterative DNS referral','Iterative DNS referral','Server trả next authoritative server để resolver hỏi tiếp.','A server returns the next authoritative server for the resolver to query.','Root trả .edu TLD address.','A root returns the .edu TLD address.'),
 C('l12-dns','DNS TTL','DNS TTL','Giới hạn cache lifetime và tốc độ CDN mapping refresh.','Bound cache lifetime and CDN mapping refresh speed.','Edge fail nhưng cached A record còn30s.','An edge fails while a cached A record remains for30s.'),
 C('l12-protocols','IP anycast','IP anycast','Nhiều sites announce same IP và BGP route client tới selected path.','Multiple sites announce the same IP and BGP routes a client to the selected path.','Google DNS address được announce ở nhiều locations.','A Google DNS address is announced from many locations.'),
 C('l12-protocols','HTTP redirection','HTTP redirection','Server trả3xx Location để client request another server sau initial request.','A server returns a3xx Location so the client requests another server after the initial request.','Overloaded edge trả302 tới peer edge.','An overloaded edge returns302 to a peer edge.')
]);
